### ISSUE TITLE
Property apiVersion is not allowed.

### ISSUE THREAD

**Issue by chesha1** [redhat-developer/vscode-yaml#1014]
The following content with file name `deploy.yaml` produces this bug.

```yaml
apiVersion: apps/v1
kind: Deployment
``` 

It says, Property apiVersion is not allowed.yaml-schema: Deployer Recipe

When the file is renamed, the error notification disappears.

Darwin arm64 23.2.0, vscode version 1.87.2

**Comment by mackenzie1** [comment]
Rename the file to deploy-xxx.yaml. See https://stackoverflow.com/questions/69493762/visual-studio-code-showing-error-property-stages-is-not-allowed-property-param
