### ISSUE TITLE
Is it possible to have a schema file defined locally?

### ISSUE THREAD

**Issue by nicholas-devlin** [redhat-developer/vscode-yaml#102]
I am able to link to urls to provide a custom schema e.g.

`"https://raw.githubusercontent.com/nicholas-devlin/datadog-yaml-schema/master/kedge-schema.json": "/myKedgeFile.yaml"`

It works correctly and does autofill and all that good stuff. But when I try to set it to a local file path: 

`"/Users/nicholas.devlin/Developer/datadog-yaml-schema/kedge-schema.json": "/myKedgeFile.yaml"`

I just get an error like `unable to load schema from <path> No content found`. Looks like it's coming from [this area](https://github.com/redhat-developer/yaml-language-server/blob/6fbc00d8d0e9d8cc549a08420418a7baf1816d1a/src/languageservice/services/jsonSchemaService.ts#L386) in the code.

I'm testing this out by just copy/pasting the kedge schema since I know that doesn't have any typos in it.

**Comment by nicholas-devlin** [comment]
Awesome thanks. Sorry for not finding that issue earlier, didn't realize I could search through archived.

**Comment by JPinkney** [comment]
No worries, perhaps I should make a note of it in the readme regardless though because I think its pretty important!

**Comment by nicholas-devlin** [comment]
Yeah, It took me a bit to even understand how the setting worked. It might be helpful to just have a more detailed example of the usage of that setting. I think I saw something in that gif about it, but the gif was like 3 minutes long and i couldn't find the spot again, that should really be split up or just link to a video lol.
