### ISSUE TITLE
Is this repo dead?

### ISSUE THREAD

**Issue by thernstig** [redhat-developer/vscode-yaml#1068]
There are many, very old issues and PRs now that has no attention at all.

Is Redhat not supporting this extension anymore.

There is a large user base of this extension, so it would be good with some confirmation.

**Comment by thernstig** [comment]
Wrote https://github.com/redhat-developer/vscode-openshift-tools/issues/4666

**Comment by msivasubramaniaan** [comment]
Hello @thernstig
