### ISSUE TITLE
extension commands not showing up in command palette

### ISSUE THREAD

**Issue by govindrai** [redhat-developer/vscode-yaml#108]
The extension installs (I can see the downloaded package in the extensions folder) but I cannot actually use the extension as I cannot see any of the commands in the command palette.

**Comment by JPinkney** [comment]
There aren't any commands for this extension. There are only preferences for this extension.

**Comment by govindrai** [comment]
Thanks for the swift reply. I don't see these preferences in settings either. If I manually add, say `yaml.format.enable: true` I get a "unknown configuration setting". I apologize if the answer is obvious.

**Comment by JPinkney** [comment]
Did you by any chance install https://marketplace.visualstudio.com/items?itemName=adamvoss.yaml#review-details? If not then what is your VSCode version and when you open up a yaml file in the output tab can you see output from the tab that says "YAML support"?

**Comment by JPinkney** [comment]
@govindrai Are you still running into this issue or can I close?

**Comment by govindrai** [comment]
You can close this. I haven’t needed to use the extension in a while.
