### ISSUE TITLE
Couldn't start client Yaml Support

### ISSUE THREAD

**Issue by ntomka** [redhat-developer/vscode-yaml#111]
When I open a YAML file, vscode reports an error saying extension cannot start client:

![image](https://user-images.githubusercontent.com/2313363/44253648-95b27380-a200-11e8-85c7-547922cf92ad.png)

Developer tools can't say more:

![image](https://user-images.githubusercontent.com/2313363/44253723-c85c6c00-a200-11e8-950a-2ad822bc2689.png)

**Comment by JPinkney** [comment]
What version of VSCode and what OS are you using?

**Comment by ntomka** [comment]
Latest vscode: 1.26.1
OS: KDE Neon, based on Ubuntu 16.04

**Comment by JPinkney** [comment]
Can you try to uninstall then reinstall? I've never seen it fail to start before

**Comment by ntomka** [comment]
Yes, that was my first reaction. :) But I tried it again now and I have the same results. Can it interfere with some other extension?

**Comment by JPinkney** [comment]
Hmm, there are a few extensions that use it i'm wondering if somehow they're breaking it? Can you list your extensions that are kubernetes/yaml related?

**Comment by ntomka** [comment]
I have no other related to them, but now I disabled all my extensions except yaml support and I have no luck:

![image](https://user-images.githubusercontent.com/2313363/44520988-d95e1f00-a6d1-11e8-8b45-ab7a8625e89d.png)

**Comment by ntomka** [comment]
Ok, I found out what caused the problem. I have problem with another extension before and I enabled `--inspect-extensions=9333` in code's shortcut to be able to debug it. After removing this cmd option I am not receiving this message anymore.

**Comment by JPinkney** [comment]
Is everything working then? Can I close?

**Comment by ntomka** [comment]
Yes. I tried outlining, and it works like a charm. But I still don't get why it interfere with --inspect-extensions cmd option. :)

**Comment by JPinkney** [comment]
I'm not too sure why either. I don't think theres anything on my side thats causing the issue. I wonder if its something in VSCode?

**Comment by ntomka** [comment]
:man_shrugging: Thanks anyway. :)
