### ISSUE TITLE
Formatter removes valid custom tags

### ISSUE THREAD

**Issue by mhanney** [redhat-developer/vscode-yaml#112]
I'm using customTags for AWS CloudFormation .yml such as "yaml.customTags": ["!Ref scalar"]. This works great with "yaml.validate": true. But when I use format document, they get completely stripped out. I'm using 0.0.14. It was working before https://github.com/redhat-developer/vscode-yaml/issues/90

**Comment by bingtimren** [comment]
I also encountered this bug. After format, "!Ref" and "!GetAttr" was removed from my document. I have thought that a formatter should never add or remove any thing rather than white spaces.

**Comment by JPinkney** [comment]
Hi! This should be fixed in version 0.0.17 (we switched formatters).
