### ISSUE TITLE
Please provide a method to provide yaml validation, completely without schemas

### ISSUE THREAD

**Issue by zoredache** [redhat-developer/vscode-yaml#113]
I think it is clear from the bunch of issues here that the schema for ansible sucks.  I would like to just completely disable that.

Please either **document** or create a way for me to completely disable use of schemas, but still have basic validation of yaml syntax.

**Comment by JPinkney** [comment]
Given that this is open source do you want to contribute a way to disable use of schemas? Relevant code: https://github.com/redhat-developer/yaml-language-server/blob/master/src/server.ts#L240.

**Comment by JPinkney** [comment]
This has been added in 0.3.0. We now have a setting called yaml.schemaStore.enable that when set to false, stops the extension from automatically pulling schemas from the schema store. However, you will still have basic validation of yaml syntax.
