### ISSUE TITLE
How does the LS decide which yml file to care about?

### ISSUE THREAD

**Issue by mickaelistria** [redhat-developer/vscode-yaml#12]
At the moment, it seems like the Language Server and the VSCode extension tries to process any `.yml` file. However, there are many `.yml` files that are not necessarily using the k8s schema. Does the language make a difference? If yes, what's the trigger?

**Comment by JPinkney** [comment]
I've added this to the master branch on my repo but I haven't merged it here yet because I want to do some additional testing. I've added a setting called "k8s.glob" and then you use that to choose which files you want to use with the language server via a glob pattern

**Comment by mickaelistria** [comment]
So it would be based on filename patterns? or on content patterns?

**Comment by JPinkney** [comment]
Currently filename patterns

**Comment by mickaelistria** [comment]
Ok, thanks for the answer. And which patterns are used? Are all users using
the same name patterns?
If not, I believe it would be interesting to try some "content detection",
ie if a yaml file has a few nodes that seem typically k8s, we enable the
k8s-ls, otherwise we ignore.
WDYT?

**Comment by JPinkney** [comment]
Currently its using https://www.npmjs.com/package/glob and by default the pattern is **/*.yaml (should also be **/*.yml as well but I haven't added that yet). I think using this node module allows for a lot of flexibility for file pattern matching but I can also talk to Gorkem and see if its a possibility to add content detection. The only problem I can foresee with that is if we get false positives and its validating a file that shouldn't be validated it could get annoying for the end user. However, If we did go that route we could have a setting for validating by filename patterns or validating by content detection and let the user decide.

**Comment by mickaelistria** [comment]
In general, users don't like to have choice too early; they prefer having
decent default settings and then tweak them progressively as they use the
tool.
If LS shows some diagnostic on a file that has risks of not being a valid
target, it could create a "disable k8s checks" quickfix to instruct the LS
to ignore the file. However, for the other way round (instruct the LS to
cover a specific file), I don't know a good way to proceed.
In any case, if `whatever.yml` is allowed, the LS would need to watch the
file even if it's not a k8s file, in order to suppot the case of newly
created file (no content to enable LS initially, but the triggers words can
be added any time).

**Comment by JPinkney** [comment]
I agree, I could look into doing some smart detection and try and figure out how I could accomplish that. In the case of covering a specific file I think I could still utilize the already defined setting for that as an option but I'll have to look into it more because I think it might be really inconvenient for a user to have to add a bunch of files into the setting.

**Comment by gorkem** [comment]
I think opt-out makes more sense for this extension let's do the "disable k8s checks" quickfix/settings

**Comment by JPinkney** [comment]
I've added this feature in the newest release. To deactivate you need to click F1 then disable kubernetes validation on this file and activate is F1 then enable kubernetes validation on this file. By default the validation is on!

**Comment by mickaelistria** [comment]
Is this supposed to work in other editors/ides such as Eclipse IDE?

**Comment by JPinkney** [comment]
We want to make this as compatible with as many IDE's as possible. I'm not sure how to build the language server and run it in eclipse so I'm not able to test on it. If eclipse doesn't support this I can make an official keybinding if that would work better? (Its just adding a few lines of code) or is there any other ways you know of in eclipse that might work better?

**Comment by gorkem** [comment]
I think this is using the `didChangeConfiguration` event so any client that hooks into config changes should be fine

**Comment by gorkem** [comment]
closing this one if anything specific to LS needs to be done please report there.
