### ISSUE TITLE
Use HTTP proxy settings when loading schema

### ISSUE THREAD

**Issue by lashchev** [redhat-developer/vscode-yaml#122]
The extension cannot load schema when HTTP_PROXY and HTTPS_PROXY are properly configured.
Configuring "http.proxy" and "http.proxyStrictSSL" workspace settings does not help.

VSCode-yaml extension v0.0.16
VSCode: (windows portable install)
Version: 1.27.2
Commit: f46c4c469d6e6d8c46f268d1553c5dc4b475840f
Date: 2018-09-12T16:17:45.060Z
Electron: 2.0.7
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64

**Comment by gorkem** [comment]
Are you still seeing this behavior at least http.proxy seems to work for me.

**Comment by gorkem** [comment]
closing
