### ISSUE TITLE
DeprecationWarning for Unhandled promise rejections

### ISSUE THREAD

**Issue by lashchev** [redhat-developer/vscode-yaml#127]
"Yaml Support" log shows this error:
```
[Error - 6:11:37 PM] (node:2616) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code
```
and a lot of errors like this:
```
[Error - 6:11:37 PM] (node:2616) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 4): #<Object>
```

redhat.vscode-yaml v0.0.17

Window 10 v1809 x64
Version: 1.28.0
Commit: 431ef9da3cf88a7e164f9d33bf62695e07c6c2a9
Date: 2018-10-05T14:58:53.203Z
Electron: 2.0.9
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64

**Comment by JPinkney** [comment]
Is there any specific action that makes the log show up?

**Comment by lashchev** [comment]
The following triggers the errors:
1. Opening YAML file (that has schema errors) - leads to error 2 following by error 1 and error 2 again.
2. Changing `yaml.schemas` leads to error 2 in the logs

Changing YAML or schema doesn't produce the errors.

**Comment by imroc** [comment]
I got these errors too

**Comment by MitBit01** [comment]
I get these errors once the extension, regardless of whether or not the file is valid Yaml.

**Comment by celsoandrade** [comment]
I get the same error multiple time

**Comment by adelwin** [comment]
I'm getting the same error, regardless of whether or not the file is valid or not.
It only happens when opening a YAML file, the first one.
My vscode version is 1.29, and running on MacOS Mojave

If there's any other information needed to pinpoint the issue, let me know.

**Comment by JPinkney** [comment]
Do you have something like autoformat or something like that on? I'm having a hard time finding the issue because I cannot reproduce

**Comment by adelwin** [comment]
I don't have vim plugin installed tho.
Maybe do you know what are the customization of your Vim plugin?

**Comment by Shenmin-Z** [comment]
vim plugin specific:
```json
{
  "vim.hlsearch": true,
  "vim.leader": "<space>",
  "vim.normalModeKeyBindingsNonRecursive": [
    {
      "before": ["leader", "w"],
      "commands": [
        {
          "args": [],
          "command": "workbench.action.files.save"
        }
      ]
    }
  ],
  "vim.useSystemClipboard": true,
  "vim.statusBarColorControl": true,
}
```

full settings:
```json
{
  "editor.codeLens": false,
  "editor.lineNumbers": "relative",
  "editor.minimap.enabled": true,
  "editor.minimap.showSlider": "always",
  "editor.minimap.side": "left",
  "editor.tabSize": 2,
  "editor.wordWrap": "on",
  "emmet.triggerExpansionOnTab": true,
  "explorer.openEditors.visible": 0,
  "git.enableSmartCommit": true,
  "terminal.integrated.shell.windows": "C:\\Program Files\\Git\\bin\\bash.exe",
  "vim.hlsearch": true,
  "vim.leader": "<space>",
  "vim.normalModeKeyBindingsNonRecursive": [
    {
      "before": ["leader", "w"],
      "commands": [
        {
          "args": [],
          "command": "workbench.action.files.save"
        }
      ]
    }
  ],
  "vim.useSystemClipboard": true,
  "window.title": "${dirty}${activeEditorShort}${separator}${activeEditorMedium}",
  "workbench.colorTheme": "One Dark Pro",
  "workbench.startupEditor": "newUntitledFile",
  "explorer.confirmDelete": false,
  "window.titleBarStyle": "custom",
  "typescript.updateImportsOnFileMove.enabled": "never",
  "emmet.showExpandedAbbreviation": "inMarkupAndStylesheetFilesOnly",
  "editor.fontSize": 15,
  "javascript.updateImportsOnFileMove.enabled": "never",
  "vim.statusBarColorControl": true,
  "files.exclude": {
    "**/.git": true,
    "**/.svn": true,
    "**/.hg": true,
    "**/CVS": true,
    "**/.DS_Store": true,
    // "node_modules": true
  },
  "workbench.colorCustomizations": {
    "statusBar.background": "#5f00af",
    "statusBar.noFolderBackground": "#5f00af",
    "statusBar.debuggingBackground": "#5f00af"
  },
  "breadcrumbs.enabled": true,
  "git.autofetch": true,
  "explorer.confirmDragAndDrop": false,
  "javascript.implicitProjectConfig.experimentalDecorators": true,
  "extensions.ignoreRecommendations": true
}
```

**Comment by lashchev** [comment]
@JPinkney I do have auto-save and auto-format on

**Comment by pcevela** [comment]
Same issue here. Only other extension is Bash Beautify.
Plugin version 0.3.0

Version: 1.31.1 (user setup)
Commit: 1b8e8302e405050205e69b59abb3559592bb9e60
Date: 2019-02-12T02:20:54.427Z
Electron: 3.1.2
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17134

**Comment by JPinkney** [comment]
Thanks everyone for the debugging info! I haven't found the cause yet but all the diagnostics everyone gave should give me a few places to look!

**Comment by rroblik** [comment]
+1

**Comment by Groumy** [comment]
If I may, I have the same issue with a french os.

It might not be the issue, but it is an issue with so many tools, that I feel obligated to share ;)

**Comment by kenankule** [comment]
I've seen this happening in an environment where my access to the json schema server is blocked (due to firewall or vpn) and "yaml.schemaStore.enable": true. 
I believe the extension is trying to download some schemas from the json schema server automatically and failing.
I was able to use local schemas using the file protocol and "yaml.schemas" variable. In that case the extension worked just fine.

**Comment by JPinkney** [comment]
I believe I was finally able to solve the issue! It was a super simple fix too: https://github.com/redhat-developer/yaml-language-server/pull/183/files. it should be available in the next release

**Comment by adelwin** [comment]
@JPinkney sorry, when you say "next release" is exactly which release of vscode?
