### ISSUE TITLE
latest travis schema is not used for .travis.yml files

### ISSUE THREAD

**Issue by ssbarnea** [redhat-developer/vscode-yaml#128]
It seems that extension complains about directories block inside cache but this is covered by the schema published at https://github.com/ssbarnea/schemastore/blob/master/src/schemas/json/travis.json#L755

```
---
language: python
cache:
  - pip
  - directories:
      - "node_modules"
      - $HOME/.cache
```

This is expected too pass, but in fact it reports `directories` as invalid value.

This makes me think that the schema being used is outdated but I have no idea which schema was used by the plugin,... or at least I don't know where to look.

**Comment by JPinkney** [comment]
I've just tested this out again and it seems to be working for me. I know this issue has been open a while so perhaps the issue has resolved itself. When you get a chance let me know if you can still reproduce on your end and I can look further into it!

**Comment by gorkem** [comment]
Closing this one, please reopen if it is still valid
