### ISSUE TITLE
It should be clear what JSON Schema version is supported

### ISSUE THREAD

**Issue by lashchev** [redhat-developer/vscode-yaml#129]
Sorry, maybe I am looking in the wrong places, but I cannot find any information on what JSON Schema versions are supported by this extension: `draft-04`, `draft-06`, `draft-07`?

**Comment by JPinkney** [comment]
I believe its draft-04 though I'll have to check. A lot of the json stuff was able to be re-used from the json language service so it would be whatever that was when I used some of that code.

**Comment by lashchev** [comment]
It would be great to document this on the main project page, because json-schema is moving forward and draft-07 is current mainstream for a while now. At least all our schemas are in draft-07.
Draft-08 is coming out soon.

Are there any plans to start supporting draft-07 (Core, Validation, Hyper-Schema, Relative JSON Pointer) any time soon?

**Comment by JPinkney** [comment]
If I have time then potentially. I work part-time 12 hours per week and am a full-time student so its kind of hard to get to everything when I'm the only one who contributes to this project.

**Comment by lashchev** [comment]
@JPinkney Thanks for your effort! Not a lot of free time on my side as well, but in case you need any help or the second pair of eyes - feel free to ping me. I won't promise a prompt reply, but will eventually get to the task)

**Comment by andxu** [comment]
Hi @lashchev, are you using yaml extension together with this extension https://github.com/Azure/vscode-kubernetes-tools ? if so, the schema is provided by the integrated ones generated by me, https://github.com/Azure/vscode-kubernetes-tools/blob/master/schema/swagger-v1.9.3.json, if it is out of date, please provide a test yaml for me and I will update the schema.
