### ISSUE TITLE
"uniqueItems" array items schema validation is not checked

### ISSUE THREAD

**Issue by lashchev** [redhat-developer/vscode-yaml#130]
If the schema has `uniqueItems=true` set for an array - extension doesn't highlight duplicated items.

redhat.vscode-yaml: 0.0.17
VSCode:
Version: 1.28.0
Commit: 431ef9da3cf88a7e164f9d33bf62695e07c6c2a9
Date: 2018-10-05T14:58:53.203Z
Electron: 2.0.9
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64

**Comment by JPinkney** [comment]
Hmm...... it looks as though the functionality is [there](https://github.com/redhat-developer/yaml-language-server/blob/master/src/languageservice/parser/jsonParser.ts#L399). Are you able to provide some sample schema that I can test it against just so I can see where its going wrong?

**Comment by JPinkney** [comment]
I've just tried with:
```JSON
{
  "type": "array",
  "uniqueItems": true
}
```

and 
```YAML
- 1
- 2
- 1
```

and the error is reported now.
