### ISSUE TITLE
Is it possible make a port compatible with monaco?

### ISSUE THREAD

**Issue by palvarezcordoba** [redhat-developer/vscode-yaml#132]
I want to use autocompletion in a webapp, is it possible to make a port compatible with monaco?
It will be hard?

**Comment by JPinkney** [comment]
I've found https://github.com/kpdecker/monaco-yaml and https://github.com/Microsoft/monaco-editor/issues/131. It looks like the first link is an old version of yaml-language-server.

**Comment by pengx17** [comment]
@palvarezcordoba I've took @kpdecker 's idea and updated some of the dependences here in my own fork: https://github.com/pengx17/monaco-yaml and published at npm `@alauda/monaco-editor`
It should be working with latest monaco-editor and it baked with a recent yaml-language-server at AMD bundles.

**Comment by kpdecker** [comment]
Glad to pass maintenance of the monaco-yaml package on if you have the cycles. The project I had using monago didn't end up taking off so I'm not working much in this realm these days.

**Comment by pengx17** [comment]
@kpdecker Sure, I am willing to take it over and maintain it with a regular basis.
