### ISSUE TITLE
Formatter removes Document Start "---"

### ISSUE THREAD

**Issue by shamsalmon** [redhat-developer/vscode-yaml#134]
When turning on format on save it removes document start. This seems like poor practice.

**Comment by rcjsuen** [comment]
I think it uses [prettier](https://github.com/prettier/prettier) to implement this. Perhaps there could be a way to tweak this?

https://github.com/redhat-developer/yaml-language-server/blob/ed82ac4f94226642c87779b222586f38b9989d92/src/languageservice/services/yamlFormatter.ts

**Comment by JPinkney** [comment]
There's some discussion on it on prettier: https://github.com/prettier/prettier/issues/5013

**Comment by JPinkney** [comment]
This should be fixed with version 0.2.0.
