### ISSUE TITLE
Validate JSON array error

### ISSUE THREAD

**Issue by YingmingHu** [redhat-developer/vscode-yaml#140]
After set `yaml.customTags` to edit AWS CloudFormation template as following:
```json
    "yaml.customTags": [
            "!And",
            "!If",
            "!Not",
            "!Equals",
            "!Or",
            "!FindInMap",
            "!Base64",
            "!Cidr",
            "!Ref",
            "!Sub",
            "!GetAtt",
            "!GetAZs",
            "!ImportValue",
            "!Select",
            "!Split",
            "!Join"
        ],
```
Please refer this example:
![image](https://user-images.githubusercontent.com/1429198/49271175-89001580-f4a7-11e8-8018-1d7f937c6d02.png)
Actually, it is a valid yaml fragment.

**Comment by JPinkney** [comment]
Inside of yaml.customTags join !Join should have type sequence.

yaml.customTags: [
     "!Join sequence"
]

then it should work. When you omit a type it defaults to scalar which may be why the error is being shown.

**Comment by YingmingHu** [comment]
It works for me. Thank you @JPinkney
