### ISSUE TITLE
Formatter always convert the document indent to 2 spaces even if setting is 4

### ISSUE THREAD

**Issue by bingtimren** [redhat-developer/vscode-yaml#143]
If I right click and choose "Format document", even if I have work space setting as follows, the formatter still converts the indent size from my original 4 spaces in the document to 2 spaces. The formatter should respect the settings.

```{
    "yaml.format.enable":true,
    "yaml.customTags": [
        "!Ref","!GetAtt"
    ],
    "[yaml]": {
        "editor.insertSpaces":true,
        "editor.tabSize":4,
        "editor.quickSuggestions":true
    }    
}```

**Comment by Vincz** [comment]
Same here... Regardless of my settings set to 4, it always indents with 2 spaces.
Switching back to the prettier formatter for now, waiting for this to be fixed.

**Comment by jbutz** [comment]
I opened looked at the language server and noticed that it is just using Prettier. I opened redhat-developer/yaml-language-server#122 to cover adding the `tabWidth` and `useTabs` settings

**Comment by JPinkney** [comment]
Using tabWidth is fixed by https://github.com/redhat-developer/yaml-language-server/commit/1458e25926c7189cefc383141f4fad1d14a568b8 but there hasn't been a release yet.

**Comment by JPinkney** [comment]
This had been added in the 0.3.0 release!
