### ISSUE TITLE
directives end is not properly detected when validating YAML documents

### ISSUE THREAD

**Issue by arnauldvm** [redhat-developer/vscode-yaml#150]
According to specs, end of directives is detected by rule "c-directives-end" (https://yaml.org/spec/1.2/spec.html#c-directives-end), i.e. 3 consecutives dashes at the beginning of the line.

However, starting a file like this:
```
%YAML:1.0
---
dummy: foo
```
results in the following error:
`directives end mark is expected (2, 2)`

If I introduce a random character at the beginning of that line, the error does not occur:
```
%YAML:1.0
@---
dummy: foo
```
---
Extension version: redhat.vscode-yaml 0.2.1
VSCode version: 
```
Version: 1.30.2 (system setup)
Commit: 61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8
Date: 2019-01-07T22:53:57.820Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
OS: Windows_NT ia32 6.1.7601
```

**Comment by JPinkney** [comment]
I think its because the parser is specifically for yaml 1.2 perhaps?

Using:
```
%YAML 1.2
---
hello: world
```

does not create any errors

**Comment by gorkem** [comment]
I can no longer replicate this behaviour. Probably fixed with the new parser.
