### ISSUE TITLE
Intelisense trigger by schema 'examples' property

### ISSUE THREAD

**Issue by Ash258** [redhat-developer/vscode-yaml#154]
When your [json schema](https://github.com/lukesampson/scoop/blob/master/schema.json) contains [examples property](https://github.com/lukesampson/scoop/blob/a98c56edf399fc6212ec74200e179cca2be0a5cb/schema.json#L355-L376) intelisense should be triggered as in vscode's native json extension.

![Yaml](https://i.imgur.com/1ARiUGW.png)

![Json](https://i.imgur.com/4ysjs72.png)

> Extension: 0.2.1
> Vscode: 1.31.0-insider 8f56013e8f66650c1b0b65cc5c502691e307db21

**Comment by JPinkney** [comment]
This is available in 0.7.0!
