### ISSUE TITLE
No Reload Adoption: Update `yamlValidation` contributions when extensions are added/removed

### ISSUE THREAD

**Issue by sandy081** [redhat-developer/vscode-yaml#156]
Hi, I am a developer from VS Code and in the last release `1.31`, we added a new feature - no reload is required on installing an extension - https://code.visualstudio.com/updates/v1_31#_no-reload-on-install

But there are some exceptions to it as mentioned in the doc. If the extension is contributing to external contribution points, then the extension requires reload after installing. Hence, we added a new listener API for the owners of the external contribution point to listen to extension addition/removal and can update its state - https://code.visualstudio.com/updates/v1_31#_extensions-change-event.

Our plan is to give extensions one milestone/month for adopting to the above API and make the other extensions consuming their contribution points ready for no reload. It means that from next release, above exception will be removed and all extensions are added to VS Code window immediately after installation and no reload is shown.

We scanned the extensions in the marketplace and found out that this extension uses an external contribution point `yamlValidation` and requires reload on install. I found out from code that this extension owns this contribution point and couple of popular extensions (ms-python.python) contributes to it which forces them to reload on install. So please adopt to the above API and make this and other contribution extensions ready for no reload.

Thanks

**Comment by JPinkney** [comment]
Hi, from my understand all we need to do is add the extensions.onDidChange endpoint and then it should be good. Is that correct?

I've opened a PR to fix that (https://github.com/redhat-developer/vscode-yaml/pull/160) but I just wanted to make sure thats all we need to do on our side.

**Comment by sandy081** [comment]
I cannot confirm but kinda looks correct. But please test it with the latest insiders and if you are receiving the event when an extension that is using your contribution point is installed and also it is working as expected.

**Comment by JPinkney** [comment]
This has been added and the new api has been adopted. It will be available in the next release.
