### ISSUE TITLE
yaml.format.enable setting has opposed effect

### ISSUE THREAD

**Issue by remcohaszing** [redhat-developer/vscode-yaml#158]
I use prettier to format yaml code. I recently noticed the formatting was wrong. After some digging around, I found out this is because the vscode yaml extension also formats my code, taking precedence over prettier.

When I set `"yaml.format.enable": true`, the code is formatted using prettier. When I set `"yaml.format.enable": false`, or the setting is omitted, the code is formatted using the vscode yaml extension.

I believe a boolean should be flipped somewhere.

**Comment by JPinkney** [comment]
Prettier is the the same formatter that [this extension uses as well](https://github.com/redhat-developer/yaml-language-server/blob/master/src/languageservice/services/yamlFormatter.ts). I'll look into seeing where the flip would be.

**Comment by JPinkney** [comment]
The fix will be available in the next release!

**Comment by devoto13** [comment]
@JPinkney It looks more like this setting has no effect at all anymore, judging from [this change](https://github.com/redhat-developer/yaml-language-server/commit/8c54e34685578ba37f02d137386b80a8821004dd#diff-916156c481141bfcd08c6ae40ce10e00L254) it seems that the option is no longer recognized by the language server.

**Comment by JPinkney** [comment]
Its fixed as of https://github.com/redhat-developer/yaml-language-server/pull/126 but I have no released yet

**Comment by dogmatic69** [comment]
I've got 0.17.0 installed and seems like this does not work at all for formatting. 
![image](https://user-images.githubusercontent.com/94674/119638592-1a516800-be17-11eb-8cd6-67a9e16e7dc1.png)

Am I missing a config, or a regression?
