### ISSUE TITLE
Syntax checker shows error on valid YAML syntax

### ISSUE THREAD

**Issue by PraiseTheSun-MySunBro** [redhat-developer/vscode-yaml#161]
Basically, this is a valid use case of YAML, but vscode gives an error as "duplicate key" even when there are not duplicates. 

This occurs whenever you represent a sequence as keys in **? :** construction.

```
mappings:
  ? 
    - key1
    - key2
  : 
    val1

  ? 
    - key3
  :
    val2
```

**Comment by gorkem** [comment]
This has been fixed with the new parser. Closing.
