### ISSUE TITLE
Easy way to have standard yaml formatting

### ISSUE THREAD

**Issue by max-sixty** [redhat-developer/vscode-yaml#164]
(this may be an obvious question - thanks for your patience if so - I'm an infrequent yaml user who couldn't find the answer elsewhere)

I recently installed this extension through kubernetes, and it's awesome that it auto-formats yaml. But it seems to do that with non-conventional formatting (I think?), albeit correct; in particular for the indent of a sequence. This means any existing file I'm editing creates a large diff.

Take an example from https://kubernetes.io/docs/tutorials/configuration/configure-redis-using-configmap/:

```diff
index 36b3bed..0379724 100644
@@ -4,21 +4,21 @@ metadata:
   name: redis
 spec:
   containers:
-  - name: redis
-    image: kubernetes/redis:v1
-    env:
-    - name: MASTER
-      value: "true"
-    ports:
-    - containerPort: 6379
-    resources:
-      limits:
-        cpu: "0.1"
-    volumeMounts:
-    - mountPath: /redis-master-data
-      name: data
-    - mountPath: /redis-master
-      name: config
+    - name: redis
+      image: kubernetes/redis:v1
+      env:
+        - name: MASTER
+          value: "true"
+      ports:
+        - containerPort: 6379
+      resources:
+        limits:
+          cpu: "0.1"
+      volumeMounts:
+        - mountPath: /redis-master-data
+          name: data
+        - mountPath: /redis-master
+          name: config
   volumes:
     - name: data
       emptyDir: {}
@@ -26,5 +26,5 @@ spec:
       configMap:
         name: example-redis-config
         items:
-        - key: redis-config
-          path: redis.conf
\ No newline at end of file
+          - key: redis-config
+            path: redis.conf

```

Any ideas whether this is expected? Might this caused by something in my settings somewhere? Is there a 'standard' config I could use to override the sequence indent?

Thank you!

**Comment by JPinkney** [comment]
I'm not entirely aware if there is a standard way of how sequences should be formatted in YAML. I've found a few examples where there are spaces after the sequence (like how it currently formats) and no spaces at the start of the sequence (what I think you're looking for). We aren't technically in control of the formatter, it comes from https://github.com/prettier/prettier and I cannot find any setting that would allow for this. If you file an issue on https://github.com/prettier/prettier and they create a fix to allow that as a setting I will happily updated the formatter on our side!

**Comment by max-sixty** [comment]
Thanks for the fast and full response @JPinkney . I'll check out that repo. Closing this
