### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by ohumbe** [redhat-developer/vscode-yaml#166]
- Issue Type: `Performance`
- Extension Name: `vscode-yaml`
- Extension Version: `0.3.0`
- OS Version: `Darwin x64 18.2.0`
- VSCode version: `1.32.2`

redhat.vscode-yaml-unresponsive.cpuprofile.txt:
`{
    "nodes": [
        {
            "id": 1,
            "callFrame": {
                "functionName": "(root)",
                "scriptId": "0",
                "url": "",
                "lineNumber": -1,
                "columnNumber": -1
            },
            "hitCount": 0,
            "children": [
                2,
                40,
                49
            ]
        },
        {
            "id": 2,
            "callFrame": {
                "functionName": "processImmediate",
                "scriptId": "72",
                "url": "timers.js",
                "lineNumber": 624,
                "columnNumber": 25
            },
            "hitCount": 0,
            "children": [
                3
            ]
        },
        {
            "id": 3,
            "callFrame": {
                "functionName": "tryOnImmediate",
                "scriptId": "72",
                "url": "timers.js",
                "lineNumber": 662,
                "columnNumber": 23
            },
            "hitCount": 0,
            "children": [
                4
            ]
        },
        {
            "id": 4,
            "callFrame": {
                "functionName": "runCallback",
                "scriptId": "72",
                "url": "timers.js",
                "lineNumber": 690,
                "columnNumber": 20
            },
            "hitCount": 0,
            "children": [
                5
            ]
        },
        {
            "id": 5,
            "callFrame": {
                "functionName": "",
                "scriptId": "488",
                "url": "pii_removed/main.js",
                "lineNumber": 239,
                "columnNumber": 38
            },
            "hitCount": 0,
            "children": [
                6
            ]
        },
        {
            "id": 6,
            "callFrame": {
                "functionName": "processMessageQueue",
                "scriptId": "488",
                "url": "pii_removed/main.js",
                "lineNumber": 244,
                "columnNumber": 32
            },
            "hitCount": 0,
            "children": [
                7
            ]
        },
        {
            "id": 7,
            "callFrame": {
                "functionName": "handleRequest",
                "scriptId": "488",
                "url": "pii_removed/main.js",
                "lineNumber": 291,
                "columnNumber": 26
            },
            "hitCount": 0,
            "children": [
                8
            ]
        },
        {
            "id": 8,
            "callFrame": {
                "functionName": "client.onReady.then.client.onRequest",
                "scriptId": "484",
                "url": "pii_removed/extension.js",
                "lineNumber": 57,
                "columnNumber": 69
            },
            "hitCount": 0,
            "children": [
                9
            ]
        },
        {
            "id": 9,
            "callFrame": {
                "functionName": "requestCustomSchema",
                "scriptId": "515",
                "url": "pii_removed/schema-contributor.js",
                "lineNumber": 34,
                "columnNumber": 23
            },
            "hitCount": 0,
            "children": [
                10
            ]
        },
        {
            "id": 10,
            "callFrame": {
                "functionName": "requestYamlSchemaUriCallback",
                "scriptId": "1056",
                "url": "pii_removed/yaml-schema.js",
                "lineNumber": 158,
                "columnNumber": 37
            },
            "hitCount": 0,
            "children": [
                11
            ]
        },
        {
            "id": 11,
            "callFrame": {
                "functionName": "getYamlDocuments",
                "scriptId": "1000",
                "url": "pii_removed/yaml-locator.js",
                "lineNumber": 44,
                "columnNumber": 20
            },
            "hitCount": 0,
            "children": [
                12
            ]
        },
        {
            "id": 12,
            "callFrame": {
                "functionName": "ensureCache",
                "scriptId": "1000",
                "url": "pii_removed/yaml-locator.js",
                "lineNumber": 49,
                "columnNumber": 15
            },
            "hitCount": 0,
            "children": [
                13
            ]
        },
        {
            "id": 13,
            "callFrame": {
                "functionName": "parse",
                "scriptId": "1002",
                "url": "pii_removed/yaml-parser.js",
                "lineNumber": 29,
                "columnNumber": 14
            },
            "hitCount": 0,
            "children": [
                14
            ]
        },
        {
            "id": 14,
            "callFrame": {
                "functionName": "parseInternal",
                "scriptId": "1002",
                "url": "pii_removed/yaml-parser.js",
                "lineNumber": 52,
                "columnNumber": 22
            },
            "hitCount": 0,
            "children": [
                15
            ]
        },
        {
            "id": 15,
            "callFrame": {
                "functionName": "readDocument",
                "scriptId": "1002",
                "url": "pii_removed/yaml-parser.js",
                "lineNumber": 211,
                "columnNumber": 21
            },
            "hitCount": 0,
            "children": [
                16
            ]
        },
        {
            "id": 16,
            "callFrame": {
                "functionName": "composeNode",
                "scriptId": "1002",
                "url": "pii_removed/yaml-parser.js",
                "lineNumber": 759,
                "columnNumber": 20
            },
            "hitCount": 0,
            "children": [
                17
            ]
        },
        {
            "id": 17,
            "callFrame": {
                "functionName": "readBlockMapping",
                "scriptId": "1002",
                "url": "pii_removed/yaml-parser.js",
                "lineNumber": 511,
                "columnNumber": 25
            },
            "hitCount": 0,
            "children": [
                18
            ]
        },
        {
            "id": 18,
            "callFrame": {
                "functionName": "composeNode",
                "scriptId": "1002",
                "url": "pii_removed/yaml-parser.js",
                "lineNumber": 759,
                "columnNumber": 20
            },
            "hitCount": 0,
            "children": [
                19
            ]
        },
        {
            "id": 19,
            "callFrame": {
                "functionName": "readBlockMapping",
                "scriptId": "1002",
                "url": "pii_removed/yaml-parser.js",
                "lineNumber": 511,
                "columnNumber": 25
            },
            "hitCount": 0,
            "children": [
                20
            ]
        },
        {
            "id": 20,
            "callFrame": {
                "functionName": "composeNode",
                "scriptId": "1002",
                "url": "pii_removed/yaml-parser.js",
                "lineNumber": 759,
                "columnNumber": 20
            },
            "hitCount": 0,
            "children": [
                21
            ]
        },
        {
            "id": 21,
            "callFrame": {
                "functionName": "readBlockMapping",
                "scriptId": "1002",
                "url": "pii_removed/yaml-parser.js",
                "lineNumber": 511,
                "columnNumber": 25
            },
            "hitCount": 0,
            "children": [
                22
            ]
        },
        {
            "id": 22,
            "callFrame": {
                "functionName": "composeNode",
                "scriptId": "1002",
                "url": "pii_removed/yaml-parser.js",
                "lineNumber": 759,
                "columnNumber": 20
            },
            "hitCount": 2441,
            "children": [
                23,
                24,
                32,
                37,
                39,
                45,
                46,
                48,
                50,
                52,
                55,
                56,
                57,
                58,
                59,
                63,
                64
            ],
            "positionTicks": [
                {
                    "line": 823,
                    "ticks": 2441
                }
            ]
        },
        {
            "id": 23,
            "callFrame": {
                "functionName": "e",
                "scriptId": "75",
                "url": "pii_removed/bootstrap-fork.js",
                "lineNumber": 4,
                "columnNumber": 54
            },
            "hitCount": 11808,
            "children": [
                38,
                65,
                67
            ],
            "positionTicks": [
                {
                    "line": 5,
                    "ticks": 11808
                }
            ]
        },
        {
            "id": 38,
            "callFrame": {
                "functionName": "",
                "scriptId": "75",
                "url": "pii_removed/bootstrap-fork.js",
                "lineNumber": 4,
                "columnNumber": 401
            },
            "hitCount": 383,
            "children": [
                51
            ],
            "positionTicks": [
                {
                    "line": 5,
                    "ticks": 383
                }
            ]
        },
        {
            "id": 51,
            "callFrame": {
                "functionName": "indexOf",
                "scriptId": "0",
                "url": "",
                "lineNumber": -1,
                "columnNumber": -1
            },
            "hitCount": 86
        },
        {
            "id": 65,
            "callFrame": {
                "functionName": "indexOf",
                "scriptId": "0",
                "url": "",
                "lineNumber": -1,
                "columnNumber": -1
            },
            "hitCount": 5
        },
        {
            "id": 67,
            "callFrame": {
                "functionName": "stringify",
                "scriptId": "0",
                "url": "",
                "lineNumber": -1,
                "columnNumber": -1
            },
            "hitCount": 2
        },
        {
            "id": 24,
            "callFrame": {
                "functionName": "serializeRequest",
                "scriptId": "91",
                "url": "pii_removed/extensionHostProcess.js",
                "lineNumber": 595,
                "columnNumber": 222
            },
            "hitCount": 368,
            "children": [
                25,
                31,
                61
            ],
            "positionTicks": [
                {
                    "line": 596,
                    "ticks": 368
                }
            ]
        },
        {
            "id": 25,
            "callFrame": {
                "functionName": "_requestJSONArgs",
                "scriptId": "91",
                "url": "pii_removed/extensionHostProcess.js",
                "lineNumber": -1,
                "columnNumber": -1
            },
            "hitCount": 33,
            "children": [
                26,
                27,
                34,
                43,
                62,
                66
            ],
            "positionTicks": [
                {
                    "line": 596,
                    "ticks": 33
                }
            ]
        },
        {
            "id": 26,
            "callFrame": {
                "functionName": "byteLength",
                "scriptId": "25",
                "url": "buffer.js",
                "lineNumber": 507,
                "columnNumber": 19
            },
            "hitCount": 300,
            "children": [
                36
            ],
            "positionTicks": [
                {
                    "line": 530,
                    "ticks": 300
                }
            ]
        },
        {
            "id": 36,
            "callFrame": {
                "functionName": "byteLengthUtf8",
                "scriptId": "0",
                "url": "",
                "lineNumber": -1,
                "columnNumber": -1
            },
            "hitCount": 641,
            "positionTicks": [
                {
                    "line": 530,
                    "ticks": 641
                }
            ]
        },
        {
            "id": 27,
            "callFrame": {
                "functionName": "alloc",
                "scriptId": "91",
                "url": "pii_removed/extensionHostProcess.js",
                "lineNumber": 592,
                "columnNumber": 916
            },
            "hitCount": 380,
            "children": [
                28
            ],
            "positionTicks": [
                {
                    "line": 593,
                    "ticks": 380
                }
            ]
        },
        {
            "id": 28,
            "callFrame": {
                "functionName": "allocUnsafe",
                "scriptId": "25",
                "url": "buffer.js",
                "lineNumber": -1,
                "columnNumber": -1
            },
            "hitCount": 0,
            "children": [
                29
            ]
        },
        {
            "id": 29,
            "callFrame": {
                "functionName": "allocate",
                "scriptId": "25",
                "url": "buffer.js",
                "lineNumber": -1,
                "columnNumber": -1
            },
            "hitCount": 0,
            "children": [
                30,
                41
            ]
        },
        {
            "id": 30,
            "callFrame": {
                "functionName": "createPool",
                "scriptId": "25",
                "url": "buffer.js",
                "lineNumber": 123,
                "columnNumber": 19
            },
            "hitCount": 12,
            "children": [
                33
            ],
            "positionTicks": [
                {
                    "line": 124,
                    "ticks": 12
                }
            ]
        },
        {
            "id": 33,
            "callFrame": {
                "functionName": "createUnsafeArrayBuffer",
                "scriptId": "25",
                "url": "buffer.js",
                "lineNumber": -1,
                "columnNumber": -1
            },
            "hitCount": 4349,
            "children": [
                68,
                69,
                70,
                71,
                72,
                73,
                74
            ],
            "positionTicks": [
                {
                    "line": 124,
                    "ticks": 4349
                }
            ]
        },
        {
            "id": 68,
            "callFrame": {
                "functionName": "module.exports.Ir.c.pipeline",
                "scriptId": "1093",
                "url": "pii_removed/extension.bundle.js",
                "lineNumber": 262,
                "columnNumber": 1319686
            },
            "hitCount": 1,
            "positionTicks": [
                {
                    "line": 263,
                    "ticks": 1
                }
            ]
        },
        {
            "id": 69,
            "callFrame": {
                "functionName": "mapper",
                "scriptId": "1093",
                "url": "pii_removed/extension.bundle.js",
                "lineNumber": 262,
                "columnNumber": 79668
            },
            "hitCount": 1,
            "positionTicks": [
                {
                    "line": 263,
                    "ticks": 1
                }
            ]
        },
        {
            "id": 70,
            "callFrame": {
                "functionName": "",
                "scriptId": "1093",
                "url": "pii_removed/extension.bundle.js",
                "lineNumber": 0,
                "columnNumber": 23734
            },
            "hitCount": 1,
            "positionTicks": [
                {
                    "line": 1,
                    "ticks": 1
                }
            ]
        },
        {
            "id": 71,
            "callFrame": {
                "functionName": "e._isSuccess",
                "scriptId": "163",
                "url": "pii_removed/main.js",
                "lineNumber": 0,
                "columnNumber": 119951
            },
            "hitCount": 1,
            "positionTicks": [
                {
                    "line": 1,
                    "ticks": 1
                }
            ]
        },
        {
            "id": 72,
            "callFrame": {
                "functionName": "ignore.run.e",
                "scriptId": "163",
                "url": "pii_removed/main.js",
                "lineNumber": 0,
                "columnNumber": 107206
            },
            "hitCount": 1,
            "positionTicks": [
                {
                    "line": 1,
                    "ticks": 1
                }
            ]
        },
        {
            "id": 73,
            "callFrame": {
                "functionName": "scheduleRunWithHttpOperationResponse",
                "scriptId": "1093",
                "url": "pii_removed/extension.bundle.js",
                "lineNumber": 261,
                "columnNumber": 1105179
            },
            "hitCount": 1,
            "positionTicks": [
                {
                    "line": 262,
                    "ticks": 1
                }
            ]
        },
        {
            "id": 74,
            "callFrame": {
                "functionName": "lastWeek",
                "scriptId": "1093",
                "url": "pii_removed/extension.bundle.js",
                "lineNumber": 156,
                "columnNumber": 218811
            },
            "hitCount": 1,
            "positionTicks": [
                {
                    "line": 157,
                    "ticks": 1
                }
            ]
        },
        {
            "id": 41,
            "callFrame": {
                "functionName": "FastBuffer",
                "scriptId": "25",
                "url": "buffer.js",
                "lineNumber": -1,
                "columnNumber": -1
            },
            "hitCount": 493,
            "positionTicks": [
                {
                    "line": 593,
                    "ticks": 493
                }
            ]
        },
        {
            "id": 34,
            "callFrame": {
                "functionName": "writeShortString",
                "scriptId": "91",
                "url": "pii_removed/extensionHostProcess.js",
                "lineNumber": -1,
                "columnNumber": -1
            },
            "hitCount": 4,
            "children": [
                35
            ],
            "positionTicks": [
                {
                    "line": 596,
                    "ticks": 4
                }
            ]
        },
        {
            "id": 35,
            "callFrame": {
                "functionName": "write",
                "scriptId": "25",
                "url": "buffer.js",
                "lineNumber": 896,
                "columnNumber": 39
            },
            "hitCount": 437,
            "children": [
                42,
                53
            ],
            "positionTicks": [
                {
                    "line": 938,
                    "ticks": 399
                },
                {
                    "line": 909,
                    "ticks": 22
                },
                {
                    "line": 911,
                    "ticks": 16
                }
            ]
        },
        {
            "id": 42,
            "callFrame": {
                "functionName": "utf8Write",
                "scriptId": "0",
                "url": "",
                "lineNumber": -1,
                "columnNumber": -1
            },
            "hitCount": 1135,
            "positionTicks": [
                {
                    "line": 938,
                    "ticks": 1135
                }
            ]
        },
        {
            "id": 53,
            "callFrame": {
                "functionName": "isFinite",
                "scriptId": "0",
                "url": "",
                "lineNumber": -1,
                "columnNumber": -1
            },
            "hitCount": 15
        },
        {
            "id": 43,
            "callFrame": {
                "functionName": "writeLongString",
                "scriptId": "91",
                "url": "pii_removed/extensionHostProcess.js",
                "lineNumber": -1,
                "columnNumber": -1
            },
            "hitCount": 9,
            "children": [
                44
            ],
            "positionTicks": [
                {
                    "line": 596,
                    "ticks": 9
                }
            ]
        },
        {
            "id": 44,
            "callFrame": {
                "functionName": "write",
                "scriptId": "25",
                "url": "buffer.js",
                "lineNumber": 896,
                "columnNumber": 39
            },
            "hitCount": 1471,
            "children": [
                47,
                60
            ],
            "positionTicks": [
                {
                    "line": 938,
                    "ticks": 1436
                },
                {
                    "line": 909,
                    "ticks": 25
                },
                {
                    "line": 911,
                    "ticks": 10
                }
            ]
        },
        {
            "id": 47,
            "callFrame": {
                "functionName": "utf8Write",
                "scriptId": "0",
                "url": "",
                "lineNumber": -1,
                "columnNumber": -1
            },
            "hitCount": 505,
            "positionTicks": [
                {
                    "line": 938,
                    "ticks": 505
                }
            ]
        },
        {
            "id": 60,
            "callFrame": {
                "functionName": "isFinite",
                "scriptId": "0",
                "url": "",
                "lineNumber": -1,
                "columnNumber": -1
            },
            "hitCount": 10
        },
        {
            "id": 62,
            "callFrame": {
                "functionName": "writeUInt8",
                "scriptId": "91",
                "url": "pii_removed/extensionHostProcess.js",
                "lineNumber": 593,
                "columnNumber": 132
            },
            "hitCount": 13,
            "positionTicks": [
                {
                    "line": 594,
                    "ticks": 13
                }
            ]
        },
        {
            "id": 66,
            "callFrame": {
                "functionName": "createPool",
                "scriptId": "25",
                "url": "buffer.js",
                "lineNumber": 123,
                "columnNumber": 19
            },
            "hitCount": 7,
            "positionTicks": [
                {
                    "line": 124,
                    "ticks": 7
                }
            ]
        },
        {
            "id": 31,
            "callFrame": {
                "functionName": "u",
                "scriptId": "91",
                "url": "pii_removed/extensionHostProcess.js",
                "lineNumber": 586,
                "columnNumber": 397
            },
            "hitCount": 6443,
            "positionTicks": [
                {
                    "line": 587,
                    "ticks": 6443
                }
            ]
        },
        {
            "id": 61,
            "callFrame": {
                "functionName": "_arrayContainsBuffer",
                "scriptId": "91",
                "url": "pii_removed/extensionHostProcess.js",
                "lineNumber": 595,
                "columnNumber": 121
            },
            "hitCount": 30,
            "positionTicks": [
                {
                    "line": 596,
                    "ticks": 30
                }
            ]
        },
        {
            "id": 32,
            "callFrame": {
                "functionName": "r",
                "scriptId": "91",
                "url": "pii_removed/extensionHostProcess.js",
                "lineNumber": 446,
                "columnNumber": 837
            },
            "hitCount": 61,
            "positionTicks": [
                {
                    "line": 447,
                    "ticks": 61
                }
            ]
        },
        {
            "id": 37,
            "callFrame": {
                "functionName": "String",
                "scriptId": "0",
                "url": "",
                "lineNumber": -1,
                "columnNumber": -1
            },
            "hitCount": 1043
        },
        {
            "id": 39,
            "callFrame": {
                "functionName": "allocate",
                "scriptId": "25",
                "url": "buffer.js",
                "lineNumber": 316,
                "columnNumber": 17
            },
            "hitCount": 145,
            "children": [
                54
            ],
            "positionTicks": [
                {
                    "line": 329,
                    "ticks": 26
                },
                {
                    "line": 323,
                    "ticks": 16
                },
                {
                    "line": 317,
                    "ticks": 103
                }
            ]
        },
        {
            "id": 54,
            "callFrame": {
                "functionName": "FastBuffer",
                "scriptId": "25",
                "url": "buffer.js",
                "lineNumber": -1,
                "columnNumber": -1
            },
            "hitCount": 267,
            "positionTicks": [
                {
                    "line": 317,
                    "ticks": 267
                }
            ]
        },
        {
            "id": 45,
            "callFrame": {
                "functionName": "_writeSoon",
                "scriptId": "91",
                "url": "pii_removed/extensionHostProcess.js",
                "lineNumber": 168,
                "columnNumber": 597
            },
            "hitCount": 564,
            "positionTicks": [
                {
                    "line": 169,
                    "ticks": 564
                }
            ]
        },
        {
            "id": 46,
            "callFrame": {
                "functionName": "_onWillSendRequest",
                "scriptId": "91",
                "url": "pii_removed/extensionHostProcess.js",
                "lineNumber": 587,
                "columnNumber": 738
            },
            "hitCount": 110,
            "positionTicks": [
                {
                    "line": 588,
                    "ticks": 110
                }
            ]
        },
        {
            "id": 48,
            "callFrame": {
                "functionName": "e.isCancellationToken",
                "scriptId": "91",
                "url": "pii_removed/extensionHostProcess.js",
                "lineNumber": 44,
                "columnNumber": 938
            },
            "hitCount": 241,
            "positionTicks": [
                {
                    "line": 46,
                    "ticks": 241
                }
            ]
        },
        {
            "id": 50,
            "callFrame": {
                "functionName": "alloc",
                "scriptId": "91",
                "url": "pii_removed/extensionHostProcess.js",
                "lineNumber": 592,
                "columnNumber": 916
            },
            "hitCount": 164,
            "positionTicks": [
                {
                    "line": 593,
                    "ticks": 164
                }
            ]
        },
        {
            "id": 52,
            "callFrame": {
                "functionName": "writeUInt32BE",
                "scriptId": "26",
                "url": "internal/buffer.js",
                "lineNumber": 636,
                "columnNumber": 22
            },
            "hitCount": 88,
            "positionTicks": [
                {
                    "line": 637,
                    "ticks": 88
                }
            ]
        },
        {
            "id": 55,
            "callFrame": {
                "functionName": "writeUInt8",
                "scriptId": "91",
                "url": "pii_removed/extensionHostProcess.js",
                "lineNumber": 593,
                "columnNumber": 132
            },
            "hitCount": 103,
            "positionTicks": [
                {
                    "line": 594,
                    "ticks": 103
                }
            ]
        },
        {
            "id": 56,
            "callFrame": {
                "functionName": "byteLength",
                "scriptId": "25",
                "url": "buffer.js",
                "lineNumber": 507,
                "columnNumber": 19
            },
            "hitCount": 83,
            "positionTicks": [
                {
                    "line": 530,
                    "ticks": 83
                }
            ]
        },
        {
            "id": 57,
            "callFrame": {
                "functionName": "u",
                "scriptId": "91",
                "url": "pii_removed/extensionHostProcess.js",
                "lineNumber": 586,
                "columnNumber": 397
            },
            "hitCount": 76,
            "positionTicks": [
                {
                    "line": 587,
                    "ticks": 76
                }
            ]
        },
        {
            "id": 58,
            "callFrame": {
                "functionName": "assertSize",
                "scriptId": "25",
                "url": "buffer.js",
                "lineNumber": 257,
                "columnNumber": 19
            },
            "hitCount": 61,
            "positionTicks": [
                {
                    "line": 258,
                    "ticks": 61
                }
            ]
        },
        {
            "id": 59,
            "callFrame": {
                "functionName": "get",
                "scriptId": "91",
                "url": "pii_removed/extensionHostProcess.js",
                "lineNumber": 588,
                "columnNumber": 705
            },
            "hitCount": 177,
            "positionTicks": [
                {
                    "line": 589,
                    "ticks": 177
                }
            ]
        },
        {
            "id": 63,
            "callFrame": {
                "functionName": "_arrayContainsBuffer",
                "scriptId": "91",
                "url": "pii_removed/extensionHostProcess.js",
                "lineNumber": 595,
                "columnNumber": 121
            },
            "hitCount": 42,
            "positionTicks": [
                {
                    "line": 596,
                    "ticks": 42
                }
            ]
        },
        {
            "id": 64,
            "callFrame": {
                "functionName": "write",
                "scriptId": "25",
                "url": "buffer.js",
                "lineNumber": 896,
                "columnNumber": 39
            },
            "hitCount": 46,
            "positionTicks": [
                {
                    "line": 909,
                    "ticks": 46
                }
            ]
        },
        {
            "id": 40,
            "callFrame": {
                "functionName": "(program)",
                "scriptId": "0",
                "url": "",
                "lineNumber": -1,
                "columnNumber": -1
            },
            "hitCount": 401
        },
        {
            "id": 49,
            "callFrame": {
                "functionName": "(garbage collector)",
                "scriptId": "0",
                "url": "",
                "lineNumber": -1,
                "columnNumber": -1
            },
            "hitCount": 3548
        }
    ],
    "startTime": 110168589,
    "endTime": 115642783,
    "samples": [
        23,
        26,
        30,
        23,
        31,
        32,
        22,
        23,
        31,
        33,
        31,
        35,
        31,
        23,
        23,
        23,
        31,
        23,
        23,
        36,
        23,
        36,
        23,
        22,
        37,
        38,
        23,
        31,
        23,
        23,
        37,
        22,
        39,
        22,
        22,
......... (a few more thousand lines of this)
    ]
}`

**Comment by fbricon** [comment]
Please provide more informations about the circumstances of this issue. Can you share your yaml file?

**Comment by MikeCongdon1** [comment]
I'm getting something similar. I have 10 yml files open.

```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: "devel-nginx-dep"
  namespace: default
spec:
  replicas: 1
  revisionHistoryLimit: 2
  template:
    metadata:
      labels:
        name: "devel-nginx-dep"
    spec:
      containers:
        - image: nginx
          imagePullPolicy: IfNotPresent
          name: "devel-nginx-dep"
          ports:
            - containerPort: 80
              protocol: "TCP"
```
That's an example of one.. I'm really not doing anything too fancy here.
I do have Kubernetes & Swagger installed.

I uninstalled Kubernetes Extension and issue appears to be gone.
So, I think this has to do with the communication between Kubernetes Extension & YAML...
Hopefully this is helpful?

**Comment by JPinkney** [comment]
@MikeCongdon1 Thanks for the bug report!
>  communication between Kubernetes Extension & YAML

On every request (hover, completion, etc etc) the YAML extension asks "api contributors" (in this case the kubernetes extension) for any schemas that should be available for the particular file. It looks like something around this area could be causing the high cpu load but its just a guess

**Comment by MikeCongdon1** [comment]
> @MikeCongdon1 Thanks for the bug report!
> 
> > communication between Kubernetes Extension & YAML
> 
> On every request (hover, completion, etc etc) the YAML extension asks "api contributors" (in this case the kubernetes extension) for any schemas that should be available for the particular file. It looks like something around this area could be causing the high cpu load but its just a guess
Thanks!
I'd be happy to test that theory out by running it in a mode with that stuff off. (or at least minimized heavily). But, I don't know how to do that, or if such a flag exists in the YAML ext. So far my fix for now to disable the Kubernetes Extension & read the docs like a good kid instead of relying on code-completion.

**Comment by fredgrott** [comment]
here is my yaml 
[redhat.vscode-yaml-unresponsive.cpuprofile.txt](https://github.com/redhat-developer/vscode-yaml/files/6264200/redhat.vscode-yaml-unresponsive.cpuprofile.txt)
on the same issue

**Comment by joshua-small** [comment]
I do not have any files open (including YAML), but got this error: [redhat.vscode-yaml-unresponsive.cpuprofile.txt](https://github.com/redhat-developer/vscode-yaml/files/6735917/redhat.vscode-yaml-unresponsive.cpuprofile.txt)

**Comment by doncid** [comment]
I have the same issue and also no YAML file opened.
[redhat.vscode-yaml-unresponsive.cpuprofile.txt](https://github.com/redhat-developer/vscode-yaml/files/6908549/redhat.vscode-yaml-unresponsive.cpuprofile.txt)

**Comment by lhwdev** [comment]
Had the same issue without any YAML file opened:
[redhat.vscode-yaml-unresponsive.cpuprofile.txt](https://github.com/redhat-developer/vscode-yaml/files/6939756/redhat.vscode-yaml-unresponsive.cpuprofile.txt)

**Comment by lixin9311** [comment]
OS: `MacOS 11.6 x64`
Cloud Code Extension Version: `v1.16.0`
YAML extension Version: `v1.2.0`

Same here, vscode starts tons of python sub-processes on editing YAML files.
But it seems to have something to do with the Google Cloud Code extension.
![image](https://user-images.githubusercontent.com/371475/141725701-2771ceaa-3269-4757-b37a-8a03d10c75d8.png)

Cloud Code extension also validates YAML files against its own libraries.
After disabling the Cloud Code extension, CPU usage becomes normal again.
I won't bother digging in further, because Cloud Code is causing other troubles for me (incorrect K8S definition, and etc..).
