### ISSUE TITLE
Go to definition shortcut

### ISSUE THREAD

**Issue by rvansa** [redhat-developer/vscode-yaml#174]
I can't find a way (command, keybinding...) to jump to the schema file, onto element definition to see why the file does not match the template. Is there one?

**Comment by evidolob** [comment]
@JPinkney I think we can provide [CodeLens](https://code.visualstudio.com/api/language-extensions/programmatic-language-features#codelens-show-actionable-context-information-within-source-code)(something like "Open Schema") for each schema error, when some one click on it we open JSON Schema and navigate to part which causes error. WDYT?

**Comment by JPinkney** [comment]
I think this makes sense, I think I like the code action a bit more and the code action can be `Jump to schema location`. There are a few technical issues though. E.g. if a schema is coming from a url how can we jump to location? do we download it to a location then open it etc. Or only provide the code action for local schemas?

**Comment by evidolob** [comment]
I think we can download(and we already downloading it for validation) and open in readonly mode

**Comment by evidolob** [comment]
@JPinkney I made a prototype for this issue using CodeActions:

![ezgif com-gif-maker (8)](https://user-images.githubusercontent.com/929743/104737817-6d226100-574d-11eb-8963-1e863bcddc80.gif)
But I face some problems:

- To be able to open schema in vscode I need to use the latest version of LSP client/server 7.0.0 to use [showDocument](https://microsoft.github.io/language-server-protocol/specifications/specification-current/#window_showDocument)
- And file opening works only for local files, demo shows that k8s schema opened in a browser, so all schemas with `htttps` uri will be opened in a browser. I can handle that by providing custom URI schema and open schema in read only mode, but it would be werry VSCode specific.

**Comment by JPinkney** [comment]
I've never implemented a code action so I'm not exactly sure how they're implemented but what if the flow was something like:
```
If user is hovering over the error:
    If schema is local schema then:
        show code action and send showDocument request from server to client
    If schema is anything else (contributed using the api or its a schema from the browser) then
        return no code actions available
```

**Comment by evidolob** [comment]
I implement loading JSON Schema content from remote (https) in to vscode editor with custom document content provider:

![ezgif com-gif-maker (9)](https://user-images.githubusercontent.com/929743/104891322-74c64d80-5979-11eb-9ab8-512f934f2557.gif)

So yaml-ls trying open document, if uri for it starts with `https` it changed to `json-shema`, in vecode extension I add [textdocumentcontentprovider](https://code.visualstudio.com/api/extension-guides/virtual-documents#textdocumentcontentprovider) which can handle `json-shema` uri's and return content of schema.

I will create draft PR where we can discuss this.
