### ISSUE TITLE
No Github releases for vscode-yaml

### ISSUE THREAD

**Issue by ibuziuk** [redhat-developer/vscode-yaml#176]
According to `Installation from Github Release` section of docs it is expected to have github releases, similar to releases for `xml` extension - https://github.com/redhat-developer/vscode-xml/releases. Atm, there are no releases for vscode-yaml  available on GitHub

[1] https://github.com/redhat-developer/vscode-yaml#installation-from-github-release

**Comment by ibuziuk** [comment]
@fbricon @gorkem will it be possible to create the latest release of the extention in order to workaround che 7 GA VS Code marketplace rate limit error - https://github.com/eclipse/che/issues/12840

**Comment by fbricon** [comment]
I've created the 0.4.0 release : https://github.com/redhat-developer/vscode-yaml/releases/tag/0.4.0

I'll let @JPinkney push the proper tags for the previous ones, if he wants (prolly no need to go before 0.1.0). Just download https://marketplace.visualstudio.com/_apis/public/gallery/publishers/redhat/vsextensions/vscode-yaml/VERSION/vspackage and attach it manually to the release (until we automate the process).

**Comment by ibuziuk** [comment]
@JPinkney @fbricon thank you. Presently we do need version `0.3.0` since this one is used in the plugin registry atm - https://che-plugin-registry.openshift.io/plugins/

**Comment by ibuziuk** [comment]
@JPinkney will much appreciate if you could possibly add `0.3.0` vsix to the dedicated release

**Comment by fbricon** [comment]
@ibuziuk there: https://github.com/redhat-developer/vscode-yaml/releases/tag/0.3.0
