### ISSUE TITLE
Overlapping functionality with the VSCode Ansible extension

### ISSUE THREAD

**Issue by paidhi** [redhat-developer/vscode-yaml#178]
The functionality of this extension seems to overlap with the _Ansible_ extension (`vscoss.vscode-ansible`). Both extensions populate the Outline view as well as _Go to symbol_. So all elements are displayed twice.
This is not really a bug but keeps irritating me when working with Ansible and YAML files.

To reproduce:
Install both this extension and `vscoss.vscode-ansible`. Open a YAML file and see duplicate entries in the Outline view and _Go to symbol_.

I have reported this in parallel here: https://github.com/VSChina/vscode-ansible/issues/230

**Comment by gorkem** [comment]
This is because `vscode-ansible` has a copy of this extension (the language server to be precise). There is not much we can do here.

**Comment by gorkem** [comment]
@ssbarnea Can we close this now ?

**Comment by ssbarnea** [comment]
Yes, that is outdated several generations. Now there is only one Ansible extension at https://marketplace.visualstudio.com/items?itemName=redhat.ansible
