### ISSUE TITLE
is there a way to register optional default schemas?

### ISSUE THREAD

**Issue by jstrachan** [redhat-developer/vscode-yaml#180]
we've got a JSON schema file for editing files called `jenkins-x*.yml` for use with VS Code and this extension: https://jenkins-x.io/architecture/jenkins-x-pipelines/#editing-in-vs-code

is there a way we could automate adding this schema into the vscode-yaml extension to avoid users not having to tinker with their `settings.json` file? e.g. adding this default...

```json
    "yaml.schemas": {
        "https://jenkins-x.io/schemas/jx-schema.json": "jenkins-x*.yml"
    },
```
if so am more than happy to generate a PR - I've just no clue how to do that ;) Many thanks!

**Comment by JPinkney** [comment]
You should be able to add your schema to the [schema store](https://github.com/SchemaStore/schemastore) api with something like:  

```
{
      "name": "Jenkins-X",
      "description": "Jenkins-X file",
      "fileMatch": [ "jenkins-x*.yml" ],
      "url": "https://jenkins-x.io/schemas/jx-schema.json"
}
```

and then as long as a user has the ```yaml.schemaStore.enable``` setting to true (it's true by default) it should automatically associate the schema to the file!

**Comment by jstrachan** [comment]
@JPinkney many thanks! Creating a PR there now

**Comment by jstrachan** [comment]
I've raised this PR https://github.com/SchemaStore/schemastore/pull/683 many thanks
