### ISSUE TITLE
 Include support for JSON Schema in YAML format

### ISSUE THREAD

**Issue by robbie01** [redhat-developer/vscode-yaml#182]
JSON is already unnecessarily verbose, and JSON Schema definitions don't make it any better. I would like to see support for JSON Schema validation against definitions in YAML format instead of JSON, so we can forget about the format entirely.

**Comment by gorkem** [comment]
Closing as this is already implemented with https://github.com/redhat-developer/yaml-language-server/commit/4a2f1d8943a6b73b4a19d4bc801e364250665c4b
