### ISSUE TITLE
Glob parsing incorrect for folders with wildcards 

### ISSUE THREAD

**Issue by teq0** [redhat-developer/vscode-yaml#184]
If I have a folder structure like 
```
+-- /dogs
  +-- /spike
      -- spike.yaml
      +-- /toys
         -- ball.yaml
```
and settings like 
```json
{
  "yaml.schemas": {
      "../schemas/pets/dog.schema.json": "dogs/*/*.yaml",
      "../schemas/pets/toy.schema.json": "dogs/*/toys/*.yaml",
   }
 }
```

the first `*` in `"dogs/*/*.yaml"` is causing it to recurse so that `dog.schema.json` is being applied to the `toys` subfolder. Correct glob syntax for that would actually be `"dogs/**/*.yaml"`

Not sure but from looking at the code this might be a VS Code thing?

**Comment by teq0** [comment]
Actually that's not exactly it, although that does happen. It seems like it's applying any pattern recursively, so 
```
{
  "yaml.schemas": {
      "../schemas/pets/dog.schema.json": "dogs/*.yaml",
      "../schemas/pets/toy.schema.json": "dogs/*/toys/*.yaml",
   }
 }
```

would still apply `dogs.schema.json` to the contents of the `toys` folder.

**Comment by tomaxsas** [comment]
had this issue also
``` json
    "yaml.schemas": {
        "https://json.schemastore.org/ansible-playbook": [
            "**/ansible/*.yml"
        ],
        "https://json.schemastore.org/ansible-role-2.9": [
            "**/ansible/roles/**/*.yml"
        ]
    }
```
ansible-playbook schema would apply for roles, very annoying.

**Comment by ssbarnea** [comment]
Closing as patterns are working as expected but you might want to check https://github.com/redhat-developer/vscode-yaml/issues/660
