### ISSUE TITLE
"Unknown tag" error when validating sets

### ISSUE THREAD

**Issue by bfelbo** [redhat-developer/vscode-yaml#191]
This works just fine as YAML:
```
1:
  not_allowed_match_user_ids: !!set {}
2:
  not_allowed_match_user_ids: !!set {}
```

However, this extension redlines it and gives the following errors:
```
unknown tag <tag:yaml.org,2002:set>
unknown tag <tag:yaml.org,2002:set>
```

According to https://github.com/adamvoss/vscode-yaml/issues/16, it's possible to add these tags to your own settings, but I can't find the right name to add them with.

**Comment by bfelbo** [comment]
I can add this to settings.json to resolve the error:
```
    "yaml.customTags": [
        "tag:yaml.org,2002:set"
    ]
```

However, then I get the following errors:
```
bad indentation of a mapping entry
unacceptable node kind for !<tag:yaml.org,2002:set> tag; it should be "scalar", not "mapping"
end of the stream or a document separator is expected
```

Is there anything I can add to settings.json to fix this?

**Comment by bfelbo** [comment]
Alternatively, is it possible to make this plugin ignore certain (custom) types altogether?

**Comment by LucasIcarus** [comment]
any updates? 

```yaml
key: !!bool true
```

will cause similar error.

```bash
unknown tag <tag:yaml.org,2002:bool>
```

**Comment by gorkem** [comment]
The new parser recognizes YAML 1.2 core schema of which all these tags are part. Closing as I can see them working now.
