### ISSUE TITLE
Array item properties are created with the wrong indent

### ISSUE THREAD

**Issue by itowlson** [redhat-developer/vscode-yaml#192]
I have a JSON schema which contains an array property.  The array item type is an object with properties.  The desired layout is like this:

```
install:
  - helm:
      name: foo
  - helm:
      name: bar
```

When I add the array using tab-completion, RH YAML correctly inserts a starting array 
element with the correct indentation:

```
in<HIT TAB TO AUTOCOMPLETE>

=>

install:
  - helm:
      name: <CURSOR POSITIONED HERE>  # This is correct
```

But when I add a second array element by tab-completing the name, it does not indent the sub-properties:

```
install:
  - helm:
      name: foo
  - he<HIT TAB TO AUTOCOMPLETE>

=>

install:
  - helm:
      name: foo
  - helm:
    name: <CURSOR HERE>   # Note name is *NOT* indented from its parent
```

Furthermore, our real scenario is that the array can contain multiple different kinds of item (which is why we have the `helm` parent name rather than just an array of tuples).  So our JSON schema specifies `"items": { "anyOf": [ { "$ref": "...helm..." }, { "$ref": "...exec..." }, ... ] }`.  In this case, even with only a single option in the "anyOf", no element is auto inserted (correctly, as RH YAML could not know which of the anyOf options to take), and the user must explicitly insert the first array element, which is then indented incorrectly

```
# With the anyOf variant of the JSON Schema

in<HIT TAB FOR AUTOCOMPLETION>

=> 

install:
  - <CURSOR HERE>  # This is okay

=>

install:
  - he<HIT TAB FOR AUTOCOMPLETION>

=>

install:
  - helm:
    name: <CURSOR HERE>  # Incorrect indentation
```

Here is the simplified JSON Schema which I used to reproduce the issue:

```json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "definitions": {
    "installStep": {
      "properties": {
        "helm": {
          "additionalProperties": false,
          "properties": {
            "name": {
              "type": "string"
            }
          },
          "required": [
            "name"
          ],
          "type": "object"
        }
      },
      "required": [
        "helm"
      ],
      "type": "object"
    }
  },
  "properties": {
    "install": {
      "items": {
        "anyOf": [
          {
            "$ref": "#/definitions/installStep"
          }
        ]
      },
      "type": "array"
    }
  },
  "type": "object"
}
```

Note that this is the ‘anyOf’ schema to show the second part of the issue (which is our real environment).  To reproduce the first part of the issue, remove the `anyOf` from around the `$ref` in the `items` schema (or I can send you that schema too).

Please let me know if you need any more information.

**Comment by JohannLai** [comment]
I had the same problem.

**Comment by squillace** [comment]
@JPinkney should we submit a PR?

**Comment by JPinkney** [comment]
@squillace Yes preferably

**Comment by andxu** [comment]
hi @itowlson , I have a different result using the latest vscode and RH-yaml on marketplace, did I misunderstand something?
 
![test](https://user-images.githubusercontent.com/17075863/61691323-e4945180-ad5d-11e9-8ee5-941aee9a9cfa.gif)

**Comment by itowlson** [comment]
@andxu You're definitely getting the output we want.  Could you post your schema or a screenshot of your schema please?  It's disappearing too quickly for me to read it off the GIF - sorry.

**Comment by andxu** [comment]
```json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "definitions": {
    "installStep": {
      "properties": {
        "helm": {
          "additionalProperties": false,
          "properties": {
            "name": {
              "type": "string"
            }
          },
          "required": [
            "name"
          ],
          "type": "object"
        }
      },
      "required": [
        "helm"
      ],
      "type": "object"
    }
  },
  "properties": {
    "install": {
      "items": {
        "anyOf": [
          {
            "$ref": "#/definitions/installStep"
          }
        ]
      },
      "type": "array"
    }
  },
  "type": "object"
}
```

**Comment by squillace** [comment]
Thanks so much for following up on this @andxu. @itowlson?

**Comment by itowlson** [comment]
@andxu That looks right for the repro.  Let me check I'm up to date with everything and try again.  Thanks!

**Comment by itowlson** [comment]
@andxu I'm on VS Code 1.36.1 and YAML 0.4.1.  Those both look up to date to me.  And I pasted your schema into my schema content callback.  But I'm still seeing the problem.  I wonder what's different between our two environments?

@JohannLai I saw you thumbs-upped Andy's schema - is that working for you, or still giving the same problem?

**Comment by itowlson** [comment]
@andxu I noticed your entries are indented by 4 whereas mine are indented by 2.  I am clutching at straws here, but are you using tabs or spaces?  Where is your indent configured?

**Comment by itowlson** [comment]
@andxu If I switch to tabs I get the desired behaviour as shown in your GIF (except for a wiggly saying 'tabs can lead to unpredictable results').  Could you try switching to spaces and see if that reproduces the error for you please?

**Comment by itowlson** [comment]
@andxu The plot thickens.  It's not tabs vs. spaces.  It's indent size 2 vs. indent size 4.  I have indent size 2, and get the misalignment.  If I change it to 4, everything works.  (And if I use tabs, but with a size of 2, it goes wrong again.)

**Comment by JohannLai** [comment]
I'm not sure it works. I think it's worth a try. I'll try it later.

**Comment by itowlson** [comment]
@andxu @squillace got confused about which indent I was referring to because apparently the YAML extension has tab conversion stuff of its own, so for avoidance of doubt it is this one - works when set to 4, shows the bug when set to 2.  No YAML-extension-specific settings in play.

![image](https://user-images.githubusercontent.com/865538/61765844-d2381780-ae32-11e9-8078-b3219ca6b29a.png)

**Comment by squillace** [comment]
@andxu I repro @itowlson's explanation. I have a default of 2 spaces on my VS Code, and I get the following when using with `Spaces: 2`. This is incorrect autocomplete.

![image](https://user-images.githubusercontent.com/1422718/61766320-4de38700-ad95-11e9-8dd0-bf100928b76d.png)

if I then switch to `Spaces: 4` I get the following, which is what you get. 

![image](https://user-images.githubusercontent.com/1422718/61766362-7bc8cb80-ad95-11e9-9324-48cdd757a165.png)

**Comment by andxu** [comment]
Looks funny, I will test it on different indents to figure out the root cause.

**Comment by squillace** [comment]
:-) Thanks, @andxu, thanks so much for tolerated us. :-) Let us know what you find!

**Comment by andxu** [comment]
When this plugin provides completion text for the sample yaml below, the snippet vscode-yaml provides is `"helm:\n\tname: $1"`  with `insertTextFormat`(in the case of error indents: 2),  which will result in the final code change of `"text": "install:\n■■-■helm:\n■■■■name:■"`(I replaced spaces with '■'), if I change the indents to 4,  the same snippet will result in "install:\n■■-■helm:\n■■■■■■name:■", seems the code [here](https://github.com/redhat-developer/yaml-language-server/blob/71567fc785645e3e405899c8e442461dd9793ecd/src/languageservice/services/yamlCompletion.ts#L618) makes the snippet code, I will continue to research more on vscode's behavior on applying code snippet.

```
install:
  - he<HIT TAB TO AUTOCOMPLETE>
``

```json
[Trace - 4:38:51 PM] Received response 'textDocument/completion - (43)' in 2ms.
Result: {
    "items": [
        {
            "kind": 10,
            "label": "helm",
            "insertText": "helm:\n\tname: $1",
            "insertTextFormat": 2,
            "documentation": "",
            "textEdit": {
                "range": {
                    "start": {
                        "line": 1,
                        "character": 4
                    },
                    "end": {
                        "line": 1,
                        "character": 6
                    }
                },
                "newText": "helm:\n\tname: $1"
            }
        }
    ],
    "isIncomplete": false
}


[Trace - 4:38:51 PM] Sending request 'completionItem/resolve - (44)'.
Params: {
    "label": "helm",
    "insertTextFormat": 2,
    "textEdit": {
        "newText": "helm:\n\tname: $1",
        "range": {
            "start": {
                "line": 1,
                "character": 4
            },
            "end": {
                "line": 1,
                "character": 6
            }
        }
    },
    "kind": 10
}


[Trace - 4:38:51 PM] Received response 'completionItem/resolve - (44)' in 0ms.
Result: {
    "label": "helm",
    "insertTextFormat": 2,
    "textEdit": {
        "newText": "helm:\n\tname: $1",
        "range": {
            "start": {
                "line": 1,
                "character": 4
            },
            "end": {
                "line": 1,
                "character": 6
            }
        }
    },
    "kind": 10
}


[Trace - 4:38:51 PM] Sending notification 'textDocument/didChange'.
Params: {
    "textDocument": {
        "uri": "file:///c%3A/azure-webapp/helloworld/test.yaml",
        "version": 34
    },
    "contentChanges": [
        {
            "text": "install:\n  - helm:\n    name: "
        }
    ]
}
```

**Comment by itowlson** [comment]
@andxu Thanks for the update. I wonder if it’s also worth looking at what is different about the case where the array item type is specific instead of an anyOf - per the initial bug report, this caused the FIRST array element to indent correctly even with an indent if 2... but still got it wrong on subsequent elements...

**Comment by andxu** [comment]
The indent settings in vscode will cause the spaces(if you don't use 'space' other than 'tab') added at the 
baseline of the first '-' in `-helm`, so  it gives the following result:
```yaml
# indent 1
install:
- helm:
^name: 
```
```yaml
# indent 2
install:
- helm:
^^name: 
```

```yaml
# indent 3
install:
- helm:
^^^name: 
```

```yaml
# indent 4
install:
- helm:
^^^^name: 
```

**Comment by andxu** [comment]
So I think it is a bug in yaml language server generating the snippet at the wrong indent on array objects.

**Comment by andxu** [comment]
I will post a PR before 08/05.

**Comment by itowlson** [comment]
Thanks for the fix @andxu (and for the review @JPinkney)!

**Comment by andxu** [comment]
once the yaml LS is published at npm, I will update the vscode-yaml here.

**Comment by andxu** [comment]
thank @JPinkney for publish a new version.
