### ISSUE TITLE
.gitlab-ci.yml environment error

### ISSUE THREAD

**Issue by ajouve** [redhat-developer/vscode-yaml#193]
Hi,

I have the flowing error in my `.gitlab-ci.yml`

```
Used to associate environment metadata with a deploy. Environment can have a name and URL attached to it, and will be displayed under /environments under the project.
```

For

```
deploy:
  environment: staging
```

Is there any way to fix ti ?

**Comment by JPinkney** [comment]
> Used to associate environment metadata with a deploy. Environment can have a name and URL attached to it, and will be displayed under /environments under the project.

That isn't an error, that is the hover message. If you look in the problems panel it says "Incorrect type: 
expected object".

According to what I found in the [docs](https://docs.gitlab.com/ee/ci/environments.html) environment expects an object not a string so it should be something like
```yaml
deploy:
  environment:
    name: staging
```

**Comment by JPinkney** [comment]
@ajouve Out of curiosity was this able to fix your issue? If yes, I'll close the issue

**Comment by ajouve** [comment]
Yes fixed thanks
