### ISSUE TITLE
Schema validation doesn't work on files named `values.yaml`

### ISSUE THREAD

**Issue by Stono** [redhat-developer/vscode-yaml#196]
This is baffling me, if i name my file _anything_ other than `values.yaml`, it works fine, for example `bacon.yaml`.

```
    "yaml.schemas": {
        "https://github.atcloud.io/raw/AutoTrader/platform-helm-at-service/master/schema/compiled.json": "/bacon.yaml"
    }
```

The second i use `values.yaml`, autocomplete doesn't work at all.

**Comment by JPinkney** [comment]
I've just tested on my machine and doing something like 
```
"yaml.schemas": {
        "http://json.schemastore.org/composer": "/values.yaml"
}
```

works for me and there is [no conflicting schema store files](https://github.com/SchemaStore/schemastore/blob/master/src/api/json/catalog.json) with values.yaml . Out of curiosity can you try values.yml?

**Comment by Stono** [comment]
Hey thanks for the prompt replies this evening @JPinkney.

`values.yml` works just fine

**Comment by Stono** [comment]
So I've got:
```
    "yaml.schemas": {
        "../platform-helm-at-service/schema/index.json": "/*.yaml"
    }
```

And two files, `bacon.yaml` and `values.yaml`.

`bacon` works just fine, `values` does not.  I'm wondering if it's a conflicting plugin (I have helm+kubernetes installed too and they use the same yaml lang server)

**Comment by Stono** [comment]
Nope, removed the kubernetes plugin and still ney joy.

**Comment by Stono** [comment]
<img width="608" alt="Screenshot 2019-07-10 at 19 07 25" src="https://user-images.githubusercontent.com/1486729/60993269-021cf080-a346-11e9-9920-a319ca0fc4f3.png">
<img width="473" alt="Screenshot 2019-07-10 at 19 07 32" src="https://user-images.githubusercontent.com/1486729/60993271-02b58700-a346-11e9-9c08-fcb6c6f23e95.png">

**Comment by JPinkney** [comment]
OH I think I know why. For some reason your values.yaml file does not look like its set to the YAML language type. If you do ctrl+p and then Change Language Mode and then YAML I believe it should work (the only reason I know is because your values.yaml icon is not the one VSCode uses for YAML). I have no idea why it wasn't set correctly when you originally created the yaml file though. Looks like a weird vscode bug

**Comment by Stono** [comment]
That sorted it!
How bloody odd, thank you!

**Comment by tvvignesh** [comment]
I am seeing this too. Interesting to see this behavior. Not sure which plugin is causing it.

**Comment by OmriHarary** [comment]
@tvvignesh Not sure if it's the case for you, but for anyone else who might come across this: The Kubernetes extension (`ms-kubernetes-tools.vscode-kubernetes-tools`) which also provides Helm support sets the language mode for all files in a Helm chart to `helm-template`, including values.yaml.

It would be nice if the two extensions worked together nicer.

**Comment by gorkem** [comment]
@lstocchi @itowlson Any ideas?

**Comment by lstocchi** [comment]
@gorkem The kubernetes extension is surely responsible for this issue as @OmriHarary described.
if you go inside the package.json you can find out why the language is set to helm 
```
"languages": [
            {
                "id": "helm",
                "aliases": [
                    "helm-template",
                    "helm"
                ],
                "filenamePatterns": [
                    "values.yaml",
                    "Chart.yaml",
                    ......
``` 
i'm not really sure why values.yaml is handled like this. It is a special file for helm https://helm.sh/docs/chart_template_guide/values_files/ but it is also a plain yaml file so i guess we can change that rule. 
I'll investigate more on this.

**Comment by tvvignesh** [comment]
@OmriHarary Yup. I do use the Kubernetes extension. Interesting..

**Comment by JPinkney** [comment]
Yeah I think there's not really anything on our side that we can do if they just hijack the files with name values.yaml and change the type to helm

**Comment by gorkem** [comment]
@lstocchi perhaps the extension is trying to push the optional schema that may come with the helm chart.
