### ISSUE TITLE
yaml.schemas seem to be cached and don't auto update

### ISSUE THREAD

**Issue by Stono** [redhat-developer/vscode-yaml#197]
Any tips on how to clear the cache?  I can't even append a `#some-number` to the url, because the nested resolved schemas are cache.

**Comment by JPinkney** [comment]
Other then refreshing vscode (which I think _should_ work) there isn't a built in way to do it that I can think of.

**Comment by Stono** [comment]
Possible dupe of https://github.com/redhat-developer/vscode-yaml/issues/128

**Comment by Stono** [comment]
Actually it was being updated, however the behaviour of "default" made me think it wasn't working.

See: https://github.com/redhat-developer/vscode-yaml/issues/198
