### ISSUE TITLE
publish to the LSP plugin registry thingy so that its easy to install/upgrade via VS Code directly

### ISSUE THREAD

**Issue by jstrachan** [redhat-developer/vscode-yaml#21]
lets make a real release so its super easy for folks to find this excellent plugin and install/upgrade from VS Code

**Comment by gorkem** [comment]
That is the plan. Only a few more things to rake care of.

**Comment by schickling** [comment]
Any progress on this?

**Comment by gorkem** [comment]
Should happen this week. Still missing an icon :)

**Comment by JPinkney** [comment]
@schickling We are now officially published! https://marketplace.visualstudio.com/items?itemName=redhat.vscode-yaml
