### ISSUE TITLE
Unable to load schema from 'kubernetes://schema/monitoring.coreos.com/v1@prometheusrule': No content.

### ISSUE THREAD

**Issue by branttaylor** [redhat-developer/vscode-yaml#210]
Issue Type: <b>Bug</b>

Opened a .yaml file and I'm getting this error at the top of the file, and the file path is red:

Unable to load schema from 'kubernetes://schema/monitoring.coreos.com/v1@prometheusrule': No content.

Extension version: 0.4.1
VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:56:38.504Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2900)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (2.14GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by JPinkney** [comment]
By any chance did you set anything in yaml.schemas? Or are you using the kubernetes extension?

**Comment by branttaylor** [comment]
@JPinkney I'm using the Kubernetes extension. I wasn't sure how it interacted with this extension, but I noticed that the Kubernetes extension depended on this one. I've now disabled the Kubernetes extension but enabled the YAML one, and I'm not seeing the error. Safe to say that I should move this issue over to them instead?

**Comment by JPinkney** [comment]
It looks like its an issue with the Kubernetes extension rather than this one

**Comment by branttaylor** [comment]
Agreed. Thanks @JPinkney for your quick response!
