### ISSUE TITLE
Incorrect type. Expected "string" when install this.

### ISSUE THREAD

**Issue by at-bachhuynh** [redhat-developer/vscode-yaml#213]
My CircleCI file always announce this error when enable this extensions.
![image](https://user-images.githubusercontent.com/16200158/62938654-a25cae00-bdf9-11e9-8ca4-18784bbf151e.png)

Everything will be OK when disable the extensions.
![image](https://user-images.githubusercontent.com/16200158/62938607-8953fd00-bdf9-11e9-94aa-2915f00bdc8f.png)

Is there any way to fix it?

**Comment by JPinkney** [comment]
I'm guessing the upstream schemas that we use from the [json schema store](https://github.com/SchemaStore/schemastore) says that anything under references should be a string and thats why you are getting an error.

If this assumption is incorrect (I don't have much knowledge of circleci) then file an issue on that repository and it will be changed.

For now, you can disable the schema store by setting yaml.schemaStore.enable to be false.

**Comment by at-bachhuynh** [comment]
Thank @JPinkney, It works when disable yaml.schemeStore!

**Comment by JPinkney** [comment]
I'm going to close this issue as its a problem with the schema located on the json schema store
