### ISSUE TITLE
Unordered sets are not recognized 

### ISSUE THREAD

**Issue by yves-chevallier** [redhat-developer/vscode-yaml#225]
YAML files such as: 

```yaml
--- 
set:
  ? foo
  ? bar
  ? baz
```

are not properly highlighted. 

The following is also not recognized (from Example 2.25 of the specifications):

```yaml
# Sets are represented as a
# Mapping where each key is
# associated with a null value
--- !!set
? Mark McGwire
? Sammy Sosa
? Ken Griff
```

**Comment by gorkem** [comment]
Closing as we are able to support sets with the new parser already.
