### ISSUE TITLE
Auto-completion doesn't work properly

### ISSUE THREAD

**Issue by adoux** [redhat-developer/vscode-yaml#226]
Hi everyone.

The auto-completion doesn't work properly for YAML files except after the first install of the extension or when I disable/enable the extension.
But as soon as I restart vscode once, the auto-completion feature doesn't work anymore.

- After disable/enable of the extension, and before restarting vscode :

![image](https://user-images.githubusercontent.com/54279741/64626208-c0fc9780-d3ed-11e9-8867-a98345578d2d.png)

- After restarting vscode :

![image](https://user-images.githubusercontent.com/54279741/64626326-f608ea00-d3ed-11e9-9c55-129afe65f51c.png)

I have disabled all other plugins, left the YAML settings with default values, but still the same behavior.

- Running VSCode :
    - Version: 1.38.0 (system setup)
    - Commit: 3db7e09f3b61f915d03bbfa58e258d6eee843f35
    - Date: 2019-09-03T21:49:13.459Z
    - Electron: 4.2.10
    - Chrome: 69.0.3497.128
    - Node.js: 10.11.0
    - V8: 6.9.427.31-electron.0
    - OS: Windows_NT x64 10.0.18362
- And YAML (Red Hat) 0.5.2

settings.json :

```
{
    "workbench.colorTheme": "Default Light+",
    "[yaml]": {},
    "editor.tabSize": 2,
    "python.jediEnabled": false,
    "yaml.trace.server": "verbose",
}
```

Thanks in advance for your help.

**Comment by JPinkney** [comment]
I've just tested on my machine and I cannot reproduce the issue. Do you have a proxy? Can you show me what's in the output channel by doing view -> output -> then selecting `YAML Support` in the dropdown.

**Comment by adoux** [comment]
I don't have any proxy, direct connection only, and here is the output when I try to use completion with ctrl+space :

```
[Trace - 17:50:03] Sending request 'textDocument/completion - (8)'.
Params: {
    "textDocument": {
        "uri": "file:///c%3A/[...]/test_scripts.jps"
    },
    "position": {
        "line": 12,
        "character": 2
    },
    "context": {
        "triggerKind": 1
    }
}


[Trace - 17:50:03] Received request 'custom/schema/request - (10)'.
Params: "file:///c%3A/[...]/test_scripts.jps"


[Trace - 17:50:03] Sending response 'custom/schema/request - (10)'. Processing request took 0ms
No result returned.


[Trace - 17:50:03] Received response 'textDocument/completion - (8)' in 1ms.
Result: {
    "items": [],
    "isIncomplete": false
}
```

**Comment by JPinkney** [comment]
The "items" in `textDocument/completion` shouldn't be empty when autocompletion is working because addNodesToHAProxy, address, ipAddresses, etc are all values directly from that field. What's the name of the file you're working on? (Schemas from schema store are matched with the name of the file to know which files they should auto associate with, so maybe its that)

**Comment by JPinkney** [comment]
What do the KO stand for? Do you mean it works okay or does it mean something else?

`to add association between .jps files and YAML language` needs to be done otherwise it guaranteed won't work

**Comment by fbricon** [comment]
KO means not OK (expression used in France)

**Comment by adoux** [comment]
I've just tried to completely uninstall vscode and delete every folder linked to it, so going with a fresh new instance, and the problem is still here.

I have to point out that the extension's other features are working well even after a vscode restart, validation, symbols research, etc.

**Comment by adoux** [comment]
I couldn't tell why, but I can't reproduce the issue, maybe thanks to the last updates of vscode or YAML plugin.

Thanks a lot anyway for your help !

**Comment by JPinkney** [comment]
No worries! I'm glad to help!
