### ISSUE TITLE
Autocomplete for multiple yaml objects fails

### ISSUE THREAD

**Issue by dfgrosso** [redhat-developer/vscode-yaml#230]
Issue Type: <b>Bug</b>

Greetings,

Since I've updated to version 0.5 I no longer have autocomplete in yaml files with multiple ojects (ex: Service + Deployment)

Extension version: 0.4.1
VS Code version: Code 1.38.1 (b37e54c98e1a74ba89e03073e5a3761284e3ffb0, 2019-09-11T13:35:15.005Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.80GB (4.67GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by JPinkney** [comment]
Can you please provide the schema, the yaml you were trying to auto complete, and any other vscode extensions you are running

**Comment by dfgrosso** [comment]
Hello.

Sure. 
My extensions:
![Anotação 2019-09-17 145956](https://user-images.githubusercontent.com/23335507/65048336-d75da280-d95b-11e9-961f-0def394b9603.png)

My yaml:

[backoffice-redis.zip](https://github.com/redhat-developer/vscode-yaml/files/3621708/backoffice-redis.zip)

**Comment by JPinkney** [comment]
Which version of the 0.5 series were you updating to? 0.5.0, 0.5.1, all had https://github.com/redhat-developer/vscode-yaml/issues/216 issue where autocompletion wasn't working.

It is most likely an issue with the kubernetes extension regardless though, as they contribute the schema to this extension

**Comment by dfgrosso** [comment]
Hi.

I've tried all the 0.5 minors up to 0.5.3

Thank u.

Regards,
Daniel

**Comment by JPinkney** [comment]
Then you'll probably want to file an issue https://github.com/Azure/vscode-kubernetes-tools because it seems like an issue with the schema

**Comment by JPinkney** [comment]
I believe this issue has been resolved and everything should be working now
