### ISSUE TITLE
Schemas using file refs do not live update when definition is changed

### ISSUE THREAD

**Issue by vrachels** [redhat-developer/vscode-yaml#231]
using a schema with "$ref" and file references can result in filewatcher updates not properly updating the schema verification if the ref in a file is updated.

tl;dr: File Ref definitions are being locally cached in each schema, and are not being updated when the dependency is updated.

Minimal repro:
yaml.schemas adds test.json
test.json has a "definitions" { ... } section which contains the local $ref'd definition.
The local definition points to some other schema file(s) via file ref, ie A.json
A.json is defined similarly, and points to another schema file(s) B.json that is defined similarly.

<details><summary>Example Files</summary><p>

<details><summary>test.json</summary><p>

```json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$id": "test.json",
    "definitions": {
        "Core": {
           "anyOf": [
                {
                    "$ref": "A.json#/definitions/A"
                }
            ]
        }
    },
    "$ref": "#/definitions/Core"
}
```
</p></details>
<details><summary>A.json</summary><p>

```json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$id": "A.json",
    "definitions": {
        "A": {
            "type": "array",
            "items": {
                "$ref": "B.json#/definitions/B1"
             },
             "minItems": 1
        }
    },
    "$ref": "#/definitions/A"
}
```
</p></details>
<details><summary>B.json</summary><p>

```json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$id": "B.json",
    "definitions": {
        "B1": {
            "type": "string",
            "pattern": "^[a-z]+$"
        },
        "B2": {
            "type": "string",
            "pattern": "^[A-Z]+$"
        }
    },
    "$ref": "#/definitions/B1"
}
```
</p></details>
<details><summary>test2.json</summary><p>

```json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$id": "test2.json",
    "definitions": {
        "Core": {
            "anyOf": [
                {
                    "type": "array",
                    "items": {
                        "$ref": "B.json#/definitions/B1"
                    },
                    "minItems": 2
                }
            ]
        }
    },
    "$ref": "#/definitions/Core"
}
```
</p></details>
<details><summary>TestData.yaml</summary><p>

```yaml
- lowercase
- UPPERCASE
- Capitalized
- camelCase
- CapitalizedCamelCase
```
</p></details>
</p></details>

#### Test cases for 3 layers (schema -> A -> B):
* Change A.json definitions.A.items.$ref : B1 -> B2  
** verbose output shows update, with same error, still testing against B1 pattern
** Close vscode, reopen.  Note correct validation.
** Reset files, restart before continuing test.
* Change B.json definitions.B1.pattern :  "^[a-z]+$" -> "^[A-Z][a-z]*$"
** verbose output shows update, with same error, still testing against previous B1 pattern
** Close vscode, reopen.  Note correct validation.
** Reset files, restart before continuing test.
* Change A.json definitions.A.minItems : 1 -> 10
** verbose output shows update, with same error, still testing against previous A minItems
** Close vscode, reopen.  Note correct validation.
** Reset files, restart before continuing test.

#### Followup test:
* Change B.json definitions.B1.pattern :  "^[a-z]+$" -> "^[A-Z][a-z]*$"
* Force an update of A.json.
** Note no change in validation
* Force an update of test.json
** Note updated validation

#### Test cases for 2 layers (schema -> B)
Change yaml.schemas from test.json to test2.json.

* Change B.json definitions.B1.pattern :  "^[a-z]+$" -> "^[A-Z][a-z]*$"
** verbose output shows update, with same error, still testing against previous B1 pattern
** No reset yet, for followup test:
* Change test2.json to force an update.  ie: definitions.Core.anyOf[0].minItems : 1 -> 2
** Note that updated B1 pattern is now being tested

**Comment by ssbarnea** [comment]
Closing as I do not think this is really actionable. It should be noted that "Reload Window" can be used as a workaround for this limitation.
