### ISSUE TITLE
Stop formatter from line warpping !include tag

### ISSUE THREAD

**Issue by rickstaa** [redhat-developer/vscode-yaml#234]
As I saw the extension supports custom tags ([see #76](https://github.com/redhat-developer/vscode-yaml/issues/76)) I was wondering if there is a way to stop the formatter from formatting these custom tags? I currently use the [PyYaml](https://pypi.org/project/PyYAML/) `!include` in my .yaml file but the formatter keeps removing the linebreak (See gif below). I tried to add the tags I used to the custom tags settings variable.

```
"yaml.customTags": [
	"!secret scalar",
	"!include scalar",
	"!include_dir_merge_named scalar"
],
```

![formatting error](https://user-images.githubusercontent.com/17570430/66955592-f6d31280-f062-11e9-989e-b6ccc685e87d.gif)

**Comment by JPinkney** [comment]
We currently use the [yaml formatter from prettier](https://github.com/prettier/prettier) so you'll probably want to file a request there. Once its fixed there i'll update to the newest package

**Comment by rickstaa** [comment]
@JPinkney Thanks for your answer. I filled [a new issue in the prettier repository](https://github.com/prettier/prettier/issues/6674).

**Comment by rickstaa** [comment]
@JPinkney Prettier does currently not support these templates. As a result, a custom plugin has to be created to support these template tags. As I'm currently only using the `!include` the template I'm now fine with manual re-editing my files after each format. I will create a small plugin if I in the future start to use more template tags
