### ISSUE TITLE
Support schema in files without .yaml extension

### ISSUE THREAD

**Issue by pke** [redhat-developer/vscode-yaml#235]
Given this configuration

```json
"yaml.schemas": {
  "./.taprc.schema.json": "./.taprc"
},
```

The `.taprc` is not treated as YAML and does not offer syntax highlighting nor schema suggestions and validation.

Would that be possible to or do we have to use core VSCode settings to associate "YAML" with the `.taprc` file?

```json
"files.associations": {
  ".taprc": "yaml",
}
```

**Comment by JPinkney** [comment]
You'll have to associate it with yaml either by doing the file associations or you can do `ctrl+shift+p` to bring up command palette and then search for `Change Language Mode` and then change that to yaml

**Comment by pke** [comment]
I did the former, but the yaml-language-server does not seem to pick up on the file. Is there some diagnostics I could enable to see if the server loads the schema correctly?

**Comment by JPinkney** [comment]
Try setting `"yaml.trace.server": "verbose"` in the settings

and then open up the output view and in the dropdown select `YAML Support` and then try autocompletion, hover, etc and then paste what the output is and i'll see if theres something going wrong

**Comment by pke** [comment]
So it seems that the paths are resolved differently.

```js
"./.taprc.schema.json": ".taprc.yaml" // works OK
"./.taprc.schema.json": "./.taprc.yaml" // doesn't work
".taprc.schema.json": "./.taprc.yaml" // doesn't work
"/.taprc.schema.json": "./.taprc.yaml" // doesn't work
"/.taprc.schema.json": ".taprc.yaml" // doesn't work Unable to load schema from 'undefined': No schema specified
".taprc.schema.json": "/.taprc.yaml" // works OK
```

Only one of those not working printed something in the problems view.

I'll set trace to "verbose" now.

**Comment by ssbarnea** [comment]
There is huge number of tools that have config files using YAML that do not have `.yaml` extension. I hope we can sort this soon.

**Comment by JPinkney** [comment]
@ssbarnea You do not need `.yaml` extension in order for this extension to work. You just need the language mode for the specific file to be YAML. I believe the original issue ended up being a schema path configuration issue, @pke correct me if i'm wrong

**Comment by pke** [comment]
I did not further investigate this, it seems. I think once I uploaded the schema to schemastore it worked (cause VSCode uses the catalogue there to match file patterns).

**Comment by gorkem** [comment]
Closing this, as we do not really have a way to improve it further on the extension
