### ISSUE TITLE
VS Code Error message | Ansible nxos_acl module

### ISSUE THREAD

**Issue by NetDevLazg** [redhat-developer/vscode-yaml#236]
Hey There,

Im using a Ansible module nxos_acl to create access list on nexus devices. When I create a task to loop over multiple values there is two of the module options that gives syntax error, when I run the playbook is runs fine and does what it needs to do and when i disable the yaml extension on vs code the error goes away.

I receive the syntax error on <action> field and <state> field.

Error for action field: Valued is not accepted. Valid values: "permit", "deny", "remark.

Error for state field: Valued is not accepted. Valid values: "present", "absent", "delete_acl".

Code:

ntp_acl:
    - {name: NTP-LOCKDOWN, seq: "10", action: permit, proto: ip, src: 10.0.99.0/24, dest: any, state: present}
    - {name: NTP-LOCKDOWN, seq: "20", action: permit, proto: ip, src: 10.1.199.0/24, dest: any, state: present}
    - {name: NTP-LOCKDOWN, seq: "30", action: deny, proto: ip, src: any, dest: any, state: present}

- name: Creates NTP ACL
  nxos_acl:
    name: "{{ item.name }}"
    seq: "{{ item.seq }}"
    action: "{{ item.action }}"
    proto: "{{ item.proto }}"
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: "{{ item.state }}"
  loop: "{{ ntp_acl }}" # var located in role vars folder
  tags:
    - nx_os_baseline
    - nx_os_ntp
    - nx_os_ntp_acl

**Comment by JPinkney** [comment]
I'm not familiar with anything ansible related but it looks to be a problem with the schema that gets associated with your ansible file.

Are you using the ansible vscode extension or are you just opening an ansible file? Also do you have "yaml.schemaStore.enable": true in your settings.json (it's true by default)

**Comment by NetDevLazg** [comment]
I think we can close this out
