### ISSUE TITLE
What glob patterns are supported for yaml.schemas

### ISSUE THREAD

**Issue by darrenswart** [redhat-developer/vscode-yaml#240]
Wondering what glob patterns are supported for matching files?  I can't seem to get anything to work other than the asterick.  For example, `vol*.yml` will successfully match the file vol3.yml.  However, something like `vol[0-9].yml` doesn't appear to match the same file vol3.yml.  The same with `vol?.yml` it doesn't match vol3.yml either.  Both of these seem like valid glob patterns.

**Comment by gorkem** [comment]
This is now documented on README
