### ISSUE TITLE
Merge keys incorrectly cause schema validation errors

### ISSUE THREAD

**Issue by nfriend** [redhat-developer/vscode-yaml#241]
I'm playing around with the YAML schema support provided by this extension and I'm having trouble with YAML files that contain merge keys (`<<`).

At the root of my workspace, I created a `schema.json`:

```json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "test.yaml",
  "type": "object",
  "properties": {
    "person": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        }
      },
      "required": ["name"]
    }
  }
}
```

In my `settings.json`, I apply this schema to any files named `test.yaml`:

```json
"yaml.schemas": {
  "./schema.json": "**/test.yaml"
},
```

This schema validates correctly for a basic YAML file like this:

```yaml
person:
  name: John
```

<img width="243" alt="Screen Shot 2019-10-28 at 9 33 18 AM" src="https://user-images.githubusercontent.com/1638631/67678689-078a5f00-f966-11e9-9ea9-53f83dda7b1e.png">

However, if I instead provide the `name` property through a merge key, I get a validation error:

```yaml
base: &base
  name: John

person:
  <<: *base
```

<img width="351" alt="Screen Shot 2019-10-28 at 9 31 23 AM" src="https://user-images.githubusercontent.com/1638631/67678582-c09c6980-f965-11e9-9e22-08f12819d402.png">

**Comment by JPinkney** [comment]
Fixed as of 0.7.0!
