### ISSUE TITLE
Incorrect highlighting of multi-line values containing colons

### ISSUE THREAD

**Issue by itowlson** [redhat-developer/vscode-yaml#242]
This was reported on the Kubernetes extension at https://github.com/Azure/vscode-kubernetes-tools/issues/639, but it looks like it affects all YAML files even without the k8s extension being installed.

The syntax highlighting of multi-line values containing doesn't look right.  For example, consider the following YAML:

```yaml
foo:
  bar: |
    set_header 'Server: '
    set_header 'Access-Control-Allow-Methods: GET, PUT, POST, DELETE, PATCH, OPTIONS'
    set_header 'Access-Control-Allow-Origin: https://snip'
```

Here's how this gets highlighted:

![image](https://user-images.githubusercontent.com/865538/67818060-c4bab980-fb14-11e9-8755-2c05016a892f.png)

Note that the first line of the multiline value gets 'key' colouring (blue) up to the colon, then the closing quote and start of next line get 'value" (brown) colouring until the next quote, then key again until the colon, then value...

If I remove the colons, everything in the multi-line value is correctly coloured brown.

I tried this in an online YAML parser and it treated the multi-line section as a single value, so I think this should be valid - the colons shouldn't be being handled as key-value separators.

**Comment by itowlson** [comment]
Thanks @JPinkney. Raised upstream at https://github.com/microsoft/vscode/issues/83709.

**Comment by JPinkney** [comment]
It looks like this issue got fixed upstream so I'm closing

![image](https://user-images.githubusercontent.com/8839537/78403363-3b7b4780-75ca-11ea-8cac-25cf49e6726b.png)
