### ISSUE TITLE
Add breadcrumb

### ISSUE THREAD

**Issue by giggio** [redhat-developer/vscode-yaml#248]
Please add breadcrumb to the extension. Like json has it:

![breadcrumb](https://user-images.githubusercontent.com/334958/68721438-22c5b300-0591-11ea-9bac-7c34e7c1f669.png)

**Comment by fbricon** [comment]
works for me
<img width="446" alt="Screen Shot 2019-11-13 at 9 33 58 AM" src="https://user-images.githubusercontent.com/148698/68746381-c4ccb600-05f8-11ea-83f1-c2fe6d38ae54.png">

**Comment by giggio** [comment]
It only works if the file is saved.

**Comment by giggio** [comment]
Ok, this is not an issue with this extension, this is an issue with Code. Sorry about that. I'll report it there.
