### ISSUE TITLE
Hover support

### ISSUE THREAD

**Issue by gorkem** [redhat-developer/vscode-yaml#25]
When a property is hovered it should show its documentation

**Comment by JPinkney** [comment]
This is currently working for some nodes such as 
```
metadata:
    name:
```
We can hover over name and it works but its restricted by the current schema.

When the schema is fixed we will have to test this to make sure its working so i'll keep this issue open

**Comment by schickling** [comment]
That would be great!

**Comment by JPinkney** [comment]
In the newest version of the extension as long as its provided by the schema!
