### ISSUE TITLE
Valid mapping syntax in ansible task triggers syntax error

### ISSUE THREAD

**Issue by qguv** [redhat-developer/vscode-yaml#250]
The following valid Ansible task:

```yaml
- name: Install python-frontmatter
  pip: name=python-frontmatter version=0.4.2
```

causes vscode-yaml to emit a syntax error on the string `name=python-frontmatter version=0.4.2`:

```
Incorrect type. Expected "object".
```

**Comment by JPinkney** [comment]
Since this is a schema issue i'm going to close it here. Please raise the issue in https://github.com/SchemaStore/schemastore if you are still facing this error.
