### ISSUE TITLE
No autocomplete for Kubernetes 

### ISSUE THREAD

**Issue by d-w4lsh** [redhat-developer/vscode-yaml#253]
Is what I see [here](https://raw.githubusercontent.com/redhat-developer/vscode-yaml/master/images/demo.gif) supposed to work out of the box? I use VSCode on Windows 10 and there is no autocomplete for Kubernetes config files in yaml.

I tried putting schemas in yaml.schemas setting to no avail. For instance I receive "unable to parse content" error with the schema https://github.com/instrumenta/kubernetes-json-schema/blob/master/v1.16.0-standalone/all.json.

**Comment by JPinkney** [comment]
You have to set up the kubernetes to match the file you are working on by doing:
```
yaml.schemas: {
    "kubernetes": "my_yaml_file.yml"
}
```
When its done this way specific errors (such as matching multiple schemas when one must validate error) are automatically disabled for better editing experience.

However, if you want to use the schema you linked you have to use the raw github content
```
"yaml.schemas": {
    "https://raw.githubusercontent.com/instrumenta/kubernetes-json-schema/master/v1.16.0-standalone/all.json": "test.yaml"
  }
```

**Comment by d-w4lsh** [comment]
Got it. The "kubernetes" config does work but only after some Yaml has been written (i.e. after the apiVersion tag). Thanks!

**Comment by JPinkney** [comment]
No worries!

>  but only after some Yaml has been written 

yeah there's a bug report somewhere for that. Its been over a year and I still have no idea why it does that :man_shrugging:
