### ISSUE TITLE
Regression: duplicate key errors not reported since v0.5

### ISSUE THREAD

**Issue by SupSuper** [redhat-developer/vscode-yaml#256]
Pretty simple test case:
```yaml
a: 1
b: 2
c: 3
c: 4
```
On versions older than 0.5, this will correctly highlight a "duplicate key" error. On 0.5 and later, no error is reported.

**Comment by JPinkney** [comment]
Can confirm this isn't working. My guess is its something around [here](https://github.com/redhat-developer/yaml-language-server/blob/master/src/languageservice/parser/yamlParser07.ts#L193)

**Comment by JPinkney** [comment]
This should be working again as of the 0.7.0 version of the extension!
