### ISSUE TITLE
default value escape dollar sign?

### ISSUE THREAD

**Issue by jetersen** [redhat-developer/vscode-yaml#258]
We have this schema https://github.com/release-drafter/release-drafter/blob/master/schema.json

We have some defaults like `* $TITLE (#$NUMBER) @$AUTHOR` for `change-template`

When VS Code auto complete's the default

it becomes 
```yaml
change-template: *  (#) @
```

instead of the desired

```yaml
change-template: * $TITLE (#$NUMBER) @$AUTHOR
```

How do one properly escape I tried `\\` and `\\\\` to no avail.

**Comment by JPinkney** [comment]
Looks like a bug. When it automatically inserts the default its stripping characters but if you auto complete change-template and then do another seperate auto completetion after then it works

**Comment by casz** [comment]
Glad I could help find a bug 😅

**Comment by casz** [comment]
I realize that for yaml we need to quote the string but that is more schema related 😆

**Comment by msivasubramaniaan** [comment]
It is working as expected in the latest version. 
![image](https://user-images.githubusercontent.com/93245779/177311203-6b0665c8-77d6-40b8-827c-346bd13acea2.png)

**Comment by jetersen** [comment]
@msivasubramaniaan Great news!
