### ISSUE TITLE
Use of multiple glob patterns is not documented

### ISSUE THREAD

**Issue by ssbarnea** [redhat-developer/vscode-yaml#259]
I need to define multiple glob patterns for specific file types and apparently that is not possible because the configuration uses the schema name/location as a dictionary key.

Patterns I need to match to the same schema:
```
zuul.d/*.yaml
.zuul.d/*.yaml
.zuul.yaml
```

How can I configure these?

Related to https://github.com/redhat-developer/vscode-yaml/issues/240 and https://github.com/redhat-developer/vscode-yaml/issues/151

**Comment by JPinkney** [comment]
I believe this is undocumented right now, but you should be able to do:

```json
"yaml.schemas": {
    "my_schema.json": ["zuul.d/*.yaml", ".zuul.d/*.yaml", ".zuul.yaml"]
}
```
