### ISSUE TITLE
yaml.customTags not working when Ansible extension is also installed

### ISSUE THREAD

**Issue by ssbarnea** [redhat-developer/vscode-yaml#264]
I tried to add `!encrypted/pkcs1-oaep` to yaml.customTags to make it ignore it but apparently this feature does not work.

## Update
This has proven to be caused by Ansible extension by Microsoft and they already have an year old bug about messing other YAML extensions: https://github.com/VSChina/vscode-ansible/issues/230

Lets not close this bug because it seriously affecting YAML extension and we do not have a way to avoid it other then disabling the culprit extension.

Related: https://github.com/redhat-developer/vscode-yaml/issues/265

**Comment by pbsladek** [comment]
I can confirm this. Install Ansible vscode plugin - everything breaks in regards to custom tags. Uninstall Ansible vscode plugin. custom tags works np again.
