### ISSUE TITLE
Documentation for code completions

### ISSUE THREAD

**Issue by gorkem** [redhat-developer/vscode-yaml#27]
Display documentation for a property during code completions

**Comment by JPinkney** [comment]
This is currently working for some nodes such as 
```
metadata:
    name:
```
This is restricted by the current schema

**Comment by nikolasburk** [comment]
Is there any progress on this one? :)

**Comment by schickling** [comment]
Yeah, would be great if this would be support since this [worked in the "old" yaml plugin](https://github.com/adamvoss/vscode-yaml).

**Comment by JPinkney** [comment]
@nikolasburk @schickling Added in the newest version of the extension!
