### ISSUE TITLE
Configure tabSize only for yml file

### ISSUE THREAD

**Issue by b1zzu** [redhat-developer/vscode-yaml#274]
Hi, how can I configure the tabSize that the auto formatter will use only for yaml/yml files?

I've tried to do this:
```
"yaml.editor.tabSize": 2
```
and this
```
"yaml.tabSize": 2
```
but none of this are valid options

**Comment by fbricon** [comment]
You can try a variation of  vscode-yaml's default values for the YAML language:
https://github.com/redhat-developer/vscode-yaml/blob/4060dbf0d4671648bfc422191336b19b016fc47c/package.json#L146-L155

**Comment by JPinkney** [comment]
Yes, like Fred said you can do:
```
"[yaml]": { 
   "editor.tabSize": 4,
 } 
```
for example and it will change tab size to 4 for all yml/yaml files. 

Also, if you ever want to change the tabSize for a specific file in VSCode: on the status bar click where it says something like `spaces: 4` and then a menu should pop up where you can configure the number of spaces etc

**Comment by b1zzu** [comment]
Thanks, guys now I've understood how to use it
