### ISSUE TITLE
Receiving error when trying to install language server into extension for development

### ISSUE THREAD

**Issue by ericbiewener** [redhat-developer/vscode-yaml#275]
I'm following [these instructions](https://github.com/redhat-developer/vscode-yaml#developing-the-client-and-server-together) for "Developing the client and server together" but am receiving the following error when trying to run `yarn compile` in the language server directory:

> env: node\r: No such file or directory

Here's the full output:
![image](https://user-images.githubusercontent.com/253298/73571768-29432880-4424-11ea-80ab-f0e9b512f3c7.png)

As far as I can tell, I have followed the provided instructions correctly. I have installed node modules in both directories, and here's a screenshot of the directory structure:

![image](https://user-images.githubusercontent.com/253298/73571625-dc5f5200-4423-11ea-93fc-46d0999d1d15.png)

Let me know if there is any other relevant info I can provide. Perhaps this is a file system permissions issue?

**Comment by JPinkney** [comment]
Can you try again with npm instead of yarn? When I do `npm install` and then `npm run compile` everything succeeds with node v10.15.3 and npm 6.4.1

**Comment by ericbiewener** [comment]
Yup, that does it! I saw a `yarn.lock` file in the language server repo so I figured that was the right package manager to use (and trying to use `npm` _after_ didn't solve anything). Must have borked permissions though. I actually re-cloned the repos entirely to avoid any potential lingering permissions issues.

**Comment by JPinkney** [comment]
Yeah, I've really got to remove that pesky file! If you want, removing the yarn.lock could be your first PR to the language server :wink:
