### ISSUE TITLE
Error when pasting into YAML

### ISSUE THREAD

**Issue by taylorturner** [redhat-developer/vscode-yaml#276]
```
[Error - 4:17:45 PM] Request textDocument/documentSymbol failed.
  Message: Request textDocument/documentSymbol failed with message: Cannot read property 'endPosition' of null
  Code: -32603
```

This happens any time I copy and paste into a YAML.

**Comment by JPinkney** [comment]
Is there any specific yaml that does this? Also which version of the yaml extension are you using? I'm using the latest version of the extension and I cannot reproduce

**Comment by taylorturner** [comment]
Upon further investigation there are 2 errors it throws
```
[Error - 5:02:21 PM] Request textDocument/documentSymbol failed.
  Message: Request textDocument/documentSymbol failed with message: Cannot read property 'endPosition' of null
  Code: -32603 
[Error - 5:02:22 PM] Request textDocument/hover failed.
  Message: Request textDocument/hover failed with message: Cannot read property 'endPosition' of null
  Code: -32603
```
I'm copying this
```
    hostFqdn:
      envName: 'HOST_FQDN'
      value: &hostFQDN 'example.com'
```
It throws the errors when I paste, and I end up with a missing `'`
```
    hostFqdn:
      envName: 'ELEMENT_PLATFORM_HOST_FQDN'
      value: &hostFQDN 'platform.ean.io
```

**Comment by JPinkney** [comment]
I still cannot reproduce :(. Pasting it in works fine for me

**Comment by taylorturner** [comment]
Only other thing I can think of is that I’m using the VIM emulator for VSCode.

**Comment by JPinkney** [comment]
Hmm, I still haven't been able to reproduce this. @taylorturner Is this still an issue? Does this issue occur when you paste that in the middle of a yaml file or can you reproduce if you paste it into a new yaml file?

**Comment by gorkem** [comment]
Closing as this has been stale for a long time and can not be reproduced
