### ISSUE TITLE
How to define a new yaml schema and its file associations in another extension?

### ISSUE THREAD

**Issue by fbaligand** [redhat-developer/vscode-yaml#280]
If I want to add completion for a specific yaml file in another extension, what do I have to do?
Is there some documentation about that?

Ideally, just some configuration in package.json would be great! (like provided by vscode for json files, with “jsonValidation” entry)

**Comment by Livven** [comment]
This already exists and with the exact same syntax as `jsonValidation`:

```json
{
  "contributes": {
    "yamlValidation": [
      {
        "fileMatch": "yourfile.yml",
        "url": "./schema.json"
      }
    ]
  }
}
```

**Comment by fbaligand** [comment]
Great!
I will try it!

**Comment by fbaligand** [comment]
I just tested it, and it works great!
Thank you!

Maybe it misses just a doc sample? maybe in README.md?

**Comment by JPinkney** [comment]
Its near the bottom of this part of the readme https://github.com/redhat-developer/vscode-yaml#associating-a-schema-to-a-glob-pattern-via-yamlschemas right before the paragraph
