### ISSUE TITLE
Bug on auto-completion: default value is inserted just after semi-colon (instead of one space after)

### ISSUE THREAD

**Issue by fbaligand** [redhat-developer/vscode-yaml#281]
Say that I have this json schema:
``` json
		"pipeline.id": {
			"type": "string",
			"description": "The ID of the pipeline.",
			"default": "main"
		},
``` 

If I use auto-completion in my YAML file, typing `pipeline`, then press `<TAB>` key, I get this entry in my YAML file:
`pipeline.id:main`

The expected generated YAML entry should be:
`pipeline.id: main`

Could you fix this little bug?

**Comment by JPinkney** [comment]
Looks like the issue is here: https://github.com/redhat-developer/yaml-language-server/blob/master/src/languageservice/services/yamlCompletion.ts#L667

**Comment by fbaligand** [comment]
Thanks for your analysis and pointed line!
Indeed, I think that bug is around there. 
But more at line 693. Because, later some “value” variable affectations have a “ “ prefix, like line 719. 

what do you think about?

**Comment by JPinkney** [comment]
Yep, looks like most likely the spaces on 719, 722, 732, 735 need to be removed

**Comment by fbaligand** [comment]
Yes, this would be a nice way to fix!
The only (small) disadvantage of this way would be that when there is no simple value, but a line return and child properties, this would generate a "useless" space between `:` and `\n`.
I think about lines 704, 706, 725 and 728.

The other way is to add a `' '` prefix at lines 676, 687, 693, 699 and 743.

Which way do you prefer?

**Comment by fbaligand** [comment]
@JPinkney Tell me the way that you prefer, and then, I'm ready to submit a PR.

**Comment by JPinkney** [comment]
I think try the second way:
> The other way is to add a ' ' prefix at lines 676, 687, 693, 699 and 743.

and then if that doesn't work out try the first way

**Comment by fbaligand** [comment]
Ok, I will do so.

**Comment by fbaligand** [comment]
@JPinkney 

I just submitted the PR:
https://github.com/redhat-developer/yaml-language-server/pull/245

I tested on my vscode, it works as expected for me!

Can you review the PR?
