### ISSUE TITLE
The YAML Support server crashed 5 times in the last 3 minutes

### ISSUE THREAD

**Issue by Telokis** [redhat-developer/vscode-yaml#289]
The extension crashes when I open a yaml file.  
I've seen the similar issues and double checked that I am properly using the extension of this repository!

* Extension: `0.7.2`
* VScode: Version: `1.43.1 (user setup)`
* Commit: `fe22a9645b44368865c0ba92e2fb881ff1afce94`
* Date: `2020-03-18T07:01:20.184Z`
* Electron: `7.1.11`
* Chrome: `78.0.3904.130`
* Node.js: `12.8.1`
* V8: `7.8.279.23-electron.0`
* OS: `Windows_NT x64 10.0.18363`

```
Error: Cannot find module 'c:\Users\Telokis\.vscode\extensions\redhat.vscode-yaml-0.7.2\node_modules\yaml-language-server\out\server\src\server.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:717:15)
    at Module._load (internal/modules/cjs/loader.js:622:27)
    at Module._load (electron/js2c/asar.js:717:26)
    at Function.Module._load (electron/js2c/asar.js:717:26)
    at Function.Module.runMain (internal/modules/cjs/loader.js:944:10)
    at internal/main/run_main_module.js:17:11 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
[Info  - 12:24:03] Connection to server got closed. Server will restart.
internal/modules/cjs/loader.js:720
    throw err;
    ^
```

**Comment by fbricon** [comment]
is c:\Users\Telokis\.vscode\extensions\redhat.vscode-yaml-0.7.2\ really empty?

**Comment by JPinkney** [comment]
I think things to try would be to uninstall then re-install the extension. If that doesn't work then completely wipe the folder path and then re-install the extension. One of those should work.

I was using it on windows on the weekend and it was behaving as expected

**Comment by Telokis** [comment]
Uninstalling didn't fix the issue but wiping the directory manually did it, thanks.

(No idea where this error came from, though)
