### ISSUE TITLE
Bug with global json schema import?

### ISSUE THREAD

**Issue by JohnHillegass** [redhat-developer/vscode-yaml#291]
I had some issues getting this to work on MacOS. It is based off of an example from the README.

The setting config:
```
    "yaml.schemas": {
        "file:///Users/johnd/some-schema.json": ["some.yaml"],
    },
```
would yield 'Request textDocument/hover failed with message: Cannot read property '$ref' of null'.

In order to get it working, I had to adjust to:

```
    "yaml.schemas": {
        "/Users/johnd/some-schema.json": ["some.yaml"],
    },
```

Not sure if anyone else has reported this yet but wanted to drop a note in case it helps anyone facing similar issues.

**Comment by JPinkney** [comment]
Just merged your readme fix! so i'm going to close this issue

**Comment by JohnHillegass** [comment]
Thanks @JPinkney !
