### ISSUE TITLE
Can I add custom value for a tag?

### ISSUE THREAD

**Issue by al-wys** [redhat-developer/vscode-yaml#293]
I added a custom **resource type** in k8s, then I tried to deploy the type. But this extension prompted me that `Value is not accepted.`

![image](https://user-images.githubusercontent.com/16317690/79100488-34f28a00-7d99-11ea-83aa-bb9ce4500999.png)

**Comment by JPinkney** [comment]
Without actually modifying the schema itself there isn't any way that I can think of.

It might be worth it to try out: https://marketplace.visualstudio.com/items?itemName=ms-kubernetes-tools.vscode-kubernetes-tools it uses all the yaml features from this project but builds on that for better kubernetes support

**Comment by al-wys** [comment]
> Without actually modifying the schema itself there isn't any way that I can think of.
> 
> It might be worth it to try out: https://marketplace.visualstudio.com/items?itemName=ms-kubernetes-tools.vscode-kubernetes-tools it uses all the yaml features from this project but builds on that for better kubernetes support

Well, I saw this extension before. I thought this extension had too much features. I’d like to get a smaller one.  So, I didn’t choose this extension.

**Comment by JPinkney** [comment]
I'm going to close this because there's nothing we can do here. If you want to add in a custom type you'd have to modify the schema. The alternative route is to use the kubernetes extension which uses this extension for the yaml support.
