### ISSUE TITLE
Lack of reliability with use of schemastore.org 

### ISSUE THREAD

**Issue by ssbarnea** [redhat-developer/vscode-yaml#294]
Loading schemas from https://json.schemastore.org seems to be a permanent source of failures for this extension.

I think we need to consider alternative CDN that is more reliable especially as I see repeated failures and I never got an explanation about why it went down or what was done to avoid regression.  I am bit concerned that there is a single person being this URL which makes this a not only a reliability issue but also a security issue.

See https://github.com/SchemaStore/schemastore/issues/1009

**Comment by JPinkney** [comment]
There's not really anything I can do from my side for this. If there is an alternative that can be used then that would be fine but right now it provides the greatest number of common schemas that we can associate with automatically, a different repo where people can file issues/fixes for those schemas, and has been integrated for something like 2+ years with this extension IIRC

**Comment by apupier** [comment]
fixing https://github.com/redhat-developer/vscode-yaml/issues/308 might help schemastore.org to be more reliable.
