### ISSUE TITLE
Auto-completion on working

### ISSUE THREAD

**Issue by SUMIT0733** [redhat-developer/vscode-yaml#297]
While editing yaml file, the extension not suggesting auto-completion.

**Comment by JPinkney** [comment]
I'm going to need a little bit more info to understand the issue.

What YAML are you trying to autocomplete? What is the name of the file? Have you associated a schema with your file?

**Comment by SUMIT0733** [comment]
I am new to YAML, I have installed YAML support extension in VS code and added below in settings:
"yaml.schemas": {
    "kubernetes": "*.yaml"
  },

And, I want this extension for kubernetes file. 
Can you please provide a reference where can I find the steps that I can follow to proper setup of YAML auto completion.

**Comment by JPinkney** [comment]
The setup that you have is correct. You will need to provide minimum
`apiVersion: v1`
inside of your yaml file before the kubernetes schema will work

**Comment by apupier** [comment]
@SUMIT0733 I suppose that it is now working for you. i'm closing the issue. feel free to reopen if it is not working and you have more information
