### ISSUE TITLE
Auto complete is not working

### ISSUE THREAD

**Issue by Anandharaj** [redhat-developer/vscode-yaml#299]
![image](https://user-images.githubusercontent.com/6447717/82142749-2564d600-985c-11ea-8843-0dfa717b0940.png)

**Comment by Anandharaj** [comment]
![image](https://user-images.githubusercontent.com/6447717/82142766-49281c00-985c-11ea-975f-3ef427f4cbe4.png)

**Comment by JPinkney** [comment]
You have to type minimum
`apiVersion: v1`
before autocomplete will work the kubernetes schema. There used to be an issue around for this somewhere but I can't find it anymore

**Comment by erydrn** [comment]
@JPinkney according to what you suggest, still auto-completion does not work. I also installed and enabled Red Hat Yaml but still, Ctrl + Space does not suggest anything

**Comment by JPinkney** [comment]
@erydrn did you add in 

```
"yaml.settings": {
"kubernetes": "pod-definition.yaml"
}

into your vscode settings?

**Comment by vardanbansal-harness** [comment]
@JPinkney Facing the same issue as of today.

**Comment by JPinkney** [comment]
@vardanbansal-harness I'm going to need some details to understand your issue. What is in your `yaml.settings`? what is the yaml file you are trying to autocomplete? etc etc

**Comment by vardanbansal-harness** [comment]
Thanks for the quick revert @JPinkney . I simply added     
```
"yaml.schemas":{
		"kubernetes" : "*.yaml",
}
```
to my vscode settings.json file
Then I opened up a .yaml file in the same project to try it out.
Then as suggested by you above, wrote minimum `apiVersion: v1` for kubernetes auto-suggest to kick in.
If now in next line if try to check for auto-suggesting of `metadata` by typing just m and then control+space, it says 'No suggestions.'

**Comment by vardanbansal-harness** [comment]
Another thing is "yaml.settings" the right key or "yaml.schema". Documentation says the latter in README.

**Comment by JPinkney** [comment]
oops yes its "yaml.schemas" not "yaml.settings", I just mistyped

**Comment by vardanbansal-harness** [comment]
@JPinkney Do you see any issue with my config?

**Comment by JPinkney** [comment]
This is what I have no my side and it's working
![auto-complete](https://user-images.githubusercontent.com/8839537/83158750-28b95680-a0d3-11ea-825d-25ee60b1a6ec.png)

What OS are you on? Also which extensions do you have installed? For some reason the yaml.schemas looks a little darker which to me makes it seems like vscode-yaml isn't installed/isn't installed correctly. If you try and hover over yaml.schemas what does it say?

**Comment by vardanbansal-harness** [comment]
@JPinkney I'm currently on macOS Mojave. Yes you're correct it seems some issue with config. Below is what is says on hover:

![image](https://user-images.githubusercontent.com/48940704/83160711-2849ab80-a125-11ea-8c70-03dddebbd827.png)

So how did I get it till here:

Cloned, installed dependencies, compiled and ran https://github.com/redhat-developer/vscode-yaml by `npm install; npm run compile`

Then I proceeded to steps mentioned in thread above.

One weird thing is, if I wrap the key in [], like other keys above, it looks similar to other keys, but shows nothing on hover.

![image](https://user-images.githubusercontent.com/48940704/83161175-b58d0000-a125-11ea-8320-b70ae582bf1c.png)

**Comment by JPinkney** [comment]
Oh wait so you're trying to work on vscode-yaml? yaml.schemas will only be available when you start the extension host (or if you have the vscode-yaml extension installed). From the screenshots you sent are those from inside the extension host (the new vscode that launches with the extension installed) when you do run -> launch extension from within VSCode

**Comment by vardanbansal-harness** [comment]
@JPinkney Thank you so much. I appreciate your help in fixing this, I was able to make it work(in the extension host). One last question is it seems that `yaml.schemas` only accepts/supports json schema or a schema store url. I have few following questions:

1. Can I specify a yaml schema the same way as a json schema and expect it to work? Because currently, it doesn't work with a yaml schema.
2. Any workarounds to make it work with a yaml schema?

**Comment by JPinkney** [comment]
There's currently no way to load yaml schemas right now, only json schemas are accepted. There has been a pull request on the language server side (basically the part of this that provides the autocompletion, validation, etc) that was going to provide yaml schemas https://github.com/redhat-developer/yaml-language-server/pull/191 but I've been waiting for the user to add tests before I can proceed

**Comment by vardanbansal-harness** [comment]
@JPinkney Thanks for the update! 👍🏻

**Comment by JPinkney** [comment]
I'm going to close this issue as auto complete is working as expected when everything is configured correctly. If there is any other issues here feel free to create a new issue

**Comment by shubhamg7** [comment]
Hello! I am running into this problem with version 0.17.0. Here is my settings and the test I am running, any idea what I am missing here? Thanks!

![image](https://user-images.githubusercontent.com/67935201/143802710-10e2a377-1e4e-400e-bb94-04849b4fbcda.png)

I've tried restarting VSCode a few times now.

**Comment by AnjaliL** [comment]
Auto-completion is not working for me as well.
YAML Version - v0.17.0
Added the following lines in settings.json : 
"yaml.schemas": {
            "kubernetes" : "*.yaml"
    }
 
 Restarted the VSCode a fewtime after updating the settings.json file.

**Comment by mendax-sh** [comment]
> Você precisa digitar o mínimo `apiVersion: v1` antes que o preenchimento automático funcione no esquema do kubernetes. Costumava haver um problema para isso em algum lugar, mas não consigo mais encontrá-lo

Thanks

**Comment by Anvesh965** [comment]
This may be an issue with the DNS server. I faced the same problem and found a solution after one month.

To fix it, set up the DNS server by following the article below:

`https://developers.google.com/speed/public-dns/docs/using`

After this, make sure to add the following to `settings.json` in VS Code:

```json
"yaml.schemas": {
    "Kubernetes": "*.yaml"
  },

```
