### ISSUE TITLE
Disable italic in block style indicators

### ISSUE THREAD

**Issue by Sighery** [redhat-developer/vscode-yaml#302]
Currently the block style indicators show up in italic:

![2020-05-23-161952_383x302_scrot](https://user-images.githubusercontent.com/11218602/82733078-bda60380-9d11-11ea-85a0-ab55474efb57.png)

I was wondering if there was any way to disable this style. As shown in the image, the pipe block character with italic (`test1` key) looks like a forward slash (`test3` key) which leads to confusion as you might think you've mistyped it and gotten the wrong character.

**Comment by JPinkney** [comment]
I can't actually reproduce this on my side
<img width="308" alt="Screen Shot 2020-05-23 at 4 14 24 PM" src="https://user-images.githubusercontent.com/8839537/82739773-8551f580-9d10-11ea-82ee-a08f08e62b9d.png">
Do you have any custom fonts enabled or maybe custom theme? Does this still happen if vscode-yaml is disabled?

**Comment by Sighery** [comment]
I tried changing the fonts and the issue still showed up. However, I totally forgot themes were a thing. It's indeed caused by a theme and not the style of this extension, apologies.

For anyone maybe stumbling into this in the future, the theme that caused this for me is Material Theme by Mattia Astorino. I'll look around their config and issues and move this issue over to their repository.

Thanks for all your help and apologies again for taking up your time with something unrelated :sweat_smile:
