### ISSUE TITLE
add syntax highlight for Ubuntu 20.04 - focal 

### ISSUE THREAD

**Issue by gauthamp10** [redhat-developer/vscode-yaml#303]
Shows focal as an error.

![Screenshot_2020-05-24_02-51-01](https://user-images.githubusercontent.com/31800012/82740760-7186ad80-9d69-11ea-9d1d-713abd76e351.png)

**Comment by JPinkney** [comment]
I'm not entirely sure what the issue is here. What is focal? Is this from a schema? Or did that issue appear when you opened a certain file? If so what is the filename?

**Comment by gauthamp10** [comment]
I meant, the vscode-yaml extension is not recognising 'focal fossa' - [focal] short distribution name of latest Ubuntu 20.04. It recognises older versions like bionic. xenial etc..

**Comment by JPinkney** [comment]
Please file the issue on https://github.com/SchemaStore/schemastore. This extension pulls in schemas from there and the travis schema from the schemastore seems to be incorrect!

**Comment by gauthamp10** [comment]
Sure. Thank you.

**Comment by gauthamp10** [comment]
[https://github.com/SchemaStore/schemastore/pull/1056](url)

Solved.
