### ISSUE TITLE
If a registeredContributor of schema provider is throwing an error, it is forbidding other registered schema providers to work

### ISSUE THREAD

**Issue by apupier** [redhat-developer/vscode-yaml#323]
steps to reproduce:
- provide your own schema provider whcih is an array
- install VS Code Kuerbetes extension
- put text ```- ``` in the file
- VS Code Kubernetes is throwing an error, it prevents other registered schema providers to be evaluated

**Comment by gorkem** [comment]
@apupier Is this fixed now?

**Comment by apupier** [comment]
this test https://github.com/redhat-developer/vscode-yaml/blob/bbd041c9ff4bda173fd5fad721268a3e3b7a7029/test/schemaProvider.test.ts#L141 tends to mean yes.
