### ISSUE TITLE
High CPU usage

### ISSUE THREAD

**Issue by andy812** [redhat-developer/vscode-yaml#325]
<img width="1566" alt="изображение" src="https://user-images.githubusercontent.com/29895539/88203953-3e6e7680-cc53-11ea-8992-a8e8f1e6651c.png">
I use v0.9.1, VS Code 1.47.2. 
As you see vscode-yaml uses the whole core when i opened only 4 small yaml files.

**Comment by JPinkney** [comment]
Duplicate of https://github.com/redhat-developer/vscode-yaml/issues/166
