### ISSUE TITLE
how to use my own local schema?

### ISSUE THREAD

**Issue by dcsan** [redhat-developer/vscode-yaml#332]
I've read the docs a few times and having trouble getting going with schema validation.
I want to have a custom schema to validate against for something I'm building.

Following [associating](https://github.com/redhat-developer/vscode-yaml#associating-a-schema-to-a-glob-pattern-via-yamlschemas) a schema

I have this in my `.vscode` directory

```json
{
  "yaml.schemas": {
    "../cdn/schemas/storyline.json": [
      "../cdn/story*/story.yaml"
    ]
  }
}
```

so those rel-paths should point to the files to apply the schema to

![image](https://user-images.githubusercontent.com/514002/88552207-abc63280-cfd8-11ea-81f0-4c1e7dcc7f7b.png)

So given a very basic schema:

>  "../cdn/schemas/storyline.json"

```json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "title": "storyline",
  "definitions": {
    "story": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string",
          "description": "name of the story"
        },
        "cname": {
          "type": "string",
          "description": "canonical computer readable name"
        }
      }
    }
  }
}
```

It should validate against a file like this

> ../cdn/story-test/story.yaml

```yaml
story:
  name: aa
  cname: 123
```

But I can't tell if anything is working.
When I type I don't get any suggestions...

![image](https://user-images.githubusercontent.com/514002/88552697-3c9d0e00-cfd9-11ea-8da7-4fb30c57bd7a.png)

And there are no commands for yaml added to the command palette.
![image](https://user-images.githubusercontent.com/514002/88552756-50487480-cfd9-11ea-8504-d0a5088ab187.png)

I've restarted VSCode

![image](https://user-images.githubusercontent.com/514002/88552823-622a1780-cfd9-11ea-9e85-6bc8ba2678ce.png)

and the extension is running.

What am I doing wrong ¯\_(ツ)_/¯

**Comment by JPinkney** [comment]
It should be:
```
{
  "yaml.schemas": {
    "cdn/schemas/storyline.json": [
      "cdn/story*/story.yaml"
    ]
  }
}
```
It's relative to the root of the project. Not entirely sure if `cdn/story*/story.yaml` will work though, I've never tested something like that so you might have to specify them manually

**Comment by dcsan** [comment]
thanks. updated, also I think maybe my schema itself wasn't correct.
hardwired a single path to test this out for now

```
{
  "yaml.schemas": {
    "cdn/schemas/storyline.json": [
      "cdn/story-test/story.yaml"
    ]
  }
}
```

and schema
```
{
  "title": "storyline",
  "definitions": {
    "story": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string",
          "description": "name of the story"
        },
        "cname": {
          "type": "string",
          "description": "canonical computer readable name"
        }
      }
    }
  }
}
```
but still no dice/errors/suggestions or palette commands. 


So there's no way in the target YAML file to specify which schema it should use?
that seems the more natural way to do this.

**Comment by JPinkney** [comment]
You'll need to use properties as the root:
```
{
  "title": "storyline",
  "properties": {
    "story": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string",
          "description": "name of the story"
        },
        "cname": {
          "type": "string",
          "description": "canonical computer readable name"
        }
      }
    }
  }
}

```

**Comment by JPinkney** [comment]
Also, in the next version you'll be able to add a comment at the top of the file that looks like:
```
# yaml-language-server: $schema=my_schema_location
```

**Comment by dcsan** [comment]
cool! I got it working now, thanks for your help!
This might serve as a useful example for anyone else getting started...
