### ISSUE TITLE
Warning on NODE_TLS_REJECT_UNAUTHORIZED environment variable set to '0'

### ISSUE THREAD

**Issue by psteiner** [redhat-developer/vscode-yaml#334]
YAML Support output shows the following warning for YAML v0.9.1 on opening a YAML document:

```
[Error - 10:04:05 AM] (node:14916) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
[Error - 10:04:05 AM] (node:14916) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
```

Version: 1.47.3 (user setup)
Commit: 91899dcef7b8110878ea59626991a18c8a6a1b3e
Date: 2020-07-23T13:12:49.994Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.14393

**Comment by Dirk-Manderin** [comment]
I get the same error just installing the extension.

**Comment by JPinkney** [comment]
Are http.proxy or http.proxyStrictSSL settings set?

**Comment by Dirk-Manderin** [comment]
> Are http.proxy or http.proxyStrictSSL settings set?

For me, http.proxy is off, http.proxystrictssl is on

**Comment by psteiner** [comment]
My settings:
http.proxy is off
http.proxystrictssl is on
http.proxyAuthorization is null
http.proxySupport is 'override' (default value)

**Comment by Morriz** [comment]
Any updates here? Why is this extension setting global env `NODE_TLS_REJECT_UNAUTHORIZED`? If it decides to do insecure requests it does not need to set this

**Comment by JPinkney** [comment]
This project isn't setting `NODE_TLS_REJECT_UNAUTHORIZED`. At least not that I can find

**Comment by Morriz** [comment]
Strange, I only get that error in the output of this plugin. So that must have originated somewhere else then? I think this should then be closed ;)

Maybe somebody can explain why this plugin became suspect. It could be helpful when wrapping solutions to catch this error to give some context in the logs (like "This is likely to happen when ...")

**Comment by JPinkney** [comment]
I wonder if a different plugin is setting the env variable and then this plugin shows the error message when it's grabbing the schemas? I still haven't been able to reproduce this with my plugins. Can you give me a list of your plugins and then potentially related settings (like the http settings) and I can try some combinations and see where it's occurring

**Comment by Morriz** [comment]
ai, I have over 60 plugins...I just think it is good to understand this is related to lower level configuration not touched by this etension...but thanks for wanting to help ;)

**Comment by gorkem** [comment]
Closing this issue, please open another issue if this is still reproducible when running only this extension.
