### ISSUE TITLE
syntax error in circleci executor when parameter provided

### ISSUE THREAD

**Issue by iwt-svenulrich** [redhat-developer/vscode-yaml#335]
Here is an example how i can pass parameters into an executor:
https://discuss.circleci.com/t/how-to-pass-executor-parameters-in-cypress-orb/34345/2

but in vscode i get syntax errors:
![syntax-error](https://user-images.githubusercontent.com/59651272/88766309-182b6800-d178-11ea-853f-ad671eb496aa.png)

yaml plugin version: 0.9.1

circleci workflow version: 2.1

vscode:
Version: 1.47.2
Commit: 17299e413d5590b14ab0340ea477cdd86ff13daf
Date: 2020-07-15T18:18:50.054Z (1 wk ago)
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 18.7.0

**Comment by JPinkney** [comment]
This looks like an issue with the circle ci schema itself. Please file an issue on https://github.com/SchemaStore/schemastore. When its fixed there reload VSCode and it will automatically pick up the changes
