### ISSUE TITLE
Incompatible `vscode-languageserver-types` versions cause too long path on Windows.

### ISSUE THREAD

**Issue by kittaakos** [redhat-developer/vscode-yaml#336]
We are hitting a [_Path too long_ error on Windows](https://github.com/arduino/arduino-pro-ide/issues/293) when consuming the `vscode-yaml@0.7.2` VS Code extension in a bundled Theia-based electron application.

The problem:
 - [Theia](https://theia-ide.org/) can run VS Code extension.
 - In a Theia-based electron app, we include the `vscode-yaml` VS Code extension as-is at package time.
 - When users try to unpack the electron app ZIP they hit a path too long error. By default, Windows can handle max 260 characters in paths.

Apparenty, it's easy to exceed this max 260 char limit on Windows. For example:
```
vscode-yaml/extension/node_modules/yaml-language-server/out/server/node_modules/vscode-languageserver-protocol/node_modules/vscode-languageserver-types/tsconfig.esm.json
```

I logged the `vscode-languageserver-types` usage with [`npm-why`](https://github.com/amio/npm-why) and got this report:
```
npm-why vscode-languageserver-types

  Who required vscode-languageserver-types:

  vscode-yaml > vscode-languageclient > vscode-languageserver-protocol > vscode-languageserver-types@3.14.0
  vscode-yaml > yaml-language-server > vscode-json-languageservice > vscode-languageserver-types@3.15.1
  vscode-yaml > yaml-language-server > vscode-languageserver > vscode-languageserver-protocol > vscode-languageserver-types@3.14.0
  vscode-yaml > yaml-language-server > vscode-languageserver-types@3.15.1
```

Since the `vscode-languageserver-types` versions (`3.14.0` and `3.15.1`) are not compatible, `npm` cannot hoist them to the root of the `node_modules`. Are you willing to accept PRs aligning these versions to reduce the path length? I hope this is possible at all, most likely `yaml-language-server` needs to be updated too.

Thanks for this great extension!

**Comment by JPinkney** [comment]
Yeah, if you provide a PR aligning the versions I'll take a look. I can't imagine you'll run into any issues updating

**Comment by kittaakos** [comment]
We decided to use a generic app installer solution instead of trying to fix potential too long path issues in each VS Code extension we use. Thank you for being open to this change 👍 

Closing as _won't do_.
