### ISSUE TITLE
False reporting in a github actions yml file

### ISSUE THREAD

**Issue by tapsboy** [redhat-developer/vscode-yaml#338]
My issue might be dumb and maybe some other factors are at play

It seems this extension has some sort of reliance on another extension related to github actions

Gives a false +ve error as below when enabled

![image](https://user-images.githubusercontent.com/868525/89108625-f1836080-d407-11ea-8455-bedf3d99f059.png)

No error as below when disabled

![image](https://user-images.githubusercontent.com/868525/89108641-02cc6d00-d408-11ea-82c4-acc162b33b17.png)

While, I personally don't need to redhat yaml extension, it gets installed when I install Atlassian VScode JIRA plugin (https://bitbucket.org/atlassianlabs/atlascode/src/main/)

**Comment by gorkem** [comment]
Do you have [this extension](https://marketplace.visualstudio.com/items?itemName=me-dutour-mathieu.vscode-github-actions)installed ? Does disabling that one and re - starting vscode work?

**Comment by tapsboy** [comment]
Sorry,I didn't have any luck with restarts or reloads, but looks like I have to try the suggestion at https://github.com/Lona/vscode-github-actions/issues/11

**Comment by gorkem** [comment]
Do you have any mappings on the settings for yaml.schemas?

**Comment by tapsboy** [comment]
Yes, I did have those. 

```json
    "yaml.schemas": {
        "file:///Users/tapanshah/.vscode/extensions/me-dutour-mathieu.vscode-github-actions-2.2.7/schemas/workflow.schema.json": "/.github/workflows/*.yml",
        "file:///Users/tapanshah/.vscode/extensions/me-dutour-mathieu.vscode-github-actions-2.2.7/schemas/action.schema.json": "/action.yml",
        "file:///Users/tapanshah/.vscode/extensions/atlassian.atlascode-2.6.6/resources/schemas/pipelines-schema.json": "bitbucket-pipelines.yml"
    },
```

`vscode-github-actions` was upgraded to 3.x.x sometime back. Probably the earlier version of the `vscode-github-actions` extension added those and thus disabling/uninstalling just `vscode-github-actions` alone didn't help and I had to disable yaml schemas

I removed the first 2 lines manually and it stopped complaining

**Comment by tapsboy** [comment]
Thanks for the quick followup @gorkem on a weekend
