### ISSUE TITLE
YAML Extension Does Nothing...

### ISSUE THREAD

**Issue by robvet** [redhat-developer/vscode-yaml#339]
Installed the Red Hat YAML Extension into VS Code.

No statement completion, no validation, nothing.

Would almost seem that it's not getting out to your yaml-language-server?

Would love to get this working.  Please advise.

Thanks

robvet@microsoft.com

**Comment by JPinkney** [comment]
It does nothing because you haven't told it which schema to use for your yaml file. You can do this by following: https://github.com/redhat-developer/vscode-yaml#associating-a-schema-to-a-glob-pattern-via-yamlschemas

**Comment by robvet** [comment]
Hello Josh…

Thanks for your prompt response – very much appreciate.

Can see in VS Code where to configure the schema for the RedGate extension:

[cid:image001.png@01D668D9.B6ACFAF0]

Thinking I have to input a specific schema location:

[cid:image008.png@01D668DB.1E48C3A0]

Could you possibly point to a link that show the steps to configure this?

Thanks!!

Rob Vettor  | Principal Cloud-Native Application Architect
                      | SSG IP Architect
                      | Microsoft Certified Trainer
                      | CNCF (Cloud-Native Computing Foundation) Speaker Bureau<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.cncf.io%2Fspeaker%2Frobvet%2F&data=02%7C01%7Crobvet%40microsoft.com%7C4f91ec2c80f148e1d8df08d7cf475847%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637205777651526225&sdata=CrbTGz%2BmGfvfff25gczEOBjRRon13Vo0LmRA7UZQ5tE%3D&reserved=0>
                      | Owner: Microservices with Containers WorkshopPLUS
                      | Developer Advisory Services for Azure
[cid:image002.jpg@01D668D9.B6ACFAF0]   [cid:image003.png@01D668D9.B6ACFAF0]

[Description: cid:image001.gif@01CC9CCD.D94B9620]  214-707-0584
[Description: cid:image003.gif@01CC9CCD.D94B9620]   robvet@microsoft.com<mailto:robvet@microsoft.com>
[cid:image006.jpg@01D668D9.B6ACFAF0]  www.thinkingincloudnative.com<https://nam06.safelinks.protection.outlook.com/?url=http%3A%2F%2Fwww.thinkingincloudnative.com%2F&data=02%7C01%7Crobvet%40microsoft.com%7C4f91ec2c80f148e1d8df08d7cf475847%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637205777651536180&sdata=A8J9SmdjhA%2BDXPMWSfoBy4QK8JuPeIGF8jV%2FWqfngVI%3D&reserved=0>

Co-Author of…
[cid:image007.png@01D668D9.B6ACFAF0]<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fdotnet%2Farchitecture%2Fcloud-native%2F&data=02%7C01%7Crobvet%40microsoft.com%7C4f91ec2c80f148e1d8df08d7cf475847%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637205777651536180&sdata=krj4OY1RJX3KfByGp2BrYDXBR%2BWcDNvJ0xpMzXhGhqc%3D&reserved=0>

**Comment by JPinkney** [comment]
You might have to add in the pictures through the github UI, they don't show up rn

**Comment by robvet** [comment]
Hello Josh…

Still trying to figure out how to get the RedHat YAML extension to work in VS Code.

In VS Code, there is a configuration screen for YAML which is looking for a reference to the yaml.schema.

{
    "yaml.schemas": {

    }
}


I believe this is where you input the reference for the YAML schema.

Not sure what value to add here.

Any help would be greatly appreciated.

Thanks in advance!

Rob Vettor  | Principal Cloud-Native Application Architect
                      | SSG IP Architect
                      | Microsoft Certified Trainer
                      | CNCF (Cloud-Native Computing Foundation) Speaker Bureau<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.cncf.io%2Fspeaker%2Frobvet%2F&data=02%7C01%7Crobvet%40microsoft.com%7C4f91ec2c80f148e1d8df08d7cf475847%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637205777651526225&sdata=CrbTGz%2BmGfvfff25gczEOBjRRon13Vo0LmRA7UZQ5tE%3D&reserved=0>
                      | Owner: Microservices with Containers WorkshopPLUS
                      | Developer Advisory Services for Azure
[cid:image001.jpg@01D6728A.AB05B6A0]   [cid:image002.png@01D6728A.AB05B6A0]

[Description: cid:image001.gif@01CC9CCD.D94B9620]  214-707-0584
[Description: cid:image003.gif@01CC9CCD.D94B9620]   robvet@microsoft.com<mailto:robvet@microsoft.com>
[cid:image005.jpg@01D6728A.AB05B6A0]  www.thinkingincloudnative.com<https://nam06.safelinks.protection.outlook.com/?url=http%3A%2F%2Fwww.thinkingincloudnative.com%2F&data=02%7C01%7Crobvet%40microsoft.com%7C4f91ec2c80f148e1d8df08d7cf475847%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637205777651536180&sdata=A8J9SmdjhA%2BDXPMWSfoBy4QK8JuPeIGF8jV%2FWqfngVI%3D&reserved=0>

Co-Author of…
[cid:image006.png@01D6728A.AB05B6A0]<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fdotnet%2Farchitecture%2Fcloud-native%2F&data=02%7C01%7Crobvet%40microsoft.com%7C4f91ec2c80f148e1d8df08d7cf475847%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637205777651536180&sdata=krj4OY1RJX3KfByGp2BrYDXBR%2BWcDNvJ0xpMzXhGhqc%3D&reserved=0>

**Comment by JPinkney** [comment]
You can follow the readme on how to associate a schema in yaml.schemas: https://github.com/redhat-developer/vscode-yaml#associating-a-schema-to-a-glob-pattern-via-yamlschemas

The basic idea is that you have a schema (can be local or on the internet) and then you associate the schema to a glob pattern. When the glob pattern is matched the schema will be applied and you will get things like auto completion, validation, etc.
E.g.
```
"yaml.schemas": {
    "http://json.schemastore.org/composer": ["composer.yaml"],
}
```

In this case, when you open up a composer.yaml file in vscode it will pull the composer schema from the json schema store and then use that for completion, validation, etc

**Comment by ssbarnea** [comment]
I love this extension but lets face it: we need to make it have a **meaningful set of default settings** or most of the (new) users will just hate it from start.

Users should be able to override these defaults but we still need them.

**Comment by Trigun27** [comment]
Maybe not default settings but writer the text bold and bigger size!

**Comment by Trigun27** [comment]
@ssbarnea any tips for meaningful set of defaults? thanks)

**Comment by JPinkney** [comment]
> I love this extension but lets face it: we need to make it have a meaningful set of default settings or most of the (new) users will just hate it from start.

Which defaults could we add to enhance the user experience? We have the json schemas set for specific files like .travis.yml, appveyor.yml, circleci.yml, etc (all the yaml files that have distinct names) and then we have api to enabled better yaml support through tools like vscode-tekton and vscode-kubernetes. Maybe we could include more default custom tags? I'm not sure. Feel free to open an issue with suggestions and other people can add things as well!

**Comment by roncanepa** [comment]
Another data point.

I just installed this extension because it seems to be the internet's go-to extension for writing yaml in vscode.  I expected it to be able to do basic yaml linting OOTB and was interested in using the more powerful schema features later.

I've spent way too much time restarting vscode and checking the extension settings and such to try and figure out why it's not doing basic linting.

So some kind of default along this line would be helpful.  Principle of least surprise wouldn't be that it's necessary to do setup for a basic feature of an extension.  Alternatively, a post-install screen could help clarify this, as well.

**Comment by JPinkney** [comment]
WDYM basic yaml linting? Normal parse errors like duplicated keys, etc, etc? Those should all be working OOTB. Please create an issue with your yaml if thats not the case.

**Comment by roncanepa** [comment]
@JPinkney interesting.  Thank you for clarifying.  I'll look things over again and then post a separate issue if needed.

**Comment by gorkem** [comment]
I am closing this, please. If there are more items to resolve, please open issues for those specific items.
