### ISSUE TITLE
Add more documentation

### ISSUE THREAD

**Issue by schickling** [redhat-developer/vscode-yaml#34]
This plugin seems very promising! Would be great to have more documentation around the usage & installation in the readme.

**Comment by JPinkney** [comment]
I've added more documentation around the usage and installation in the readme in ab673602760d339816b2f4d5dcd28c935be589bd. Let me know if theres anything specifically that you'd like me to add!

**Comment by schickling** [comment]
I think it would be great if the language service server had a concrete example URL and mention that it supports schemastore out of the box. 

Other than that it’s great!
