### ISSUE TITLE
Unknown tag 

### ISSUE THREAD

**Issue by lego963** [redhat-developer/vscode-yaml#343]
Zuul CI in secrets.yaml: unknown tag <!encrypted/pkcs1-oaep>
Here you can see zuul doc for secrets: https://zuul-ci.org/docs/zuul/discussion/encryption.html#encryption
![image](https://user-images.githubusercontent.com/17201690/90040986-50cb5580-dcd1-11ea-8501-0338419d826b.png)

**Comment by JPinkney** [comment]
Have you tried using the yaml.customTags setting: https://github.com/redhat-developer/vscode-yaml#language-server-settings and doing:
```
"yaml.customTags": [
    "!encrypted/pkcs1-oaep scalar"
],
```

**Comment by lego963** [comment]
It broke everything
![image](https://user-images.githubusercontent.com/17201690/90048095-ac9adc00-dcdb-11ea-87be-b2cdf61517e0.png)

**Comment by JPinkney** [comment]
I had the wrong type. It should be:
"yaml.customTags": [
    "!encrypted/pkcs1-oaep array"
],

**Comment by lego963** [comment]
still 
![image](https://user-images.githubusercontent.com/17201690/90050698-4021dc00-dcdf-11ea-9474-9f5eb2371e0b.png)

**Comment by lego963** [comment]
sequence fixed it

**Comment by JPinkney** [comment]
can you please post a sample text of the yaml, its hard to debug without having the actual contents to test out on

**Comment by JPinkney** [comment]
Ah good to hear, I must have messed up the custom tag type!

**Comment by lego963** [comment]
sorry :D
