### ISSUE TITLE
 I hope you can add support for formatting “spring-boot-properties-yaml”

### ISSUE THREAD

**Issue by Wonder2018** [redhat-developer/vscode-yaml#346]
As the title says. The Spring Boot configuration file _application.yml_ is recognized as a _spring-boot-properties-yaml_ file in vscode. If I want to use _redhat-yaml_ to format it, I need to manually change the recognized file type. But in this way, I cannot use spring's _spring-configuration-metadata.json_ file to verify property settings and get code hints. So I hope this extension can add support for formatting the _spring-boot-properties-yaml_ file. The syntax of _application.yml_ is the same as that of ordinary _yml_ files, and the formatting program can be shared.

Thanks

**Comment by lukaszmoroz** [comment]
See https://github.com/microsoft/azure-pipelines-vscode/issues/209#issuecomment-718168926, this however does not work with this extension for some reason.
