### ISSUE TITLE
'yaml.schemas' configuration doesn't work on windows with full path

### ISSUE THREAD

**Issue by evidolob** [redhat-developer/vscode-yaml#347]
When I provide json scheme with `yaml.schemas` and put full path to scheme, like:
```
C:\Users\yevhen\Documents\GitHub\test\basic_completion_schema.json
```

This scheme doesn't pick up, and there are no completion items provided.

But when i replace path with:
```
basic_completion_schema.json
```
It works as expected.

Related test is https://github.com/redhat-developer/vscode-yaml/blob/master/test/completion.test.ts#L19

That test pass on linux and mac, but fail on windows.

**Comment by evidolob** [comment]
The problem in https://github.com/redhat-developer/yaml-language-server/blob/master/src/languageservice/services/schemaRequestHandler.ts#L24 as path on windows has kind of scheme `c:\` that symbols transforms in to 'scheme' for URI. 

@JPinkney WDYT?

**Comment by JPinkney** [comment]
Yeah that looks to be the case. I think you might be able to to do:
```
if (scheme === 'file' || scheme === "c") {
```
here: https://github.com/redhat-developer/yaml-language-server/blob/master/src/languageservice/services/schemaRequestHandler.ts#L27

**Comment by evidolob** [comment]
Yes, but if path will be `d:\something`? I think we need to solve this in general, I'm thinking to add check if OS is windows then we may use `vscode.Uri.file()` method to parse path, and then check uri scheme.

**Comment by JPinkney** [comment]
That's true, I think
> I'm thinking to add check if OS is windows then we may use vscode.Uri.file() method to parse path, and then check uri scheme.

I think that would work better, I just don't know that much about windows
