### ISSUE TITLE
Code completion list empty on empty file

### ISSUE THREAD

**Issue by evidolob** [redhat-developer/vscode-yaml#349]
When schema mappings is setup to use `kubernetos` scheme, on empty yaml file, completion list empty, but if file contains at least one field, completion woks normally:

![ezgif com-video-to-gif (35)](https://user-images.githubusercontent.com/929743/90773252-4b3bc400-e2fe-11ea-90a0-fcfbf148279e.gif)

**Comment by anasri72** [comment]
I have this issue as well.
