### ISSUE TITLE
Duplicate key error on non-duplicate object keys

### ISSUE THREAD

**Issue by cretz** [redhat-developer/vscode-yaml#352]
![image](https://user-images.githubusercontent.com/206396/90820280-c4371d80-e2f6-11ea-8d85-59f3eed29a01.png)

That is showing that those keys are duplicates even though they are not.

**Comment by joshuawilson** [comment]
What schema are you using? 
How do I reproduce this?

**Comment by JPinkney** [comment]
No schema needed, just the contents themselves generate an error

```
foo:
  { bar: baz }:
    - value
  { qux: quux }:
    - value
```
