### ISSUE TITLE
Error spam when editing yaml file with comments

### ISSUE THREAD

**Issue by matttattoli** [redhat-developer/vscode-yaml#353]
```
[Error - 4:35:02 PM] Request textDocument/hover failed.
  Message: Request textDocument/hover failed with message: Cannot read property 'lineComments' of undefined
  Code: -32603 
```

Getting spammed with errors into the YAML Support output when I hover over any comment in my YAML file.

This starting happening since 0.10.0, this error does not appear on 0.9.1

![image](https://user-images.githubusercontent.com/14338207/90823153-8096e080-e303-11ea-80a7-02bd072ad8ff.png)

**Comment by disconn3ct** [comment]
See #355 for a possible workaround: Remove either comments OR leading ---
