### ISSUE TITLE
Clearing the downloaded schema cache

### ISSUE THREAD

**Issue by RoboPhred** [redhat-developer/vscode-yaml#357]
I recently had a typo in a schema file I uploaded to github, where a $ref was pointing to the wrong url.  I have since corrected this.

However, I cannot get this extension to reload the file, it always complains about the typo version, and shows the typo url as the url it fails to fetch.  This is despite the code in question having been updated.

This does not appear to be an issue with web caching; github reliably returns the corrected version when I hit the url.  The issue as far as I can tell seems to be cached locally.

I have tried
- Restarting visual studio
- Uninstalling and reinstalling the YAML extension

None of these activities has cleared the cache, and the broken file is still being used.

Can you give me any insight as to how or where this extension caches its downloaded schemas?

**Comment by JPinkney** [comment]
Is the yaml-language-server still running in the background somewhere? It only caches the schema in memory, if the language server stops then the cache is gone

**Comment by RoboPhred** [comment]
The issue cleared itself up after a while.  It definitely held the cache between restarts but this is at least no longer an issue for me.
