### ISSUE TITLE
Kubernetes Auto generation  yaml files

### ISSUE THREAD

**Issue by cskalyan** [redhat-developer/vscode-yaml#365]
I am using Visual Studio Code to write or update yaml files, how ever auto generation of yaml files for kubernetes using VScode  supports only Pod, Deployment, Service, ReplicationController. To Create other yaml files like ingress, network, PV, PVclaims; auto generation is not working. Can you please add the feature to generate yml templates for other resources as well.

**Comment by joshuawilson** [comment]
Currently the kubernetes schema is built into the tooling. 
If you want to yaml support for anything else you need to point to the schema for them.

**Comment by JPinkney** [comment]
Also, by auto generation do you mean snippets? Because those come from vscode-kubernetes-tools and not this extension

**Comment by cskalyan** [comment]
For Example, i VS Code when I create a blank YML file with Kubernetes extension and YAML Support Extension enabled  and type POD, Pod template YML file is automatically generated. It works for POD, Deployment, Service, ReplicationController. This automatically generated YML file does not work for other Kube Services like, Ingress, Network Policy, PV,PVClaims.

**Comment by JPinkney** [comment]
All of that functionality is provided by https://github.com/Azure/vscode-kubernetes-tools not this extension. Please file the issue there instead

**Comment by cskalyan** [comment]
Thank you. Closing this issue and opened a new issue at https://github.com/Azure/vscode-kubernetes-tools
