### ISSUE TITLE
Latest version breaks auto-save formatting

### ISSUE THREAD

**Issue by ekristen** [redhat-developer/vscode-yaml#366]
Not sure what happened but with the latest version it stopped honoring the workspace vscode settings.

I have a .vscode/settings.json

```json
{
  "[yaml]": {
    "editor.tabSize": 4,
    "editor.insertSpaces": true
  }
}
```

All files opened are showing 2 spaces instead of 4, when saving it's auto-formats back to 2. 

If I manually change the file back to 4 and save, it does not format back to 4 it stays at 2.

Downgrading to 0.10.1 brings back the expected behavior.

**Comment by JPinkney** [comment]
Can confirm the issue. I think this: https://github.com/redhat-developer/yaml-language-server/pull/305/files PR introduced the formatting issue

**Comment by stefanbuck** [comment]
I'm using the following `.editorconfig` file and saving a file auto-formats the file to 4 spaces. 

```
[*.{yml,json}]
indent_size = 2
```
