### ISSUE TITLE
Kubernetes support seems broken

### ISSUE THREAD

**Issue by phlax** [redhat-developer/vscode-yaml#367]
I have installed the latest version (0.11.0, vscode: 1.49.1, os: debian bullseye)

I then edited the `settings.json` and added the revelant `Kubernetes` (i tried both upper and lower case `k`) entry to the `yaml.schemas` section.

With the plugin installed i get yaml validation, but no auto-completion etc.

I tried adding a different schema ("http://json.schemastore.org/composer") and this works as expected

**Comment by evidolob** [comment]
Hi, I trying to reproduce this and cannot.
On my side autocomplation works:
<img width="783" alt="Screenshot 2020-09-25 at 11 25 34" src="https://user-images.githubusercontent.com/929743/94244757-0967f400-ff22-11ea-8ba7-94899246ffe5.png">

Can you share your settings, under `yaml.schemas` section?

**Comment by phlax** [comment]
yep - heres the full config

```
cat ~/.config/Code/User/settings.json 
{
    "telemetry.enableTelemetry": false,
    "telemetry.enableCrashReporter": false,
    "[yaml]": {
        "editor.insertSpaces": true,
        "editor.tabSize": 2,
        "editor.quickSuggestions": {
            "other": true,
            "comments": false,
            "strings": true
        },
        "editor.autoIndent": "none"
    },
    "yaml.schemas": {
        "kubernetes": ["~/kubernetes-test.yml"],
        "http://json.schemastore.org/composer": ["composer.yaml"]
    },
    "yaml.trace.server": "verbose"
}
```

**Comment by phlax** [comment]
it seems like vscode doesnt like tildes for home path (i thought i had checked this!)

apologies for noise
