### ISSUE TITLE
Consider providing a 'yamlValidation' contribution point for registering a schema

### ISSUE THREAD

**Issue by egamma** [redhat-developer/vscode-yaml#37]
Such a contribution point enables an extension author to contribute a YAML schema association same as is done for JSON and its `jsonValidation` contribution point.

https://code.visualstudio.com/docs/extensionAPI/extension-points#_contributesjsonvalidation

The corresponding code in the JSON extension for this can be found here:
https://github.com/Microsoft/vscode/blob/master/extensions/json/client/src/jsonMain.ts#L174

**Comment by JPinkney** [comment]
Added in 9fdaa7f62f336def2d425f33ff6599db09c80f28!

**Comment by egamma** [comment]
nice!

**Comment by gorkem** [comment]
@JPinkney can you also add some documentation for it ?

**Comment by JPinkney** [comment]
@gorkem Yes, i'll do that now
