### ISSUE TITLE
Example string of type integer gets pasted as int

### ISSUE THREAD

**Issue by Morriz** [redhat-developer/vscode-yaml#371]
When I use autocompletion I get a nice suggestion to use `'1'` (so obviously this entry in examples is a string), but after selecting it it ends up as `1`, giving me an error as the validation spec expects a string.

Maybe this is a vscode problem, but I am reporting here first.

**Comment by evidolob** [comment]
@Morriz can you provide a sample of yaml and schema where you get that behaviour?

**Comment by Morriz** [comment]
I use draft 9 jsonschema, and the part that I use is:
```
...
    examples:
      - '1' # turns up as int after selecting in intellisense popup
      - 200m
```

**Comment by JPinkney** [comment]
You can reproduce with this schema:
```
{
    "type": "object",
    "properties": {
        "env": {
            "type": "integer",
            "default": "1"
        },
        "enum": {
            "type": "string",
            "default": "1"
        }
    }
}
```
when you autocomplete env it will be correct but when you autocomplete enum it will add the integer 1 instead of the string 1
e.g.
```
enum: 1
```
when we want
```
enum: "1"
```

**Comment by Morriz** [comment]
@JPinkney that is another version of this bug but probably caused by the same underlying mechanism?

**Comment by Morriz** [comment]
Sorry for giving yaml example, but that is what we use as source and convert to json. (Would any dev really prefer json over yaml?)

**Comment by Morriz** [comment]
On that note, is it possible to give a yaml file to this extension?

**Comment by JPinkney** [comment]
Yeah it's the same underlying mechanism. For example, I can also reproduce using:
```
properties:
  fooBar:
    type: string
    examples:
      - test
      - "2"
type: object
```

> On that note, is it possible to give a yaml file to this extension?

Yeah it works with both json schemas and yaml schemas as of 0.11.0. This is how I was testing the above example:
```
"yaml.schemas": {
    "my-schema.yaml": "test.yaml"
},
```

**Comment by Morriz** [comment]
Awesome!

**Comment by evidolob** [comment]
@JPinkney I done some investigation on this, and found that YAML doesn't have `number` type, it has only scalar type,
i.e. for yaml point of view `1`, `'1'`, `"1"` is represents same value(string witch contains '1') in different [flow scalar types ](https://yaml.org/spec/1.2/spec.html#id2786942) 
I can change code completion to surround numbers, booleans and `null` values with `"` in case if schema requires string but default value is other than string.
 Or I can improve schema validation, by adding type conventions, i.e. if scheme requires number but we parse string, we will try to convert that string to number and do rest validations. 

WDYT?

**Comment by JPinkney** [comment]
> I can change code completion to surround numbers, booleans and null values with " in case if schema requires string but the default value is other than string.

Yeah, that sounds good to me
