### ISSUE TITLE
Problems and suggested solutions should be marked with plugin-name

### ISSUE THREAD

**Issue by rivy** [redhat-developer/vscode-yaml#373]
Currently, when a value violates schema, suggestions do not mention this as the plugin which enables the warning/error.

For example, an example violation text is `Value is not accepted. Valid values: "${{ matrix.os }}", "macos-latest", "macos-10.15", "self-hosted", "ubuntu-16.04", "ubuntu-18.04", "ubuntu-20.04", "ubuntu-latest", "windows-latest", "windows-2019".(1)`. This makes it difficult to diagnose where such a suggestion is being generated (sometimes needed when the warning is invalid, as here). 

As an example of attribution, the "Code Spell Checker" shows suggestion texts like `"anyy": Unknown word.cSpell`.

A better version here might be `Value is not accepted. Valid values: "${{ matrix.os }}", "macos-latest", "macos-10.15", "self-hosted", "ubuntu-16.04", "ubuntu-18.04", "ubuntu-20.04", "ubuntu-latest", "windows-latest", "windows-2019".(YAML)`.

**Comment by evidolob** [comment]
@rivy We have similar request https://github.com/redhat-developer/yaml-language-server/issues/310

**Comment by rivy** [comment]
@evidolob , Thanks!
