### ISSUE TITLE
Allow array of strings for "fileMatch" in contributes.yamlValidation

### ISSUE THREAD

**Issue by Hofer-Julian** [redhat-developer/vscode-yaml#387]
```contributes.yamlValidation``` mimics ```contributes.jsonValidation``` by allowing the following syntax.
```json
{
  "contributes": {
    "yamlValidation": [
      {
        "fileMatch": "yourfile.yml",
        "url": "./schema.json"
      }
    ]
  }
}
```
```contributes.jsonValidation``` also allows arrays of strings for "fileMatch".
For ```contributes.yamlValidation``` this would look like this:
```json
"yamlValidation": [
      {
        "fileMatch": [
          "yourfile1.yml",
          "yourfile2.yml",
        ],
        "url": "./manifest-schema.json"
      }
    ],
```
Allowing this behaviour would be a nice enhancement and would allow full compatibility to ```contributes.jsonValidation```.

**Comment by JPinkney** [comment]
Closing as PR's have been merged

**Comment by Hofer-Julian** [comment]
Amazing, thanks a lot! 🎉
