### ISSUE TITLE
Autocompletion doesn't work for new list item

### ISSUE THREAD

**Issue by schickling** [redhat-developer/vscode-yaml#39]
Great work on the recent updates and fixes!

I've just discovered another issue when creating a new list item, then the auto-completion just works when writing out the second field:

![do-25](https://user-images.githubusercontent.com/1567498/31629792-ffb956f4-b2b4-11e7-85f6-f120fef6f125.gif)

**Comment by JPinkney** [comment]
Hi, we've just re-released our extension with a fix for this!
