### ISSUE TITLE
[BUG] If blocks don't evaluate properties correctly

### ISSUE THREAD

**Issue by Chagrilled** [redhat-developer/vscode-yaml#393]
## Describe the bug
Unless I'm being super stupid - conditional matching does not work in `"if"` blocks - all conditions seem to be ignored and the `else` block always executes.

## Expected Behavior
If an `"if"`'s condition evaluates to true, it should match the `then` schema

## Current Behavior
The `else` schema is always evaluated.

## Steps to Reproduce

1. Associate this JSON schema with a YAML file:
```json
{
    "$schema": "http://json-schema.org/draft-07/schema",
    "$id": "http://example.com/example.json",
    "type": "object",
    "title": "The root schema",
    "description": "The root schema comprises the entire JSON document.",
    "default": [],
    "properties": {
        "name": {
            "type": "string",
        },
        "var": {
            "type": "string",
        }
    },
    "if": {
        "properties": {
            "var": {
                "type": "string"
            }
        }
    },
    "then": {
        "required": [
            "pineapple"
        ]
    },
    "else": {
        "required": [
            "tomato"
        ]
    },
    "additionalProperties": true
}
```
2. This YAML file:
```yaml
name: aName
var: something
inputs:
```
3. See that the schema is informing that "tomato" is required, when "pineapple" should be required instead, as `var` is quite clearly a string type.

Although this is using JSON - the data is a YAML to JSON conversion - the schema holds true and requires `pineapple` here https://jsonschema.dev/s/PaRXa

## Environment
- [ ] Windows
- [x] Mac
- [ ] Linux
- [ ] other (please specify)

**Comment by chrisy** [comment]
I just narrowed down odd behavior to the same issue. In my case I use a pattern that begins with
```
   "allOf": [
        {
            "$ref": "#/definitions/type"
        },
        {
            "if": {
                "properties": {
                    "type": {
                        "const": "metadata-registry"
                    }
                }
            },
            "then": {
                "$ref": "#/definitions/metadata"
            }
        },
```
to select definitions based on a `type` key in the YAML file. None of them are being selected.

**Comment by evidolob** [comment]
Should be fixed with https://github.com/redhat-developer/yaml-language-server/pull/357

**Comment by Chagrilled** [comment]
Many thanks for such a fast turnaround! How/when will the update from the language server be picked up by this extension?

**Comment by evidolob** [comment]
I start release process, I hope to finish in a few hours.
