### ISSUE TITLE
yaml.schemas setting ignored when editing kubernetes CRD

### ISSUE THREAD

**Issue by indiejames** [redhat-developer/vscode-yaml#408]
## Describe the bug
Setting a schema in yaml.schemas (in my case for argo workflow template schema) seems to have no effect when editing kubernetes custom resource definitions (in my case an argo workflow template). Instead the built in kubernetes schema is applied.

Schema at:
https://raw.githubusercontent.com/argoproj/argo/master/api/jsonschema/schema.json

Sample yaml file:
[test.yaml.txt](https://github.com/redhat-developer/vscode-yaml/files/5705406/test.yaml.txt)

## Expected Behavior
Hovers and autocompletion for argo workflow template tokens (e.g. 'entryPoint') should be available.

## Current Behavior
Only standard kubernetes tokens have autocompletion or hover available.

## Steps to Reproduce

1. Add the following yaml.schema to settings.json
```json

 "yaml.schemas": {
        "https://raw.githubusercontent.com/argoproj/argo/master/api/jsonschema/schema.json": [
            "**/*.yaml"
        ]
    },
```
2. Open an argo workflow template yaml file (see attached)
3. Hover over tokens like 'entryPoint' on line 11

## Environment
- [ ] Windows
- [x ] Mac
- [ ] Linux
- [ ] other (please specify)

**Comment by JPinkney** [comment]
Do you have any other Kubernetes related extensions installed? hovering/completing entrypoint seems to work for me
![Peek 2020-12-16 16-03](https://user-images.githubusercontent.com/8839537/102405940-d466bd00-3fb7-11eb-9722-1ad4a0c229d6.gif)

**Comment by indiejames** [comment]
@JPinkney thanks for looking into this and providing such a detailed response. It turns out you are exactly right - I have the Microsoft Kubernetes extension installed and when I disabled it hovers/autocomplete started working. I'm going to close this ticket. Now I just need to figure out how to get these extensions to play nicely together; the Kubernetes extension is to useful to give up. At worst I guess I can selectively enable/disable them based on what I'm doing at the moment.
