### ISSUE TITLE
Unable to load schema from 'https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json': connect ECONNREFUSED 0.0.0.0:443.

### ISSUE THREAD

**Issue by kzhui125** [redhat-developer/vscode-yaml#410]
Unable to load schema from 'https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json': connect ECONNREFUSED 0.0.0.0:443.

very annoying message, I have to disable this extension.
<img width="1226" alt="2" src="https://user-images.githubusercontent.com/11925432/102951715-77fc2400-4508-11eb-8eb2-dd068a61e3dc.png">

**Comment by JPinkney** [comment]
Please follow the issue template so we can help you with your issue.

**Comment by kzhui125** [comment]
## Expected Behavior
no errors in "PROBLEM"

## Current Behavior
error is shown in "PROBLEM"

## Steps to Reproduce
open docker-compose.yml

## Environment
Mac 10.15.7 VSCode 1.52.1

**Comment by gorkem** [comment]
Is there a proxy issue here? 

@JPinkney I think we should report these schema loading problems as warnings.

**Comment by kzhui125** [comment]
@gorkem In China, there is a connection issue for raw.githubusercontent.com

curl: (7) Failed to connect to raw.githubusercontent.com port 443: Connection refused

Thanks,

**Comment by JPinkney** [comment]
> I think we should report these schema loading problems as warnings.

Yeah we can do that.

>  In China, there is a connection issue for raw.githubusercontent.com

Since there's a connection issue on your side the only thing you can really do is disable the schema store:
```
"yaml.schemaStore.enable": "false"
```

**Comment by kzhui125** [comment]
@JPinkney thanks

**Comment by gorkem** [comment]
Closing, I do not think there is anything else left to do here.
