### ISSUE TITLE
artifacts nto pushed in the right place on download.jboss.org

### ISSUE THREAD

**Issue by apupier** [redhat-developer/vscode-yaml#411]
## Describe the bug

builds are pushed in https://download.jboss.org/jbosstools/vscode/ instead of the subfolders

## Steps to Reproduce

1.
2.
3. 

## Environment
- [ ] Windows
- [ ] Mac
- [ ] Linux
- [ ] other (please specify)

**Comment by JPinkney** [comment]
I've merged the fix (https://github.com/redhat-developer/vscode-yaml/pull/412) and now everything seems to be working: https://download.jboss.org/jbosstools/vscode/snapshots/vscode-yaml/ so I'l close this issue
