### ISSUE TITLE
vscode/jsonschema markdownDescription support seems patchy

### ISSUE THREAD

**Issue by phlax** [redhat-developer/vscode-yaml#417]
## Describe the bug

not entirely clear if this is the correct place to post this issue - but ill start here 8/

vscode has support for a custom jsonschema field `markdownDescription`

when i add a `markdownDescription` field in my custom schema, it works only for hovering not for autocomplete

checking the kubernetes extension and i see something similar - unformatted links when using autocomplete, but correct links when i hover over the value

## Expected Behavior

markdownDescripton should work for both autocomplete and hover

## Current Behavior

markdownDescripton only works for hover

## Steps to Reproduce

1. add a kubernetes yaml file
2. add `metadata`, and then add `name`
3. check the autocomplete on `name` - link in description should be unformatted
4. add name
5. hover, and link in field description should work correctly

## Environment
- [ ] Windows
- [ ] Mac
- [X] Linux
- [ ] other (please specify)

**Comment by JPinkney** [comment]
My guess is that we haven't fully ported over `markdownDescription` for autocompletion from https://github.com/microsoft/vscode-json-languageservice/blob/master/src/services/jsonCompletion.ts yet
