### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by alexaguilar89** [redhat-developer/vscode-yaml#419]
- Issue Type: `Bug`
- Extension Name: `vscode-yaml`
- Extension Version: `0.14.0`
- OS Version: `Windows_NT x64 10.0.21296`
- VSCode version: `1.52.1`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by JPinkney** [comment]
Hi, it seems you have not put any info in this issue. Can you please add a proper title/description
