### ISSUE TITLE
ansible syntax error

### ISSUE THREAD

**Issue by bapi25** [redhat-developer/vscode-yaml#423]
## ansible syntax bad analyses

there is  a surligned code which is correct for ansible but not for this extension vscode-yaml.
{
	"resource": "../main.yml",
	"owner": "_generated_diagnostic_collection_name_#1",
	"severity": 8,
	"message": "Incorrect type. Expected \"string\".",
	"source": "yaml-schema: Ansible 2.9",
	"startLineNumber": 31,
	"startColumn": 7,
	"endLineNumber": 34,
	"endColumn": 3
}

example :
 
![image](https://user-images.githubusercontent.com/58574260/106891115-90a45000-66ea-11eb-9f23-572b08663e5a.png)

how can i leave this extension but deactivate this kind of check that is not relevant?

Thanks in advance
 

## Expected Behavior
no warning or surligned text

## Current Behavior
error message and surligned text in red
message": "Incorrect type. Expected \"string\".",

## Steps to Reproduce

have a list in ansible module "debug" option msg instead of a simple string

## Environment
- [X] Windows
- [ ] Mac
- [ ] Linux
- [ ] other (please specify)

**Comment by ssbarnea** [comment]
I am afraid that linting Ansible is bit outside the scope of YAML extension for multiple reasons including decision about when to use a schema or not and also about the schema itself.

That is why I initiated an extension that will aim to cover ansible bits, one that will reuse vscode-yaml: https://github.com/ansible-community/vscode-ansible -- Be warned that this is in very early stage and I am looking for others to join the effort, especially as my extension development skills are very low.

**Comment by gorkem** [comment]
Closing as [Ansible extension](https://marketplace.visualstudio.com/items?itemName=redhat.ansible) is available on the marketplace and should handle further issues.
