### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by ghost** [redhat-developer/vscode-yaml#434]
- Issue Type: `Bug`
- Extension Name: `vscode-yaml`
- Extension Version: `0.15.0`
- OS Version: `Windows_NT x64 10.0.19042`
- VSCode version: `1.53.2`

:warning: We have written the needed data into your clipboard. Please paste! :warning:
```json 
{
	"messages": [],
	"activationTimes": {
		"codeLoadingTime": 20388,
		"activateCallTime": 33,
		"activateResolvedTime": 1,
		"activationReason": {
			"startup": false,
			"extensionId": {
				"value": "redhat.vscode-yaml",
				"_lower": "redhat.vscode-yaml"
			},
			"activationEvent": "onLanguage:yaml"
		}
	},
	"runtimeErrors": []
}
```

**Comment by JPinkney** [comment]
I'm not sure what this issue is supposed to be reporting? Can you add more info?

**Comment by KinikoYT** [comment]
> 
> 
> I'm not sure what this issue is supposed to be reporting. Can you add more info?

it demands a lot of perfomance and also starts with a little more than a thousand milliseconds late

**Comment by gorkem** [comment]
closing as this should not be an issue after we started packing the extension.
