### ISSUE TITLE
extension fails to load files where path is a symlink

### ISSUE THREAD

**Issue by ssbarnea** [redhat-developer/vscode-yaml#437]
## Describe the bug
I was trying to identify why YAML randomly appears to do nothing on some files and I found the culprit inside the logs:

> [exthost] [error] {"message":"Git error","stdout":"","stderr":"fatal: pathspec '/Users/ssbarnea/c/a/ansible-lint/examples/playbooks/roles/dependency_in_meta/meta/main.yml' is beyond a symbolic link\n","exitCode":128}

Basically any YAML file that has a path that includes a symlink is ignored due an error like the one above. This happens even if the resolved symlink is a git tracked file inside the same repository. 

I my case I have a symlink pointing `playbooks/roles` to `../roles`. At vscode lists both location in the file-tree, if you open the one with the symlink you do not get any validation. If you open the normal file it works.

As many people are using symlinks, especially in Ansible repositories, we need to assure the validation works regarding how the file was opened.

The error message does not give a lot of insights regarding where it comes from so I am not sure how to propose fix (likely a normalization of the file path).

**Comment by evidolob** [comment]
@ssbarnea I cannot reproduce this issue:

https://user-images.githubusercontent.com/929743/108722252-993eb800-752b-11eb-9f72-e5a6bda79433.mov

Can you check how you map schema to file? I mean that your mapping is not contains file path.

**Comment by ssbarnea** [comment]
Here is a dump my current schemas, the ones I found the issue with were the ones with full https url.
```
  "yaml.schemas": {
    "https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json": "docker-compose.yml",
    "./zuul.json": "/.zuul.yaml",
    "https://raw.githubusercontent.com/ansible-community/ansible-lint/schemas/src/ansiblelint/data/ansible-requirements-schema.json": ["**/requirements.yml"],
    "https://raw.githubusercontent.com/ansible-community/ansible-lint/schemas/src/ansiblelint/data/ansible-meta-schema.json": ["**/meta/main.yml"],
    "https://raw.githubusercontent.com/ansible-community/ansible-lint/schemas/src/ansiblelint/data/ansible-vars-schema.json": ["**/vars/*.yml", "**/defaults/*.yml", "**/host_vars/*.yml", "**/group_vars/*.yml"],
    "https://raw.githubusercontent.com/ansible-community/ansible-lint/schemas/src/ansiblelint/data/ansible-tasks-schema.json": ["**/tasks/*.yml", "**/handlers/*.yml"],
    "https://raw.githubusercontent.com/ansible-community/ansible-lint/schemas/src/ansiblelint/data/ansible-playbook-schema.json": ["**/playbooks/*.yml"],
  },
```

I will try to create new empty project with a minimal reproducing case and do some testings with minimal number of extensions. I suspect that error may appear from another extension.

**Comment by evidolob** [comment]
> I suspect that error may appear from another extension.

Yes it can be, as yaml ext does nothing with git, and you provide error message with `"Git error"`

**Comment by ssbarnea** [comment]
I think that this message was a redherring because I seen others encounteing it https://github.com/jaredly/reason-language-server/issues/436 and with my test project I got it repeated like 10 times when vscode starts and one of these files is opened. 

Even with this message present, schema validation for docker-compose.yml appears to be working.
