### ISSUE TITLE
Other Schemas are being ignored

### ISSUE THREAD

**Issue by nglara** [redhat-developer/vscode-yaml#44]
Hi,

I came to a point where I needed to create multiple schemas for each group of my YAML files. I'm not sure if this is an issue but I could not find a way to make the extension use my schemas to validate my YAML files. I got 2 types of files and each of them has it's own schema.

Here is my scenario:

**In my settings.json:**

    "yaml.schemas": {
        "./transport.schema.json": "/*.transport",
        "./credential.schema.json": "/*.credential"
    }

**My YAML files are:**
1. train.transport
2. author.credential

The extension validates my author.credential against my credential.schema.json but ignoring my train.transport. I'm assuming it only remembers the last item from the list schemas.

I downloaded and debugged the source and found out that the server.js -> configureSchemas method returns a languageSettings that is being used by server.js -> updateConfiguration which overrides the first one.

I made a temporary fix just so I can make it to use all my schemas to validate my YAML files accordingly. 

**server.js -> updateConfiguration()**

```
	languageSettings.schemas = configureSchemas(uri, schema.fileMatch, schema.schema,
 languageSettings.schemas);

```

**server.js -> configureSchemas(uri, fileMatch, schema, schemas)**

```
	if (schema === null) {
		schemas.push({ uri, fileMatch: fileMatch });
	}
	else {
		schemas.push({ uri, fileMatch: fileMatch, schema: schema });
	}

```
I don't want to push my fix for I know there is more elegant way to fix the issue. 

Please let me know. Thanks.

**Comment by JPinkney** [comment]
Hi! I've just fixed this in the latest release.

**Comment by nglara** [comment]
That is fast! Thank you.
