### ISSUE TITLE
$schema prop

### ISSUE THREAD

**Issue by johngeorgewright** [redhat-developer/vscode-yaml#440]
## Summary

Out of the box, VSCode will validate against whatever schema is referenced in a JSON document's `$schema` property; whether that is from a remote URL or a path relative to the JSON file.

Is there anything in the roadmap to feature the same in `vscode-yaml`?

## Relevant information

<figure>
<figcaption>Here's an example of VSCode using a relative schema (with the <code>$schema</code> prop)</figcaption>
<img width="1003" alt="VSCode with 2 open editors side by side." src="https://user-images.githubusercontent.com/1423566/109939123-a7799a80-7cc8-11eb-969d-267db32dd777.png">
</figure>

I found  the option to reference the schema from a comment at the top of a YAML file, but I can't seem to get that to work very nicely with local schemas.

<figure>
<figcaption>... I've tried using a path relative to the root:</figcaption>
<img width="1156" alt="Screenshot 2021-03-03 at 22 56 21" src="https://user-images.githubusercontent.com/1423566/109939125-a8123100-7cc8-11eb-9d8c-9377896a8b33.png">
</figure>

<figure>
<figcaption>... and I've tried relative to the file:</figcaption>
<img width="1156" alt="Screenshot 2021-03-03 at 22 57 01" src="https://user-images.githubusercontent.com/1423566/109939128-a8aac780-7cc8-11eb-8312-a0ae1913d11f.png">
<img width="1158" alt="Screenshot 2021-03-03 at 22 57 07" src="https://user-images.githubusercontent.com/1423566/109939130-a9435e00-7cc8-11eb-8a94-eb7f34bb1de2.png">
</figure>

Even if I got one of the above options to work, the comment would be stripped out if I were to convert the YAML file to JSON, so doesn't quite suite my needs anyway 😞 .

**Comment by evidolob** [comment]
We already have a PR which add this, but work not finished, see https://github.com/redhat-developer/yaml-language-server/pull/354#pullrequestreview-536163814

**Comment by johngeorgewright** [comment]
Great news. Thanks.
