### ISSUE TITLE
Schema error on pubspec.yaml on version 0.16.0

### ISSUE THREAD

**Issue by Vayth** [redhat-developer/vscode-yaml#444]
## Describe the bug

When I open a file named `pubspec.yaml` in Linux (WSL) using version `0.16.0`, I got an error in the problem window. I have tried the following scenario and the bug only happens in that specific one.
- :x: Linux (WSL) version `0.16.0`, named `pubspec.yaml`
- :heavy_check_mark: Linux (WSL) version `0.15.0`, named `pubspec.yaml`
- :heavy_check_mark: Linux (WSL) version `0.16.0`, named `pubspecs.yaml`
- :heavy_check_mark: Linux (WSL) version `0.16.0`, named `pubspec.yml`
- :heavy_check_mark: Windows, version `0.15.0`
- :heavy_check_mark:Windows, version `0.16.0`

![image](https://user-images.githubusercontent.com/41632555/110747501-10d14e80-8271-11eb-91a1-5f346096dc59.png)

## Expected Behavior

No error message

## Current Behavior

Got error message: `Unable to load schema from 'https://json.schemastore.org/pubspec': No content`

## Steps to Reproduce

1. Open VSCode in Linux (WSL)
2. Use extension version `0.16.0`
3. Create a file named `pubspec.yaml`

## Environment
- [ ] Windows
- [ ] Mac
- [X] Linux (through WSL, haven't tried on real Linux)
- [ ] other (please specify)

**Comment by evidolob** [comment]
@Vayth Can you test another yaml file on WSL? Unfortunately, I doesn't have Windows OS to test. 
I just want to figure out, is this problem only for `pubspec.yaml` or we have problem with loading JSON Schemas on WSL.

**Comment by Vayth** [comment]
I tried other files on WSL like those I wrote in bug description and it happens only when the name is `pubspec.yaml`.

Other yaml files in my project also appear to be fine: `azure-pipelines.yml` from Azure Pipeline, `analysis_options.yaml` from pub.dev lint package, also my randomly created `pubspecs.yaml` and `pubspec.yml` for this test. All of them are fine.

Only file named `pubspec.yaml` has this issue, both when I created manually or the one generated by `flutter create` from Flutter.

**Comment by franzbischoff** [comment]
Same error for GitHub actions: `Unable to load schema from 'https://json.schemastore.org/github-workflow': No content`

I reverted to the last version and it works.

**Comment by LeMimit** [comment]
Hello, I got the same error as described here with a `docker-compose.yml` file.

I am on Ubuntu `20.04 LTS` with WSL 2 and VS Code `1.54.3` . I am using the `Remote - WSL` `v0.54.6` to see the files from WSL on VS Code.

```
Unable to load schema from 'https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json': No content.
```

The error is on `0.16.0`, but when I am downgrading to `0.15.0` the error disappears. Since like a regression.

Tell me If I can give more information to help fix this bug!

**Comment by evidolob** [comment]
@LeMimit @Vayth 
I made some test and your cases works for me:
![Screenshot 2021-03-23 175337](https://user-images.githubusercontent.com/929743/112176837-1cbdf880-8c01-11eb-9bce-0b92fcf8a6e8.png)

The only thing I can suggest is to check Windows firewall settings, and make sure that you allow connections from wsl.
Other check is to run `wget https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json` from WSL terminal.

**Comment by Vayth** [comment]
I tried `wget https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json` and I can download it just fine.
```
:~$ wget https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json
--2021-03-24 14:45:05--  https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.109.133, 185.199.111.133, 185.199.108.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.109.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 25738 (25K) [text/plain]
Saving to: ‘compose-spec.json’

compose-spec.json             100%[=================================================>]  25.13K  --.-KB/s    in 0.06s

2021-03-24 14:45:05 (402 KB/s) - ‘compose-spec.json’ saved [25738/25738]
```

Are you using `0.16.0` on your WSL vscode environment in your test?

**Comment by evidolob** [comment]
@franzbischoff Yes, I'm using `0.16.0`

Could you test `wget https://json.schemastore.org/pubspec`?

**Comment by franzbischoff** [comment]
It seems to be working now. Magically :-)

Thanks

**Comment by LeMimit** [comment]
Hello, I did not touch anything and it is working now. I have no clue why. May be the site hosting the schema had problems ?

**Comment by Vayth** [comment]
weird.. Mine is not fixed yet..
Seems like it detect that `name` is missing correctly, but the previous error is still there.
![image](https://user-images.githubusercontent.com/41632555/112420284-8ce29080-8d5f-11eb-9c1e-7f1788c68b39.png)
