### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by tasyaagnesgoei** [redhat-developer/vscode-yaml#450]
- Issue Type: `Bug`
- Extension Name: `vscode-yaml`
- Extension Version: `0.16.0`
- OS Version: `Windows_NT x64 10.0.19042`
- VSCode version: `1.54.3`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by evidolob** [comment]
@tasyaagnesgoei  Can you add more info?

**Comment by gorkem** [comment]
closing as not enough information is present
