### ISSUE TITLE
GitHub Action runs-on self hosted runner issue

### ISSUE THREAD

**Issue by reintroducing** [redhat-developer/vscode-yaml#456]
## Summary
Hello, I'm writing a GH Action that has a self hosted runner defined.
```
runs-on: selfhosted-fe-platform
```
This produces the following issue:
<img width="590" alt="Screen Shot 2021-03-18 at 7 50 08 AM" src="https://user-images.githubusercontent.com/259901/111646092-977cb300-87be-11eb-83ff-62dd890abd25.png">

The name of the self hosted runner is throwing a lint error. What's the best way to rectify this? Thank you.

## Relevant information
Latest version of plugin (just installed today). MacOS Catalina 10.15.7

**Comment by evidolob** [comment]
@reintroducing According to [doc](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#self-hosted-runners) value of `runs-on` should be `self-hosted`.

**Comment by reintroducing** [comment]
@evidolob i had read that but did not realize the proper usage (first foray into self hosted runners) and i was not sure how to specify the proper runner (if you have many), but, this seems to do the trick:
```
runs-on: [self-hosted, selfhosted-fe-platform]
```

Thank you!
