### ISSUE TITLE
Autocompletion not triggered while typing

### ISSUE THREAD

**Issue by fbricon** [redhat-developer/vscode-yaml#46]
Currently, autocompletion is only triggered when doing `ctrl+space`. I'm used to being spoiled by VS Code, which triggers autocompletion on each keystroke (see Java)

**Comment by rcjsuen** [comment]
According to the [changelog](https://github.com/redhat-developer/vscode-yaml/blob/62b2c1e84fda1931736f8da2a867b10a20beff16/CHANGELOG.md), this has been fixed. Should this be closed?

**Comment by fbricon** [comment]
Yup, works for me, nice job @JPinkney :-)
