### ISSUE TITLE
Doesn't load github actions yaml despite good URL

### ISSUE THREAD

**Issue by brandonh-msft** [redhat-developer/vscode-yaml#467]
## Describe the bug

I'm getting an error in my designer that I don't recall happening before now:
~~~
Unable to load schema from 'https://json.schemastore.org/github-workflow.json': No content.
~~~

when working with Github Actions workflow definitions. I checked that URL via my browser and it loads just fine.

## Expected Behavior
It should load the schema from that URL w/o issue

## Current Behavior
Error pops and no schema/autocomplete is loaded

## Steps to Reproduce

1. Edit a GitHub Actions workflow file in the `.github/workflows/*.yaml` location of your workspace

## Environment
- [x] Windows

**Comment by evidolob** [comment]
Duplicate https://github.com/redhat-developer/vscode-yaml/issues/462

**Comment by brandonh-msft** [comment]
> Duplicate #462

Thanks! closed.
