### ISSUE TITLE
YAML extension requires VSCode v1.52 minimum, since v0.16.0

### ISSUE THREAD

**Issue by fbaligand** [redhat-developer/vscode-yaml#471]
Although `package.json` tells that vscode required version is 1.31.0, YAML extension doesn't work with vscode versions < 1.52.
This issue happens since YAML extension v0.16.0.

For example, with version v0.15.0, I can use the YAML extension successfully in vscode v1.39.
But YAML extension v0.16.0 or v0.17.0 does not work on older vscode versions than v1.52 (I tested with several versions, including v1.51.1).

So is it a build bug? Is it a new requirement with latest versions?

**Comment by evidolob** [comment]
@fbaligand It not exactly a bug. To implement  https://github.com/redhat-developer/vscode-yaml/issues/174 we need to get latest LSP version, and it seems that LSP client requires at least v1.52 VSCode version.
We need to change supported version of VSCode in `package.json`.

**Comment by fbaligand** [comment]
Thanks for the explanation

**Comment by fbaligand** [comment]
Thanks for the package.json fix.
