### ISSUE TITLE
unknown tag <!secret> error

### ISSUE THREAD

**Issue by EricGardien** [redhat-developer/vscode-yaml#476]
Issue Type: <b>Bug</b>

Hi,
the extension YAML reports an error with this line of code:
 
password: !secret secret_id

Error reported is "unknown tag <!secret>"

This tag is used in the configuration.yaml of Homeassistant  to segregate passwords from the public file configuration.yaml,
More on this https://www.home-assistant.io/docs/configuration/secrets/

Best regards,
Eric

Extension version: 0.17.0
VS Code version: Code 1.55.1 (08a217c4d27a02a5bcde898fd7981bda5b49391b, 2021-04-07T15:06:02.360Z)
OS version: Windows_NT x64 10.0.19041

**Comment by evidolob** [comment]
@EricGardien You need to provide tag definition with https://github.com/redhat-developer/vscode-yaml#adding-custom-tags
as `secret` tag is not defined.

**Comment by rbpltr** [comment]
Something seems to have changed/broken between `0.16.0` and `0.17.0`. I cannot get `customTags` to work in `0.17.0`. They were working fine in `0.16.0` (and continue to work fine if I downgrade).

**Comment by evidolob** [comment]
Yes, that was a bug https://github.com/redhat-developer/vscode-yaml/issues/461
Fix will be included in next release.

**Comment by evidolob** [comment]
@EricGardien @rbpltr Is this issue fixed for you?

**Comment by rbpltr** [comment]
Yes. Working since `0.18.0`. Thank you.
