### ISSUE TITLE
Warning: Resource scoped settings are accessed without a resource

### ISSUE THREAD

**Issue by egamma** [redhat-developer/vscode-yaml#478]
From the `Output>Log (Extension Host)`:
```
[2021-04-12 11:45:58.727] [exthost] [warning] [redhat.vscode-yaml] Accessing a resource scoped configuration without providing a resource is not expected. To get the effective value for '[yaml]', provide the URI of a resource or 'null' for any resource.
```
To fix pls review where you access the configuration settings and verify that you pass in a resource when the scope of the setting is `resource`. See the scope section in https://code.visualstudio.com/api/references/contribution-points#Configuration-schema

There also is a sample that illustrates this https://github.com/microsoft/vscode-extension-samples/tree/main/configuration-sample

**Comment by evidolob** [comment]
Related to https://github.com/redhat-developer/yaml-language-server/issues/327

**Comment by ssbarnea** [comment]
I still see this warning using version 1.2.2 of the extension so I suspect that it was not fully fixed or a regression happened.

Also the message is quite unclear and I do not know how to avoid it or if there are other undesired side-effects from it.

**Comment by crystalfp** [comment]
Still present in 1.7.0
What could I do to help diagnose the problem?
Apparently it has no consequence on using yaml files

**Comment by bjtho08** [comment]
@msivasubramaniaan Maybe someone should be assigned to this issue and get it reopened until it is confirmed to be completed.

**Comment by robinmalik** [comment]
Still present with version 1.18.0.
