### ISSUE TITLE
Does not seem to validate objects that are part of an array property

### ISSUE THREAD

**Issue by nglara** [redhat-developer/vscode-yaml#48]
Hi, I have been testing this but could not make it to work. I designed my schema to have locations (array) and each location has Sequence and Address.

The extension does not seem to validate the Address object against my schema. I have 2 issues.

1. The Sequence property must be a numeric but it allows me to put string.
2. Under my Address object, I set the **additionalProperties** to false but it's still allow me to add **line3**.

Schema:

```
{
    "version": "1.0.0",
    "name": "Sample",
    "type": "object",
    "additionalProperties": false,
    "required": [
        "name",
        "locations"
    ],
    "properties": {
        "name": {
            "type": "string"
        },
        "locations": {
            "type": "array",
            "required": [
                "sequence",
                "address"
            ],
            "properties": {
                "sequence": {
                    "type": "integer"
                },
                "address": {
                    "type": "object",
                    "additionalProperties": false,
                    "properties": {
                        "line1": {
                            "type": "string"
                        },
                        "line2": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    }
}
```

YAML file:

```
name: sample
locations:
- sequence: this should be an integer
  address:
    line1: a
    line2: b
    line3: this should not be permitted
```

**Comment by JPinkney** [comment]
Hi, I've investigated the issue and it looks like its because the schema does not comply with the [jsonschema specification](http://json-schema.org/latest/json-schema-validation.html#rfc.section.6.4). I've done a [gist](https://gist.githubusercontent.com/JPinkney/834c1cc02617f80bc8ec06cb326cf00a/raw/42bf18cf71cc64e024ac357961e5bd1b0d98179f/temp-schema.json) that meets the jsonschema specification and everything is working!

**Comment by nglara** [comment]
My bad. I totally did not pay attention to that "items" property. Thank you for your help.
