### ISSUE TITLE
Deploy to Azure extension is incompatible with VSCode-YAML. Please uninstall it.

### ISSUE THREAD

**Issue by t2kx** [redhat-developer/vscode-yaml#483]
seems the YAML parser is conflicting with the https://github.com/microsoft/vscode-deploy-azure extension. Who needs to fix this?
I also opende an issue on https://github.com/microsoft/vscode-deploy-azure/issues/218

**Comment by JPinkney** [comment]
They have to fix it on their side. Both this extension and that extension start the YAML language server, but the YAML language server should only be started by VSCode-YAML. Otherwise you'll get things like duplicate hover results, duplicate autocompletion, etc, etc

**Comment by gorkem** [comment]
Closing as this should be handled somewhere else.
