### ISSUE TITLE
support .yml formatting by default

### ISSUE THREAD

**Issue by blackliner** [redhat-developer/vscode-yaml#484]
### Is your enhancement related to a problem? Please describe.

When trying to format a file ending in `yml`, VScode shows a warning, although this plugin is installed:
![image](https://user-images.githubusercontent.com/23190927/115258439-494a2f00-a131-11eb-99c7-b3f745003a1c.png)

### Describe the solution you would like

I would like this plugin to support `yml` files out of the box, as it does with `yaml` files

### Describe alternatives you have considered

- Changing the file ending to `yaml` will make the formater work, but disables other extensions (in my case docker-compose)
- Adding `*.yml --> yaml` to the settings `Files: Associations` will also disable other extensions (in my case docker-compose)
![image](https://user-images.githubusercontent.com/23190927/115258898-afcf4d00-a131-11eb-895b-63d574e4419c.png)

### Additional context

I am lazy and want stuff to work out of the box 😪

**Comment by blackliner** [comment]
On a second look, it might also be the case that `docker` and `yaml` are both fighting for the associated file type 🤔

**Comment by JPinkney** [comment]
> On a second look, it might also be the case that docker and yaml are both fighting for the associated file type thinking

Yeah I think that's probably the case. My guess is that the docker extension changes the file association for docker compose files and that's why it doesn't find the yaml formatter

**Comment by rgeorgiev583** [comment]
I think this problem will be solved if someone registers this extension as a formatter for `dockercompose` files.  This is currently not the case, which explains the `There is no formatter for 'dockercompose' files installed.` warning message.

**Comment by blackliner** [comment]
> I think this problem will be solved if someone registers this extension as a formatter for `dockercompose` files. This is currently not the case, which explains the `There is no formatter for 'dockercompose' files installed.` warning message.

@rgeorgiev583  Can this be done manually, or only from within the expansion itself?

**Comment by rgeorgiev583** [comment]
@blackliner I think it's only possible from the extension itself.  We need to invoke this method: https://code.visualstudio.com/api/references/vscode-api#languages.registerDocumentFormattingEditProvider

**Comment by gorkem** [comment]
I do not think we can keep up with the many file patterns that use YAML.  I am closing this as `wont-fix`
