### ISSUE TITLE
Prioritize schema selection from schemastore to be used

### ISSUE THREAD

**Issue by GerryFerdinandus** [redhat-developer/vscode-yaml#488]
### Is your enhancement related to a problem? Please describe.
When I open .github/workflows/deploy.yml
It give error because the wrong schema is active

Both filematch from schemastore are true for .github/workflows/deploy.yml
".github/workflows/**.yml"
"deploy.yml"

### Describe the solution you would like
Only filematch with the highest priority should be selected.
In this case ".github/workflows/**.yml"

This priority is based on how many the directory level "/" are present
and/or length of filematch. 

IntelliJ IDE does not have this issue.
They correctly select ".github/workflows/**.yml"

**Comment by evidolob** [comment]
Related to https://github.com/redhat-developer/yaml-language-server/issues/422

**Comment by GerryFerdinandus** [comment]
@evidolob   redhat-developer/yaml-language-server#422 need to be fix first.
If there are two or more conflicting filematch for different schema that are true.
Which one is selected?
Is there already a build in prioritize algorithm present?

**Comment by evidolob** [comment]
We have one, but it prioritize only schemas prowided with `yaml.schemas` configuration https://github.com/redhat-developer/yaml-language-server/issues/250

**Comment by GerryFerdinandus** [comment]
Thanks for the link.
There is already some prioritize 

> Then schema store schemas would be priority 3 and are only used if nothing else matches.


What need to be added is prioritize for within schemastore conflict
Hopefully there will be some fix/improvement in the future.

**Comment by GerryFerdinandus** [comment]
Just tested with the latest 0.19.0
rename my workflow to .github/workflows/deploy.yml
There is no more error any more.
This specific issue can be closed.

**Comment by davetapley** [comment]
This is happening again with `deploy.yml` in 1.6.0, it's fine in 1.5.1 😑

**Comment by tzq0301** [comment]
This is happening again with deploy.yml in 1.14.0
