### ISSUE TITLE
Hover does not work with kubernetes yaml

### ISSUE THREAD

**Issue by SteveCurran** [redhat-developer/vscode-yaml#49]
I maybe missing something. Does the language server alone support descriptions on hovering or is there something else I need?

**Comment by JPinkney** [comment]
In the case of the kubernetes yaml, unfourtunately there isn't yet hover descriptions for that schema. The schema is generated using [this](https://github.com/fabric8io/kubernetes-model) and that outputs [this generated schema](http://central.maven.org/maven2/io/fabric8/kubernetes-model/2.0.0/kubernetes-model-2.0.0-schema.json). Once the schema has the description field filled out then hover support will work for that schema.

For other schemas, as long as the description field is filled out in the schema, hover support works.

**Comment by JPinkney** [comment]
Great news, we just updated the schema in our 0.0.9 version with one that includes hover!
