### ISSUE TITLE
How can I disable yaml schema for space yaml file?

### ISSUE THREAD

**Issue by szyhf** [redhat-developer/vscode-yaml#491]
## Summary

Our server has an yaml file named `cluster.yml`, it's for our server only, but yaml think it's config for rke-cluster, and warn as blow: 

```txt
Property Register is not allowed.yaml-schema: https://raw.githubusercontent.com/dcermak/vscode-rke-cluster-config/main/schemas/cluster.yml.json
```

I never install the vscode-ext `vscode-rke` 

It looks like the vscode config `yaml.schemas` can control it but I don't know how to set a "no schema":

eg:

```json
"yaml.schemas": {
		"": "cluster.yaml",
	},
```

Really thinks for help.

**Comment by henrahmagix** [comment]
I have the exact same issue. I think this is related to https://github.com/redhat-developer/vscode-yaml/issues/245 where I am also having odd detection of a yaml file and would like to disable detection for that file, like setting it to a blank schema.

**Comment by henrahmagix** [comment]
@szyhf I've been able to accomplish this with an empty schema file, either locally or in some absolute directory, e.g.
```json
"yaml.schemas": {
  ".empty_schema.json": [
    "ignore/these/files/*.yml"
  ]
}
```
where `.empty_schema.json` is a file with the following contents:
```json
{}
```

**Comment by szyhf** [comment]
> @szyhf I've been able to accomplish this with an empty schema file, either locally or in some absolute directory, e.g.
> 
> ```json
> "yaml.schemas": {
>   ".empty_schema.json": [
>     "ignore/these/files/*.yml"
>   ]
> }
> ```
> 
> where `.empty_schema.json` is a file with the following contents:
> 
> ```json
> {}
> ```

Really thanks!!

**Comment by evilensky** [comment]
@henrahmagix Do you know how one might set it for an entire vs-code installation; that is, avoid creating `.empty_schema.json` in multiple repositories?

**Comment by henrahmagix** [comment]
@evilensky sure :) I’ve saved the empty file in my home directory, and then used an absolute path to that file, so the setting works in every project :)
