### ISSUE TITLE
False CircleCI validation on `setup_remote_docker` step with subelements

### ISSUE THREAD

**Issue by Dominik-K** [redhat-developer/vscode-yaml#51]
Suddenly your extension supports CircleCI's `config.yml`. Pretty good 👍 

I found this false validation error:

![vscode_circleci-validation_error](https://user-images.githubusercontent.com/5795847/33712444-c9d1f634-db47-11e7-8fab-663c15607af2.png)

(for search: `setup_remote_docker` step is red underlined if subelements are added. Hint shows: `Value is not accepted. Valid values: "checkout", "setup_remote_docker"`)

What is the correct repository to report this issue?
A full text search for `circleci` didn't return any results neither in this repo ("vscode-yaml") nor in the underlying [yaml-language-server](https://github.com/redhat-developer/yaml-language-server).

**Comment by gorkem** [comment]
We use [schemasore](http://schemastore.org/json/) to automatically resolve json schemas whenever we can. You can report or fix this on [schemastore repo](https://github.com/schemastore/schemastore/)

**Comment by Dominik-K** [comment]
@gorkem Thanks for your fast answer.

**Comment by JPinkney** [comment]
I'm going to close this because there is now an issue in the schema store https://github.com/SchemaStore/schemastore/issues/378
