### ISSUE TITLE
Editor: Schema link does not work when schema is a local file

### ISSUE THREAD

**Issue by Ark-kun** [redhat-developer/vscode-yaml#513]
## Describe the bug

There is a schema link above the editor window. When the schema is a local file, clicking on the link leads to error: `Cannot Load content for: A:\<some path>\components.json_schema.json. Unknown schema: 'A'`

## Expected Behavior
I expect that the schema link works fine when the schema is a local file.

## Current Behavior
`Cannot Load content for: A:\<some path>\components.json_schema.json. Unknown schema: 'A'`

## Steps to Reproduce
1. Add schema from a local file:
```
    "yaml.schemas": {
        "A:\\<some path>\\components.json_schema.json": "component.yaml"
    }
```
2. Create file called `component.yaml`
3. In the editor click on the `components.json_schema.json` line above the first line.

## Environment
- [x] Windows
- [ ] Mac
- [ ] Linux
- [ ] other (please specify)

**Comment by alkuzad** [comment]
Using file URI is workaround, some examples:

`file:///C:\\Users\\dawid.goslawski\\schema.json`
`file://localhost/c$/Users/dawid.goslawski/schema.json`

@evidolob I've seen you are quite strictly bound to XHR and http/https api, maybe just change documentation ?

**Comment by evidolob** [comment]
Hm, I think it would be better to improve schema mappings to support windows paths.
