### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by hprabowo19** [redhat-developer/vscode-yaml#514]
- Issue Type: `Bug`
- Extension Name: `vscode-yaml`
- Extension Version: `0.19.0`
- OS Version: `Windows_NT x64 10.0.19041`
- VS Code version: `1.56.2`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by evidolob** [comment]
@hprabowo19 Could you provide more info about your problem?
