### ISSUE TITLE
Temporarily revert the Telemetry feature

### ISSUE THREAD

**Issue by fbricon** [redhat-developer/vscode-yaml#515]
### Is your enhancement related to a problem? Please describe.
The vscode-commons dependency [irks](https://marketplace.visualstudio.com/items?itemName=redhat.vscode-commons&ssr=false#review-details) some users.

### Describe the solution you would like
Before the latest release is fully rolled out, we should revert the change ASAP and try to find an alternative to the currently correct technical solution.

### Describe alternatives you have considered
Simply removing the vscode-commons dependency might cause some runtime errors, it seems safer to rollback telemetry as a whole for now.

**Comment by evidolob** [comment]
I can remove dependency, and make sure that vscode-yaml will work without vscode-commons.

**Comment by fbricon** [comment]
Telemetry will be back!

**Comment by spirillen** [comment]
SpyWare, uninstalled...

**Comment by fbricon** [comment]
@spirillen VS Code implements telemetry collection by default, you have to explicitly opt-out.  
On the other hand, Red Hat extensions implement telemetry collection as an anonymous (as in no personally identifiable data, not even IP address is collected), opt-in process, so no data is collected until you explicitly agree. 

And vscode-yaml is currently not implementing telemetry collection.
