### ISSUE TITLE
Restricted Mode support

### ISSUE THREAD

**Issue by ak1394** [redhat-developer/vscode-yaml#535]
Is there any plans to allow the extension to work in the untrusted workspaces?

**Comment by evidolob** [comment]
@ak1394 Do you mean  https://github.com/redhat-developer/vscode-yaml/issues/500 ?
If so, then yes, we plan to include that in next release

**Comment by ak1394** [comment]
Ah, yes! I overlooked that ticket. Do you plan to simple declare support for untrusted workspaces? I.e. 

```json
"capabilities": {
  "untrustedWorkspaces": {
    "supported": true
  }
}
```

There is not much details how are you going to handle it in #500

**Comment by evidolob** [comment]
Yes, as we not execute any code, I don’t  see any  reason  why  we can’t  support  untrusted workspaces.

**Comment by ak1394** [comment]
Sounds great! Will keep an eye on #500 !
