### ISSUE TITLE
How can I set specific ansible linter rules to be ignored

### ISSUE THREAD

**Issue by silviuvulcan** [redhat-developer/vscode-yaml#541]
## Summary
I searched the issues and google and couldn't find an example on how to ignore specific lint rules for ansible. I already have .yamllint and .ansible-lint files but they seem to be ignored.

## Relevant information

Specifically I want the "line too long" rule to be ignored (it should already be for ansible vars but it's not). Where can I add the exception ?

**Comment by JPinkney** [comment]
Can you show a screenshot of this issue? Are you using any other Ansible VSCode extensions? AFAIK this extension doesn't throw a line too long line error

**Comment by silviuvulcan** [comment]
Your comment sent me on the right track. You are of course correct. I also had zbr.vscode-ansible installed and that was producing the error. I was sure I removed everything but this extension but obviously missed this one.

Thanks!
