### ISSUE TITLE
package.json give the wrong auto completion/suggestion

### ISSUE THREAD

**Issue by GerryFerdinandus** [redhat-developer/vscode-yaml#546]
## Describe the bug
Auto completion show items that does not belong to the package.json schema

## Expected Behavior

Auto completion/suggestion should show the correct items.
(See screen shot attachment Clion IDE as example)

## Current Behavior

It show "badges" as a selection option.
But "badges" is not part of package.json schema
(See screen shot attachment VS code.) 

## Steps to Reproduce

1. Create empty package.json file with a double quotes => { "" }
2. put the cursor between the double quotes "" 
3. Press ctrl-space to activate auto-completion/suggestion
4. "badges" is wrongfully shown in the list
 

## Environment
- [ ] Windows
- [ x] Mac
- [ ] Linux
- [ ] other (please specify)

Note there is "badges" is present in [vss-extension.json](https://github.com/SchemaStore/schemastore/blob/master/src/schemas/json/vss-extension.json) but not in [package.json](https://github.com/SchemaStore/schemastore/blob/master/src/schemas/json/package.json)
There is also "activationEvents" I do not know where that is coming from.

VS code show wrong items list.
![VS Code](https://user-images.githubusercontent.com/6232089/124171816-511b3d80-daa9-11eb-9d5b-54f08ed3ac12.png)

Clion IDE show the correct items list.
![Clion](https://user-images.githubusercontent.com/6232089/124171823-52e50100-daa9-11eb-853c-9ceebf34aec8.png)

**Comment by evidolob** [comment]
@GerryFerdinandus This extension is for `yaml` files, not for `json`. 
If you think that vscode does something wrong, you can create an issue in https://github.com/microsoft/vscode
