### ISSUE TITLE
Intelesense for variable names not working

### ISSUE THREAD

**Issue by destinio** [redhat-developer/vscode-yaml#554]
Issue Type: <b>Bug</b>

Has prevented me from intelesensing variable names. At-least in javascript, React, Typescript

Extension version: 0.21.0
VS Code version: Code 1.58.0 (2d23c42a936db1c7b3b06f918cde29561cc47cd6, 2021-07-08T06:54:17.694Z)
OS version: Darwin x64 19.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|8, 5, 3|
|Memory (System)|64.00GB (35.62GB free)|
|Process Argv|. --crash-reporter-id 3159340f-e339-41df-9563-e655b177d3e7|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspyt653:30270858
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30311712
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255:30335481
vscod805:30301674
pythonvspyt200:30331937
vscextlang:30333561
binariesv615:30325510
bridge0708:30335490

```

</details>

**Comment by evidolob** [comment]
@destinio Hi, this extension doesn’t do anything  with JS, TS or React. It is YAML only.
 Could you provide more description on issues that you face with vscode-yaml?

**Comment by destinio** [comment]
So, VSCode updated this morning for me, and all of a sudden I could not Intelesense variable names 🤷‍♂️

I ran [extension-bisect](https://code.visualstudio.com/blogs/2021/02/16/extension-bisect) and `redhat.vscode-yaml` came up as the culprit 🧟‍♂️ **bisect** allowed me to report a bug here so I did 😉

Outside of that, I'm not too sure

**Comment by evidolob** [comment]
Hm, strange, could you disable vscode-yaml, and test if Intelesense restores it work?

**Comment by JPinkney** [comment]
Any chance you can create a gif of it not working? IIRC you're the second person to run into this issue but we don't do anything with javascript, react, or typescript and everything seems to be working on my side (code 1.58.0 with vscode-yaml 0.21.0 on linux)

**Comment by destinio** [comment]
> Any chance you can create a gif of it not working? IIRC you're the second person to run into this issue but we don't do anything with javascript, react, or typescript and everything seems to be working on my side (code 1.58.0 with vscode-yaml 0.21.0 on linux)

Yes. give me a sec ;)

**Comment by destinio** [comment]
hmmm, so seems to have stopped working with is disabled again. Hold, please. I will report back in a bit

**Comment by destinio** [comment]
@evidolob @JPinkney Ok, I have re-run bisect and it turns out it was `yatki.vscode-surround` which makes wayyyy more sense.

So, y'all are off the hook 😝
Thank you for the quick response time 🍻
