### ISSUE TITLE
Not folding sub-documents

### ISSUE THREAD

**Issue by mcandre** [redhat-developer/vscode-yaml#561]
Neither stock Visual Studio Code nor this plugin are able to fold entire YAML sub-documents, when delimited by triple hyphen-minuses (`---`), for example. Please make sure to add support for this.

Allow the standard triple hyphen-minus, and/or ASCII ellipsis (`...`) to delimit multiple documents within each .y(a)?ml file.

**Comment by gorkem** [comment]
duplicate of #413
