### ISSUE TITLE
Hammerkit yaml schema picked up instead of Github actions

### ISSUE THREAD

**Issue by andig** [redhat-developer/vscode-yaml#565]
## Describe the bug
I have `yaml.schemaStore.enable` active and work with github actions (yaml files in `.github/workflows`. Editing `build.yaml` I see error indicators.

## Expected Behavior
No errors as yaml validated based on https://json.schemastore.org/github-action.json

## Current Behavior
Errors relating to https://json.schemastore.org/hammerkit.json

## Steps to Reproduce
Not really sure. This may be a problem with any of the schema definitions rather than this plugin, but I couldn't figure it out.

## Environment
- [ ] Windows
- [x] Mac
- [ ] Linux
- [ ] other (please specify)

**Comment by HarikrishnanBalagopal** [comment]
Same issue. This wasn't happening a few months ago.

**Comment by HarikrishnanBalagopal** [comment]
Going to `https://schemastore.org/` I get a certifacte error saying:
![image](https://user-images.githubusercontent.com/20921177/127636717-5add53bb-fcd0-4403-a3b2-6f645f1c12f9.png)
Does that have anything to do with this?

NOTE: the exact url has the correct certificate https://json.schemastore.org/github-action.json

**Comment by HarikrishnanBalagopal** [comment]
@andig Also the correct schema for Github workflows is this https://json.schemastore.org/github-workflow.json

**Comment by ariasuni** [comment]
This issue happens on Linux too. On my side, the plugins says it’s using both `github-actions.json` and `hammerkit.json`.

My solution was to put, in `settings.json`:

```json
    "yaml.schemas": {
        "https://json.schemastore.org/github-workflow.json": ".github/workflows/*"
    }
```

**Comment by andig** [comment]
I‘m still confused as to why it would be doing this?

**Comment by ariasuni** [comment]
JSON Schema Store’s API returns a list of schema with their `fileMatch` ([source](https://www.schemastore.org/json/#api)), that VS Code uses to determine which schema to apply to which file.

If we look into it:

```json
    {
      "name": "Hammerkit YAML Schema",
      "description": "JSON Schema for hammerkit files.",
      "fileMatch": [
        "build.yaml",
        "build.yml"
      ],
      "url": "https://json.schemastore.org/hammerkit.json"
    }
```

and

```json
    {
      "name": "GitHub Workflow",
      "description": "YAML schema for GitHub Workflow",
      "fileMatch": [
        ".github/workflows/**.yml",
        ".github/workflows/**.yaml"
      ],
      "url": "https://json.schemastore.org/github-workflow.json"
    },
```

There’s no clear way to determine which one should be used, even though it’s obvious for us human.

This extension could:

- Add a special case in their code for GitHub actions, or find some kind of heuristic (e.g. a `fileMatch` with a `/` has priority over a `fileMatch` that does not)
- Allow the user to chose which one to use with CodeLens, since it’s already able to display the two schema used using this.

**Comment by evidolob** [comment]
@ariasuni You are right.

> Allow the user to chose which one to use with CodeLens, since it’s already able to display the two schema used using this, instead of using two schemas at the same time, it’s just never what we want.

That how I plan to fix this.

**Comment by nomiro** [comment]
It should be possible to determine which schema to use if you compare how specific the `fileMatch` key is. I would measure specificity by splitting the value on path separators (`/`). The more path components, the more specific the match is. More specific matches take precedence over less specific matches.
