### ISSUE TITLE
yaml.customTags gets added to all opened projects in VSCode

### ISSUE THREAD

**Issue by barrymay** [redhat-developer/vscode-yaml#578]
## Describe the bug
In the latest version of this YAML extension (maybe has been going for a long time?), it appears that this it adds a yaml.customTags entry (see below) to the vscode settings.json, regardless of if you're using yaml in your project or not.

Since related extensions (like Atlassian's Jira extension) use the YAML extension as a dependency, this can be disruptive to the developer's workflow.  You also can't revert the change in your Git repo, because it'll just prompt again the next time vscode updates.  

If this is useful to the extension usage, can this be opted in as needed?

```
{
  "yaml.customTags": [
    "!And",
    "!And sequence",
    "!If",
    "!If sequence",
    "!Not",
    "!Not sequence",
    "!Equals",
    "!Equals sequence",
    "!Or",
    "!Or sequence",
    "!FindInMap",
    "!FindInMap sequence",
    "!Base64",
    "!Join",
    "!Join sequence",
    "!Cidr",
    "!Ref",
    "!Sub",
    "!Sub sequence",
    "!GetAtt",
    "!GetAZs",
    "!ImportValue",
    "!ImportValue sequence",
    "!Select",
    "!Select sequence",
    "!Split",
    "!Split sequence"
  ]
}
```

## Expected Behavior
Don't add this to the .vscode settings by default, unless I've opted into this default behavior.  Suggestion if it's very handy: ask the user if they want these settings added, with a 'Don't Show This Again' option if you never want it)

## Current Behavior
See the description above

## Steps to Reproduce
1. Install this extension (or another extension that depends on it)
2. Open your project
3. VSCode will see the change and the settings to your VSCode's settings.json
4. As an aside, it'll probably prompt you to check the change in (which I would expect if there was a (desired) change to my code or settings.)

## Environment (probably all of them but I see it in Mac)
- [ ] Windows
- [x] Mac
- [ ] Linux
- [ ] other (please specify)

**Comment by JPinkney** [comment]
AFAIK we aren't adding anything to `yaml.customTags` by default, we just create the setting on our side. Do you have a cloudformation or aws extension installed? My guess is that one of those extensions are adding in those tags into `yaml.customTags`.

**Comment by barrymay** [comment]
@JPinkney thanks for the quick reply.  I found that "AWS Toolkit" (when combined with the active "YAML" extension) is indeed the culprit here, so this can be closed.  Thanks!
