### ISSUE TITLE
off value is highlighted as wrong in rules section in .eslintrc.yml

### ISSUE THREAD

**Issue by EmilySeville7cfg** [redhat-developer/vscode-yaml#581]
## Describe the bug

`off` value is highlighted as wrong in rules section in .eslintrc.yml.

## Expected Behavior

No error expected with `off` value such as with `error` and `warn` ones.

## Current Behavior

`Incorrect type. Expected "integer | string | array".` error with `off`:

![image](https://user-images.githubusercontent.com/42812113/130000727-b8f5b86f-dbf8-4ef4-b475-428f746ce941.png)

When I quote `off` everything works fine. And also note that even without quotes .eslintrc.yml works fine (specified rules are ignored normally).

## Steps to Reproduce

1. Install this extension
2. Create any .js project with .eslintrc.yml
3. Try to disable rules via `off` keyword

## Environment
- [ ] Windows
- [ ] Mac
- [X] Linux (Ubuntu 20.04 LTS, VSCode 1.59.0)
- [ ] other (please specify)

**Comment by gorkem** [comment]
Are you still able to reproduce this error? At least the above example works fine for me.

**Comment by EmilySeville7cfg** [comment]
Yes, everything works fine now.
