### ISSUE TITLE
Can not load schema file when the URL is redirected.

### ISSUE THREAD

**Issue by soumi-akira** [redhat-developer/vscode-yaml#586]
## Describe the bug

It seems the extension failed to load schema file from URL that is redirected.

e.g)

`codeben.yml`

Works fine. Loaded schema URL is https://www.schemastore.org/api/json/catalog.json

`graphql.config.yml`

Error. Loaded schema URL is https://unpkg.com/graphql-config/config-schema.json

> Unable to load schema from 'https://unpkg.com/graphql-config/config-schema.json': Request vscode/content failed unexpectedly without providing any details.YAML(768)

The URL is redirected to

https://unpkg.com/graphql-config@4.0.1/config-schema.json

## Expected Behavior

Load schema file even redirected.

## Current Behavior

Throws error below, schema isn't loaded.

> Unable to load schema from 'https://unpkg.com/graphql-config/config-schema.json': Request vscode/content failed unexpectedly without providing any details.YAML(768)

## Steps to Reproduce
1. create `graphql.config.yml`
2. open `graphql.config.yml`

## Environment
- [x] Windows
- [ ] Mac
- [ ] Linux
- [ ] other (please specify)

## Workaround

create `.vscode/setting.json`

```json
{
  "yaml.schemas": {
    "https://unpkg.com/graphql-config@4.0.1/config-schema.json": "graphql.config.yml"
  }
}
```

**Comment by craigkc** [comment]
I ran into this issue today and appreciate the workaround.  I wonder about the implications of a fix, since I could imagine it's coded to not follow redirects for reasons around security?

**Comment by evidolob** [comment]
This issue causes bug in `request-light` library which we use to download JSON Schema.
I provide PR to fix redirect support  https://github.com/microsoft/node-request-light/pull/8
