### ISSUE TITLE
using inline schema reference (# yaml-language-server: $schema) seems to not support relative paths

### ISSUE THREAD

**Issue by trondhindenes** [redhat-developer/vscode-yaml#587]
## Describe the bug
When using the `# yaml-language-server: $schema` notation in a yaml file, it kindof works if I give it a path to a local file:
`# yaml-language-server: $schema=/home/what/somefolder/schema.json`

however, if I point to a relative file, it doesn't seem to work: 
`# yaml-language-server: $schema=schema.json`
`# yaml-language-server: $schema=./schema.json`
In this example, the schema file lives in the root of the open folder in vscode.

## Expected Behavior
relative files should work

## Steps to Reproduce
s33 ablve

## Environment
- [ ] Windows
- [ ] Mac
- [x] Linux
- [ ] other (please specify)

**Comment by loozhengyuan** [comment]
In my case, it works but it is relative to the file instead of the repository root.

**Comment by evidolob** [comment]
@trondhindenes @loozhengyuan Are right relative paths is calculated from yaml file path, not from workspace root path

**Comment by trondhindenes** [comment]
thanks. maybe that's something that could be clarified in the docs, I don't think it's mentioned at all.

**Comment by aalkhodiry** [comment]
This also works for people using public `config.schema.json`

```
# yaml-language-server: $schema=https://raw.githubusercontent.com/..../config.schema.json
```
