### ISSUE TITLE
How to add OpenShift schema for YAML validation?

### ISSUE THREAD

**Issue by crdnb** [redhat-developer/vscode-yaml#589]
## Summary
I am trying to use an OpenShift schema to validate YAML files against it. I found OpenShift schemas on this repo, but always get a "parse error": https://github.com/garethr/openshift-json-schema

## Relevant information

I tried different URLs, but I always get the same error (see above):
- https://github.com/garethr/openshift-json-schema
- https://github.com/garethr/openshift-json-schema/blob/master/schemas/v4.json
- https://github.com/garethr/openshift-json-schema/tree/master/v4.1.0
- https://github.com/garethr/openshift-json-schema/blob/master/v4.1.0/_definitions.json
- https://github.com/garethr/openshift-json-schema/blob/master/v4.1.0/all.json

Error message: 
`Unable to parse content from 'https://github.com/garethr/openshift-json-schema/blob/master/schemas/v4.json': Parse error at offset 6.YAML(768)`

Would much appreciate if you could tell me how to configure the OpenShift schema to be used for YAML validation. Thank you!

**Comment by JPinkney** [comment]
You need to add a link to the actual raw content like: https://raw.githubusercontent.com/garethr/openshift-json-schema/master/v4.1.0/_definitions.json

**Comment by crdnb** [comment]
Hi @JPinkney 
This obviously makes sense :) Sorry for the mistake and thanks for the hint!
