### ISSUE TITLE
Support Travis CI file

### ISSUE THREAD

**Issue by Deilan** [redhat-developer/vscode-yaml#59]
Currently there's a red squiggle for a valid `.travis.yml` fragment:

![image](https://user-images.githubusercontent.com/4777512/35145452-e7cd3bd8-fd18-11e7-9937-1ce7b73ed32d.png)

With a tooltip:

![image](https://user-images.githubusercontent.com/4777512/35145459-f43c1588-fd18-11e7-844f-09bbd40d2ad4.png)

According to [the docs](https://docs.travis-ci.com/user/chrome) it's valid though.

Not sure whether `.travis.yml` is supported by design. If it's not, then it would be great to have.

**Comment by JPinkney** [comment]
The .travis.yml schema is pulled in from https://github.com/SchemaStore/schemastore. I believe it was handcrafted by one contributor so it may still need a few tweaks. I'll look into it and then do a PR on that side.

**Comment by JPinkney** [comment]
I've opened a PR for this fix in the schemastore: https://github.com/SchemaStore/schemastore/pull/396

**Comment by JPinkney** [comment]
The PR has been merged, so i'm closing this issue!
