### ISSUE TITLE
VSCode: only .yml files get recognized, not .yaml files

### ISSUE THREAD

**Issue by Eeppii** [redhat-developer/vscode-yaml#597]
## Describe the bug
The extension works as expected on `.yml` files. However, the extension `.yaml` is not recognized anymore as a YAML file by the extension.

## Expected Behavior
Recognize `.yaml` and `.yml` files as YAML files.

## Current Behavior
Only recognizes `.yml` files.

## Steps to Reproduce
1. open any `.yaml` the file in VSCode
2. the file is not recognized by the extension.

## Environment
- [ ] Linux, Ubuntu 18.04
- [ ] Extension version 0.22.0

**Comment by JPinkney** [comment]
I just tried it on Fedora with extension version 0.22.0 and everything was working for me. What do you mean not recognised? The file types not automatically set? Or a schema isn't being picked up? Do you have any other yaml related extensions installed?

**Comment by Eeppii** [comment]
Thanks for the quick reply - I suspect my settings somehow got reset 🤔
I could resolve the issue by re-selecting the language mode YAML for all `.yaml` files. Will close this issue then. Thanks for checking!
