### ISSUE TITLE
Autocompletion does not work with custom schema

### ISSUE THREAD

**Issue by Fubuchi** [redhat-developer/vscode-yaml#600]
## Describe the bug
Autocompletion does not work with custom schema. Built-in schema like "kubernetes" work as normal.
Similar to #99 

## Expected Behavior
Autocompletion should work with custom schema.

## Current Behavior
My settings:
```
{
    "yaml.schemas": {
        "https://raw.githubusercontent.com/garethr/openshift-json-schema/master/v3.11.0/_definitions.json": "*.yaml"
    },
    "editor.wordBasedSuggestions": false
}
```

But autocomplete didn't work
![image](https://user-images.githubusercontent.com/42483897/135074952-8db01fb4-e9a1-48ca-90ac-9bae1f8c7d16.png)

Trace log: 
[verbose.log](https://github.com/redhat-developer/vscode-yaml/files/7243324/verbose.log)

## Environment
OS: Windows
Extension version: 0.22.0

**Comment by evidolob** [comment]
@Fubuchi The JSON file which you point, is not valid JSON Schema. The file contains set of sub schemas in `definitions` key,
but it doesn't contains any validation keyword for root object, see https://json-schema.org/learn/getting-started-step-by-step.html#starting

**Comment by Fubuchi** [comment]
I found this isssue #589 ,so I though that file is a valid schema for openshift. Is there any available schema for openshift like kubenetes?

**Comment by evidolob** [comment]
Try this https://raw.githubusercontent.com/garethr/openshift-json-schema/master/v4.1.0/all.json 
It should work.

**Comment by evidolob** [comment]
Or this https://github.com/garethr/openshift-json-schema/blob/master/v3.11.0/all.json If you interested in openshift v3.11.0

**Comment by Fubuchi** [comment]
It said `Matches multiple schemas when only one must validate`. It seem like I need to figure out exactly which schema for each config I use. But it is another problem, thank you.
