### ISSUE TITLE
yaml-language-server stop working

### ISSUE THREAD

**Issue by foolioo** [redhat-developer/vscode-yaml#610]
## Describe the bug

using [yaml-language-server in conjunction with inline schema](https://github.com/redhat-developer/yaml-language-server#using-inlined-schema) does not seem to work anymore in VSCode

```shell
$ code --version
1.61.0
ee8c7def80afc00dd6e593ef12f37756d8f504ea
x64

$ code --list-extensions --show-versions | grep yaml
redhat.vscode-yaml@0.23.0
```

## Expected Behavior

When using inline schema, VSCode should support auto-completion and syntax error highlighting

## Current Behavior

Both auto-completion and syntax error highlighting do not work

## Steps to Reproduce

1. Install VSCode
2. Install redhat.vscode-yaml VSCode extension
3. Create a new yaml file and add inline schema
4. Try using auto-completion for the included schema

## Environment
- [ ] Windows
- [x] Mac
- [ ] Linux
- [ ] other (please specify)

**Comment by evidolob** [comment]
@foolioo It is working for me:

https://user-images.githubusercontent.com/929743/136789474-ca73b904-d6b2-44ac-95e8-7d1c39bf6dc6.mov

Could you share the content of yaml file and json schema?

**Comment by foolioo** [comment]
@evidolob I looked by pressing `cmd + j`, and in the output tab, I selected `YAML Support`.

There is nothing there :(
