### ISSUE TITLE
Confusing "Property is not allowed" error, when property is allowed, just slightly misconfigured

### ISSUE THREAD

**Issue by henrahmagix** [redhat-developer/vscode-yaml#614]
## Describe the bug

When configuring a property, if any of the child properties are configured incorrectly, then it seems like the parent property doesn't exist, which lead me to try to debug why the property isn't allowed. It took me a while to discover that a child property was misconfigured, which when configured correctly, resolves the error.

## Expected Behavior
Extension says that `defaultBackend.service.port` is misconfigured, and perhaps show its definition so I know how to properly configure it.

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-ingress
spec:
  defaultBackend:
    service:
      name: my-service
      port: 80
```

## Current Behavior
Extension says that `defaultBackend` is not allowed.
> Property defaultBackend is not allowed. yaml-schema: https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.20.5-standalone-strict/_definitions.json
<img width="541" alt="image" src="https://user-images.githubusercontent.com/1429026/137319916-dc54f46f-14c7-4860-9eac-e2528dbcf02e.png">

## Steps to Reproduce

1. copy Ingress definition above
2. see error defined on the `defaultBackend` line, as shown in above screenshot
3. fix `port: 80` to
  ```yaml
  port:
    number: 80
  ```
4. see error disappear: `defaultBackend` is allowed, it was just misconfigured slightly

<img width="661" alt="image" src="https://user-images.githubusercontent.com/1429026/137320365-7d102a3c-9909-45d2-a995-110d81360e3d.png">

Also I have the following workspace settings to define the schema for my yaml files:
```json
{
	"folders": [
		{
			"path": "."
		}
	],
	"settings": {
		"yaml.schemas": {
			"Kubernetes": [
				"*.yml",
				"**/*.yml"
			]
		},
	}
}
```

## Environment
- [ ] Windows
- [x] Mac
- [ ] Linux
- [ ] other (please specify)

Version: v0.23.0 [Preview]

Cannot find other version to install via VS Code Marketplace, so I can only test this preview version.

Thanks =)

**Comment by evidolob** [comment]
Fixed with https://github.com/redhat-developer/yaml-language-server/pull/611

**Comment by henrahmagix** [comment]
Amazing, thanks so much @evidolob !

**Comment by noisnemid** [comment]
it appears again!
![aaa](https://user-images.githubusercontent.com/16525011/163708133-116349e8-14ef-497c-a6c3-b1efd8b8320e.png)
vscode 1.66.2
ext yaml redhad 1.6.0

**Comment by msarahan** [comment]
you can see that VSCode is using some schema called "Cheatsheets". Are you expecting it to do this? Do you know what that schema is? Schema are generally applied by matching a filename pattern, so if you rename your file to a pattern that does not match, VSCode is no longer applying that schema for validation.

You can also change to another schema. Look in the bottom right of your window. Mouse-over says "select JSON schema" - even though it says JSON schema, it is applying to your YAML file.

**Comment by Fwngry** [comment]
so what can i do? nobody so it very clearly.
