### ISSUE TITLE
[Regression] Completion of second level for Camel K files are no more working

### ISSUE THREAD

**Issue by apupier** [redhat-developer/vscode-yaml#619]
## Describe the bug

With Camel K files, the second level of completion is not working.

it is working fine with VS Code yaml 0.23.0

## Expected Behavior
completion based on yaml schema provided

## Steps to Reproduce

1. install VS Code Camel K
2. create a xx.yaml file
3. put content: (take care of the 4 spaces on the last line)
```
# camel-k:
- from:
    
```
4. call completion on last character of last line
5. No completion is provided by yaml

## Environment
- [ ] Windows
- [ ] Mac
- [x] Linux
- [ ] other (please specify)

**Comment by microhobby** [comment]
@apupier and @evidolob oddly I'm having the same issue again with `v1.1.1`.
Should I open a new issue?

```
Version: 1.63.0-insider (user setup)
Commit: a7104f13ff61bcd9f4c827d8fe3c0d27bb479fd8
Date: 2021-11-08T05:14:49.440Z
Electron: 13.5.1
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.22489
```

**Comment by evidolob** [comment]
It should be fixed with https://github.com/redhat-developer/yaml-language-server/pull/579
