### ISSUE TITLE
Help user set the schema of current YAML file

### ISSUE THREAD

**Issue by akaroml** [redhat-developer/vscode-yaml#62]
Currently, a user needs to specify schemas by modifying the settings.json.
Here to propose a status bar item to show the current schema for the current YAML file. Users can tell what schema is currently used and can switch schema by clicking on it.
This is useful when the wildcard is supported when associating schemas with YAML files.
The list of available schemas is maintained by the YAML extension. It will also allow other extensions register new schemas. It can also work with the mechanism proposed in #61 to automatically associate schemas with YAML files.

**Comment by andxu** [comment]
https://github.com/redhat-developer/vscode-yaml/pull/70

**Comment by andxu** [comment]
@JPinkney when is the next release window for vscode-yaml in market-place?

**Comment by JPinkney** [comment]
@andxu Should be this monday!

**Comment by gorkem** [comment]
Can we close this?

**Comment by GuidoS** [comment]
Is there a place where the schema being used is displayed on the editor?

**Comment by ssbarnea** [comment]
> Is there a place where the schema being used is displayed on the editor?

I have to confess that I have the same problem. This extension should expose the Schema used somewhere, probably in the status line. The tooltip on YAML could be an useful place.

I have no clue which schema was used in a file, if any at all. For someone trying to write schemas this is double annoying.

**Comment by JPinkney** [comment]
I would be OK with having a way to show which schemas are associated with the currently open file but I'm just now sure how. The status bar is already generally crowded and how should we display them on the status bar when there is multiple schemas associated with a yaml file?

**Comment by ssbarnea** [comment]
Tooltip or the icon should be ok. It would avoid avoid cluttering the statusbar.
