### ISSUE TITLE
"Fail to provide custom schemas." error in output log over and over

### ISSUE THREAD

**Issue by darkvertex** [redhat-developer/vscode-yaml#63]
I just installed it for the first time and opened a yaml file and every few seconds I get an error saying "Fail to provide custom schemas." printed to the "Yaml Support" Output log.

I'm on VSCode 1.21.0-insider on CentOS Linux release 7.4.1708 (Core)

Any clues?

**Comment by JPinkney** [comment]
Its just a console.log that snuck through a PR, the message will be disabled on our next update (most likely monday)

**Comment by darkvertex** [comment]
Ah, great! I was concerned I had done something wrong on my end.

I'll wait for the update. Thanks!

**Comment by JPinkney** [comment]
This should be gone with our 0.0.0 release
