### ISSUE TITLE
multiline arrays with comments within the array LINT as errors

### ISSUE THREAD

**Issue by lewisl** [redhat-developer/vscode-yaml#630]
In Visual Studio Code (MacOS), a yaml file contains this:
```
sendrisk:  [0.00, 0.30, 0.65, 0.75, 0.85, 0.85, 0.75, 0.70, 0.65, 0.6, 
#             11     12   13    14    15    16    17     18   19    20
            0.50, 0.20, 0.10, 0.10, 0.10, 0.05, 0.05, 0.00, 0.00, 0.0, 
#             21     22   23    24    25
            0.00, 0.00, 0.00, 0.00, 0.00]
```
Red underline squiggles indicating some error appear under the comma after 0.6 in the first line of the array and under the entire second line of the array. Surprisingly, the third line of the error shows no linting error. 

So, these are white space warnings, but I don't see what's wrong.  All the mapping items start in column 1. Only the one shown above is flagged as an error.

The flow sequence is continued until the array is closed, which I believe is allowed in YAML.  So, it is continued and closed properly.

Finally, I am not aware where I have implicit map keys.

It all parses to correct output in the Julia language package for YAML.  So, at least one YAML parser is happy with this.

The linting errors appear thus:
```
{
	"resource": "/Users/xxxx/Dropbox/Covid Modeling/Covid-ILM/parameters/variant_parameters/base_variant/base_spread.yml",
	"owner": "_generated_diagnostic_collection_name_#0",
	"severity": 8,
	"message": "All mapping items must start at the same column",
	"source": "YAML",
	"startLineNumber": 4,
	"startColumn": 70,
	"endLineNumber": 4,
	"endColumn": 73
}

{
	"resource": "/Users/lewis/Dropbox/Covid Modeling/Covid-ILM/parameters/variant_parameters/base_variant/base_spread.yml",
	"owner": "_generated_diagnostic_collection_name_#0",
	"severity": 8,
	"message": "Expected flow sequence to end with ]",
	"source": "YAML",
	"startLineNumber": 4,
	"startColumn": 71,
	"endLineNumber": 4,
	"endColumn": 73
}

{
	"resource": "/Users/lewis/Dropbox/Covid Modeling/Covid-ILM/parameters/variant_parameters/base_variant/base_spread.yml",
	"owner": "_generated_diagnostic_collection_name_#0",
	"severity": 8,
	"message": "Implicit map keys need to be followed by map values",
	"source": "YAML",
	"startLineNumber": 6,
	"startColumn": 14,
	"endLineNumber": 6,
	"endColumn": 73
}
```

**Comment by gorkem** [comment]
Are you still able to reproduce this? When I copy the example and paste it on a new  YAML document I do not see the errors.

**Comment by lewisl** [comment]
No.  Just checked with v 1.5.1 of the plugin.
