### ISSUE TITLE
JSON-in-YAML fails to parse in v1.0.0+

### ISSUE THREAD

**Issue by laverdet** [redhat-developer/vscode-yaml#631]
## Describe the bug
The following yaml payload fails to parse starting in version v1.0.0.
```yaml
foo: [ {
  bar: 1
} ]
```

## Expected Behavior

This is valid YAML so it should work in the editor. JSON-in-YAML is specified here: https://yaml.org/spec/1.2.2/#102-json-schema

## Current Behavior

I get the following errors on line 3:
```
Expected flow map to end with } YAML
Expected flow sequence to end with ] YAML
Unexpected flow-map-end token in YAML stream: "}" YAML
```

## Steps to Reproduce

1. Make a file with the content above
2. Observe the red squiggly lines

## Environment
- [ ] Windows
- [x] Mac
- [ ] Linux
- [ ] other (please specify)

**Comment by gorkem** [comment]
@evidolob it looks like we adopted the new parser version and there is not much else left to do. So I am closing this one
