### ISSUE TITLE
Feature request: formatter

### ISSUE THREAD

**Issue by marco-m** [redhat-developer/vscode-yaml#64]
Hello,
if I select "Format document", vscode pops up "Sorry, but there is no formatter for 'yaml'-files installed."
It would be nice if this extension supported formatting :-)

**Comment by JPinkney** [comment]
The formatter should be available in our latest update! The code was in it server side for a while I just didn't update some vscode extension dependencies so it wasn't showing up

**Comment by marco-m** [comment]
Thanks!

**Comment by dburles** [comment]
Hey I'm on 0.0.9 and seeing the same message

**Comment by unional** [comment]
Same here. No formatter in 0.0.9

**Comment by JPinkney** [comment]
Have you turned on the formatter in the yaml settings? It’s not enabled by default. After it’s enabled it requires a restart.

**Comment by danhofer** [comment]
I've enabled the formatter and restarted VS Code, yet I still get the message that there is no formatter. I'm on version 0.0.11. Tried uninstalling and re-installing the extension, too.

**Comment by JPinkney** [comment]
It seems to work fine for me on latest version. Are you accidentally using https://marketplace.visualstudio.com/items?itemName=adamvoss.yaml instead of https://marketplace.visualstudio.com/items?itemName=redhat.vscode-yaml or do you have any other yaml extensions activated?

**Comment by danhofer** [comment]
The only other extensions I have installed besides this one are a Python extension and an ESLint extension. I've enabled `"yaml.format.enable": true` in my user settings. I'm assuming I can format code by highlighting what I want to format and pressing `cmd-K-F` like I can for JavaScript. Is that correct, or am I misunderstanding?

**Comment by JPinkney** [comment]
Currently it just formats the entire document. If you right click on a yaml file is the format document option there? Which version of vscode are you using?

**Comment by danhofer** [comment]
I'm on VS Code version 1.22.2. When the file is open in the file explorer this is my menu when I right click. Right clicking on a closed file has a menu with less options.
![menu](https://user-images.githubusercontent.com/30373421/39528916-69a11c76-4df3-11e8-8b45-e0e60223f014.png)

**Comment by JPinkney** [comment]
No, I mean when you have a yaml file open and you right click inside the text editor. This is what I see.
![screenshot from 2018-05-02 10-39-24](https://user-images.githubusercontent.com/8839537/39529719-59d4135a-4df5-11e8-993f-2cdce07505b7.png)

**Comment by danhofer** [comment]
Ah yes, I see it. When I click the menu option it works. Thank you very much!

**Comment by PZ01** [comment]
Any reason the format removes comments?(Statements starting with a hash #)

**Comment by JPinkney** [comment]
The parser does not support comments so when formatting it it just removed it. I’m switching formatters soon and that will fix the problem.
