### ISSUE TITLE
When yaml have quoted keys, schema not works

### ISSUE THREAD

**Issue by loynoir** [redhat-developer/vscode-yaml#645]
## Describe the bug

When yaml have quoted keys, schema not works

## Expected Behavior

```txt
<cursor>"version"</cursor>: "3.7"

Hint: The version of the Docker Compose document
```

## Current Behavior

```txt
<cursor>"version"</cursor>: "3.7"

(Nothing...)
```

## Steps to Reproduce

Repo
https://github.com/loynoir/reproduce-vscode-yaml-645.yml

1. Ensure schema works when no quote
2. https://github.com/loynoir/reproduce-vscode-yaml-645.yml/blob/master/fail/docker-compose.yml#L1
3. `<cursor>"version"</cursor>: "3.7"`  

## Environment
- [ ] Windows
- [ ] Mac
- [x] Linux
- [ ] other (please specify)

**Comment by evidolob** [comment]
@loynoir I try to reproduce this, and it work for me:
<img width="727" alt="Screenshot 2021-12-10 at 11 09 07" src="https://user-images.githubusercontent.com/929743/145548004-2099457d-d3d1-451d-8d8e-a9016f0fea8b.png">

**Comment by loynoir** [comment]
Now shows error
```txt
Request vscode/content failed unexpectedly without providing any details.
```

Had a search, seems related to
#657 
#586
#550

Below workaround works
```json
{
    "yaml.schemas": {
        "http://127.0.0.1:12345/compose-spec.json": "docker-compose.yml"
    }
}
```

**Comment by loynoir** [comment]
Oh, and the exact comment "The version of the Docker Compose document" in the reproduce `work/docker-compose.yml` seems come from another extension, after I disable all vscode extension, it's gone.
