### ISSUE TITLE
lost collapse abiility

### ISSUE THREAD

**Issue by hugomelendez** [redhat-developer/vscode-yaml#646]
Something has changed with the extneison
everytime I load a yaml file start with the up/down arrow for collapsing lines, then a couple of seconds after de vscode start I've lost the feature.
 a thing related to other extensions maybe ?

**Comment by fbricon** [comment]
Works for me. Try disabling the other extensions, see if there's a conflict.

**Comment by Teckdev** [comment]
I had the same issue. Disabling the `region folding for VS Code` extension fixed the issue

**Comment by gorkem** [comment]
Closing as it looks like this is a conflict with another extension.
