### ISSUE TITLE
Unresolved tag: !Ref in CloudFormation Template

### ISSUE THREAD

**Issue by mcflynt** [redhat-developer/vscode-yaml#669]
##Description
When the extension is running and I am creating a CloudFormation template, the valid syntax of !Ref EnvironmentName, for example, where EnvironmentName is a Parameter in the template is not recognized. The extension produces a 'Problem' of 'Unresolved tag: !Ref'

## Expected Behavior
No syntax errors should be reported as this is a valid syntax

## Current Behavior
![image](https://user-images.githubusercontent.com/96748261/147601620-cc44a65b-e5e6-40ff-aabc-f9bc18ba8920.png)

![image](https://user-images.githubusercontent.com/96748261/147601635-0f0298e4-c649-447a-ba30-fb6b4d8b445d.png)

## Steps to Reproduce
1. Create CloudFormation template with any resource (Easiest is an S3 bucket)
2. Add in a parameter in the Parameters section of the template called EnvironmentName
3. In the Tags property on the S3 bucket, enter the key value pairs as in the screen-print above:
Tags:
- Key: 'environment-name'
- Value: !Ref EnvironmentName

## Environment
- [x ] Windows

## Note
The same thing happens with the also valid inline !Sub
Example: BucketName: !Sub 'my-first-bucket-${EnvironmentName}' is highlighted and the Problems report shows Unresolved tag !Sub

**Comment by gorkem** [comment]
Closing. Please let us know if there is anything else we can do.

**Comment by lmammino** [comment]
in your vscode `settings.json`:

```json
{
    "yaml.customTags": [
        "!Sub scalar"
    ]
}
```

**Comment by jroeber** [comment]
Here's the full list based on the [AWS CloudFormation intrinsic function docs](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference.html)

```json
{
    "yaml.customTags": [
        "!Base64 scalar",
        "!Cidr scalar",
        "!And sequence",
        "!Equals sequence",
        "!If sequence",
        "!Not sequence",
        "!Or sequence",
        "!Condition scalar",
        "!FindInMap sequence",
        "!GetAtt sequence",
        "!GetAZs scalar",
        "!ImportValue scalar",
        "!Join sequence",
        "!Select sequence",
        "!Split sequence",
        "!Sub scalar",
        "!Transform mapping",
        "!Ref scalar",
    ]
}
```

**Comment by Unintendedz** [comment]
> Here's the full list based on the [AWS CloudFormation intrinsic function docs](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference.html)
> 
> ```json
> {
>     "yaml.customTags": [
>         "!Base64 scalar",
>         "!Cidr scalar",
>         "!And sequence",
>         "!Equals sequence",
>         "!If sequence",
>         "!Not sequence",
>         "!Or sequence",
>         "!Condition scalar",
>         "!FindInMap sequence",
>         "!GetAtt sequence",
>         "!GetAZs scalar",
>         "!ImportValue scalar",
>         "!Join sequence",
>         "!Select sequence",
>         "!Split sequence",
>         "!Sub scalar",
>         "!Transform mapping",
>         "!Ref scalar",
>     ]
> }
> ```


Thanks for this list! 

I am not familiar with yaml, it seems `!GetAtt sequence` not working for me, I've tried to add `!GetAtt scalar` and it worked.

![image](https://user-images.githubusercontent.com/64687143/171066780-590bdaac-546c-424d-9232-97a174858f9d.png)

**Comment by Patrick-Da-Silva-RR** [comment]
Isn't there a way that those settings are part of the extension?

**Comment by saadelkenawy** [comment]
I have this problem how to fix it Please
