### ISSUE TITLE
Schema reference with fragment not working for local files

### ISSUE THREAD

**Issue by Kosta-Github** [redhat-developer/vscode-yaml#675]
## Describe the bug

When providing a schema with a fragment (e.g., `babelrc.json#/definitions/Options`) it is only working for remote schemas but loading the schema from the local file fails:

* for a remote schema this is working (`https://json.schemastore.org/babelrc.json#/definitions/Options`):
  ![image](https://user-images.githubusercontent.com/2526664/149285637-9017c2a9-bdad-4285-86b7-b6fc8f926c8c.png)
  _NOTE: the shown error message above is not the error, it just provides the proof that the remote schema is used for validation!_

* for the same schema stored as a local file this is not working (`./babelrc.json#/definitions/Options`):
  ![image](https://user-images.githubusercontent.com/2526664/149285802-b5d223a4-f29d-4cb3-b8b7-b6a32cb1d79c.png)
  _NOTE: the shown error message is the actual failure to be demonstrated, since it shows that the schema loading failed in this case!_

* however, if you remove the fragment part from the schema (`./babelrc.json`), the schema could be loaded just fine:
  ![image](https://user-images.githubusercontent.com/2526664/149286120-04c30130-51bb-400f-9b45-3bf87cf53cfe.png)
  _NOTE: the shown error message above is not the error, it just provides the proof that the local schema file could be loaded successfully!_

## Expected Behavior

Fragments should be supported for local files as well. The underlying library `yaml-language-server` has support for this: https://github.com/redhat-developer/yaml-language-server/blob/436443c6eb5723bae921119465f9ffc9028e477a/test/yamlSchemaService.test.ts#L95-L118

## Current Behavior

If a fragment is provided it fails to load the schema definition from a local file.

## Steps to Reproduce

See screenshots above.

## Environment
- [ ] Windows
- [ ] Mac
- [ ] Linux
- [ ] other (please specify)

**Comment by msivasubramaniaan** [comment]
@Kosta-Github The mentioned issue is working on 1.4.0 Please refer the screenshot.
![image](https://user-images.githubusercontent.com/93245779/153827278-abb21770-91e2-49d0-bdf7-b3ed252c8d1f.png)

**Comment by msivasubramaniaan** [comment]
@Kosta-Github Please close this issue if you were confirmed that it is working.

**Comment by Kosta-Github** [comment]
verified: works for me now as expected! 👍
