### ISSUE TITLE
Not descriptable error when using wrong type in array item

### ISSUE THREAD

**Issue by EmilySeville7cfg** [redhat-developer/vscode-yaml#685]
## Describe the bug

JSON schema `input.json`:

```json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "title": "Some description",
  "definitions": {
    "rootItem": {
      "title": "root item",
      "type": "object"
    }
  },
  "type": "object",
  "properties": {
    "root": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/rootItem"
      }
    }
  },
  "additionalProperties": false
}
```

Wrong `input.yml`:

```yml
root:
  - 1
```

Not user friendly error is displayed for `1`: `Incorrect type. Expected "rootItem"`.

## Expected Behavior

I think that it's better to display `title` value when provided not to confuse users:

```
`Incorrect type. Expected "root item"`.
```

## Current Behavior

```
`Incorrect type. Expected "rootItem"`
```

## Steps to Reproduce

1. Create `input.json` and `input.yml`
2. Create .vscode/settings.json` for workspace:

```json
{
  "yaml.schemas": {
    "input.json": "test.yml"
  }
}
```

3. See an error displayed for `input.yml`

## Environment
- [ ] Windows
- [ ] Mac
- [x] Linux
- [ ] other (please specify)

**Comment by gorkem** [comment]
This has been fixed already. At least 1.7.0 has the fix
