### ISSUE TITLE
oneOf: misleading validation failures with Incorrect type. Expected "object"

### ISSUE THREAD

**Issue by ssbarnea** [redhat-developer/vscode-yaml#692]
## Describe the bug

I discovered that the error message on invalidated values does only report the first failed check, even if the field allows multiple variants, confusing the user about which measures he can do.

```yaml
# .github/workflows/sample.yml
jobs:
  foo:
    steps:
       - run: echo 123
      env: ${{ matrix.env }} # <-- line that should fail validation
```

As github-workflows schema requires either an object for `env` or a `string` following a specific pattern, that line should produce a validation error as the pattern does not match current string.

```yaml
# relevant section from schema:
"oneOf": [
        {
          "type": "object",
          "additionalProperties": {
            "oneOf": [
              {
                "type": "string"
              },
              {
                "type": "number"
              },
              {
                "type": "boolean"
              }
            ]
          },
          "minProperties": 1
        },
        {
          "$ref": "#/definitions/expressionSyntax",
          "$comment": "https://docs.github.com/en/actions/learn-github-actions/expressions#fromjson",
          "pattern": "^\\$\\{\\{\\s*fromJSON\\(.*\\)\\s*\\}\\}$"
        }
      ]
    },
```

## Expected Behavior
Display a validation message that mentions that `oneOf` multiple conditions needs to be met, so the user can figure-out what he did wrong.

## Current Behavior

As you can see the error below is incomplete and is misleading the user about not accepting strings.
```
Incorrect type. Expected "object".
```

**Comment by ssbarnea** [comment]
Not sure if that is the same bug or another one so I will only mention it as a comment first.

Apparently keys under `matrix:` in github workflows are marked as not allowed, even if the schema is correctly defined.

Look at https://github.com/SchemaStore/schemastore/blob/master/src/test/github-workflow/matrix_include.json#L13-L22 test file, which raise false positive with us.

![](https://sbarnea.com/ss/Screen-Shot-2022-02-04-13-04-58.02.png)

**Comment by ssbarnea** [comment]
I suspect that https://github.com/redhat-developer/vscode-yaml/issues/691#issuecomment-1059056848 is not working for the same reasons. When we will see a new release?... or where can I download a build from master so I can check if this was fixed.

**Comment by msivasubramaniaan** [comment]
@ssbarnea The new release would be coming week. will let you know with the release details

**Comment by sarfarajMD** [comment]
[
  {
    "version": "latest",
    "buildId": "ca5c67098852b9f8355ef33d292d194372aa0c8d",
    "publishDate": "2025-01-25T00:30:39.864679Z",
    "files": {
      "linux-x64": {
        "url": "https://swalocaldeployv2-bndtgugjgqc3dhdx.b01.azurefd.net/downloads/ca5c67098852b9f8355ef33d292d194372aa0c8d/linux/StaticSitesClient",
        "sha": "5847b6a17360a428026b5ebe5d059686f60f0a0d78d9e5fb04e131cdef10c441"
      },
      "win-x64": {
        "url": "https://swalocaldeployv2-bndtgugjgqc3dhdx.b01.azurefd.net/downloads/ca5c67098852b9f8355ef33d292d194372aa0c8d/windows/StaticSitesClient.exe",
        "sha": "f1e9a3634be57e0ea67e716972973b0925b1523d578025cc586e7a1bb6a8b153"
      },
      "osx-x64": {
        "url": "https://swalocaldeployv2-bndtgugjgqc3dhdx.b01.azurefd.net/downloads/ca5c67098852b9f8355ef33d292d194372aa0c8d/macOS/StaticSitesClient",
        "sha": "ee27f20bc115ebeb5ea0b4c6bb4d93317712c67eeea18e5e822031425610466e"
      }
    }
  },
  {
    "version": "stable",
    "buildId": "53b7d0e07fe5c34bf68929fab92f87ce910288dc",
    "publishDate": "2024-10-24T20:43:23.5850191Z",
    "files": {
      "linux-x64": {
        "url": "https://swalocaldeployv2-bndtgugjgqc3dhdx.b01.azurefd.net/downloads/53b7d0e07fe5c34bf68929fab92f87ce910288dc/linux/StaticSitesClient",
        "sha": "66fca4b42cbc64d451097931ca4ed75649233bd818f97f0c3f6d1d75cff61413"
      },
      "win-x64": {
        "url": "https://swalocaldeployv2-bndtgugjgqc3dhdx.b01.azurefd.net/downloads/53b7d0e07fe5c34bf68929fab92f87ce910288dc/windows/StaticSitesClient.exe",
        "sha": "fc949fb19d29cce1e8b74cf1e2c31706426d46b3e03d830d601524cee63faa0b"
      },
      "osx-x64": {
        "url": "https://swalocaldeployv2-bndtgugjgqc3dhdx.b01.azurefd.net/downloads/53b7d0e07fe5c34bf68929fab92f87ce910288dc/macOS/StaticSitesClient",
        "sha": "89ec4fe61217325e89ed849a564ffe4cc51b61c325abdca82e8e441a4959ec92"
      }
    }
  },
  {
    "version": "backup",
    "buildId": "c25b033e400580829b0fea1fc7fb566139ab61c0",
    "publishDate": "2024-10-16T22:53:44.2035066Z",
    "files": {
      "linux-x64": {
        "url": "https://swalocaldeployv2-bndtgugjgqc3dhdx.b01.azurefd.net/downloads/c25b033e400580829b0fea1fc7fb566139ab61c0/linux/StaticSitesClient",
        "sha": "25a33db34c0647e1225755fb65a441c3ccfe523523f54a38f85c3ff6531aa475"
      },
      "win-x64": {
        "url": "https://swalocaldeployv2-bndtgugjgqc3dhdx.b01.azurefd.net/downloads/c25b033e400580829b0fea1fc7fb566139ab61c0/windows/StaticSitesClient.exe",
        "sha": "40e9339b57c2df7fafdddb73cee5f5ed10ad03841bd25796b3ea81b793b4bf66"
      },
      "osx-x64": {
        "url": "https://swalocaldeployv2-bndtgugjgqc3dhdx.b01.azurefd.net/downloads/c25b033e400580829b0fea1fc7fb566139ab61c0/macOS/StaticSitesClient",
        "sha": "aac8b80f43a40714f1d38a0c8c23752aaec5fc4cb32e05cd2c38ff9ef0a60f32"
      }
    }
  }
]


why this is incorrect type, expected object
