### ISSUE TITLE
Add config to disable `kubectl tool not found` message

### ISSUE THREAD

**Issue by li1234yun** [redhat-developer/vscode-yaml#693]
### Is your enhancement related to a problem? Please describe.
I always see the kubectl not found message when I open a yaml file, maybe the message can be disabled.

### Describe the solution you would like
Provide config to disable the message.

### Describe alternatives you have considered
No

### Additional context
This is my screen shapshot, I hope we can disable the message.

![image](https://user-images.githubusercontent.com/26505658/152715275-28732a64-f117-4ce0-933e-3ed23341870e.png)

**Comment by gorkem** [comment]
This is not coming from `vscode-yaml` as you can see from the `Source` of the dialog they are from the Kubernetes extension. I think they will be addressed soon https://github.com/vscode-kubernetes-tools/vscode-kubernetes-tools/issues/1023
