### ISSUE TITLE
YAML validation against multiple JSON schemas

### ISSUE THREAD

**Issue by cartu38** [redhat-developer/vscode-yaml#702]
I'm trying to check a yaml file against one or more JSON schema(s). I'm looking to specify schemas to be checked against as part of my yaml file header. Interest about is to get validation check running on a single file which may fulfill multiple non overlapping requirements. My high level need is to open some primary standard to some extension(s) which may be described Thanks additional dedicated schema(s).

I'm new if yaml not aware at all if such is possible or not ... please advise ! Any other possible way to fulfill my need ? Feel free !

I've got a try based on VSCode & RedHat dedicated extension. Up to now only first promoted schema is taken into account. I've no intellisense running based on second schema.

![valid](https://user-images.githubusercontent.com/26499918/155008288-d6c92821-d8f0-4d97-b1df-c16e8bf302ed.PNG)

**Comment by gorkem** [comment]
This is not a case that we handle at the moment. This extension always associates one schema with the whole file.  TBH implementing this enhancement would be a largish undertaking. 

One option that comes to my mind is using a top-level schema with `anyOf` keyword to combine them.

**Comment by VGRSTM** [comment]
@gorkem Thanks ! Works for me ! `anyOf` is very helpful here

![works](https://user-images.githubusercontent.com/71082832/155278895-2596a6cb-1e5a-4d8a-890c-e90464e5a242.PNG)
