### ISSUE TITLE
Unresolved tag: !vault in ansible yaml file

### ISSUE THREAD

**Issue by Sv9t** [redhat-developer/vscode-yaml#703]
## Describe the bug
When I add encrypted variable with ansible vault string in yaml file I get an syntax error.

## Expected Behavior
No syntax errors should be reported as this is a valid syntax
https://docs.ansible.com/ansible/latest/user_guide/vault.html

## Current Behavior
![Screenshot_13](https://user-images.githubusercontent.com/14145634/155088151-4ebddac4-cefc-4079-b8be-a8ff25120d48.png)

## Steps to Reproduce
1. Create yaml file
2. Ecryption string with ansible vault
3. Add encrypted string in yaml file

## Environment
- [ *] Windows

**Comment by gorkem** [comment]
@ssbarnea Any ideas?

**Comment by evidolob** [comment]
The `!vault` tag is not in core schema for yaml, and JSON Schemas does not allow to define yaml tags. 
To solve error, @Sv9t needs to add `!vault` tag in to [custom tag](https://github.com/redhat-developer/vscode-yaml#adding-custom-tags) preference.

**Comment by ssbarnea** [comment]
Or use the ansible language server for those files, which also allows you to encrypt and decrypt secrets... or proper auto-completes.

YAML extension is great, but it has limitations.

**Comment by gorkem** [comment]
For reference, @ssbarnea  refers to [ vscode-ansible](https://marketplace.visualstudio.com/items?itemName=redhat.ansible), which still utilizes this extension but adds more ansible specific features. 
Otherwise, custom tags are the other way to tackle this.
