### ISSUE TITLE
Problems when the filename is site.yml?

### ISSUE THREAD

**Issue by robo-wg** [redhat-developer/vscode-yaml#720]
When I name a file site.yml, everything in the file is marked as invalid. If I rename the file (e.g. _site.yml or sitexy.yml) everything fits. Unfortunately, however, I need exactly this file name. 

Error messages:

_Property xyz is not allowed 
Incorrect type. Expected "array_

Even with a completely empty file with the name site.yml the error "Incorrect type. Expected "array" is thrown.

What could be the reason for this or can someone reproduce it?

Thanks, Robert

**Comment by evidolob** [comment]
@robo-wg That error happened because your file name matches to: 
```json
{
      "name": "Ansible Playbook",
      "description": "Ansible playbook files",
      "url": "https://raw.githubusercontent.com/ansible-community/schemas/main/f/ansible-playbook.json",
      "fileMatch": [
        "playbook.yml",
        "playbook.yaml",
        "site.yml",
        "site.yaml",
        "**/playbooks/*.yml",
        "**/playbooks/*.yaml"
      ]
    },
```
From https://www.schemastore.org/json/ which we use to get JSON Schemas to validate yaml files.

If that behaviour is not what you want, you can disable `yaml.schemaStore.enable` in settings.
