### ISSUE TITLE
schemaStore.enable setting does not work as expected

### ISSUE THREAD

**Issue by tornike** [redhat-developer/vscode-yaml#721]
Because schema matching is not perfect I prefer **yaml.schemaStore** disabled, but every time vscode window is reloaded, even though setting is set to "false", schemas are applied anyway.
I have to enable this setting and then disable it manually and schemas are removed, but I have to do this procedure on every vscode reload/restart.

## Expected Behavior

When **yaml.schemaStore.enable** is set to "false", it should be considered even after reloads.

## Current Behavior

After reload/restart **yaml.schemaStore.enable** has no effect.

## Steps to Reproduce

1. Create file named _"deploy.yml"_ in .github/workflows directory. 2 schemas should be applied **Deployer Recipe** and **GitHub Workflow**.
![image](https://user-images.githubusercontent.com/29104009/159114463-1ae0feae-3799-4828-b5da-00dd72d3288e.png)
**Deployer Recipe** shows some errors.
2. Go to the settings and set **yaml.schemaStore.enable** to "false". Errors should disappear.
3. Close and reopen vscode or just run "Reload Window" from command Palette. Even though schemaStore is disabled now, schemas are applied anyway and **Deployer Recipe** again shows errors.
4. Now you can enable schemaStore and disable it again and errors disappear.

## Environment
- VSCode version: 1.65.2
- Extension version: v1.5.1
- OS: Ubuntu 20.04.1

**Comment by rickygao** [comment]
I am also suffering this, with the same viscose version and extension version on macOS Monterey.

**Comment by gorkem** [comment]
I can reproduce.
