### ISSUE TITLE
.travis.yml `osx_image: xcode9.2` is not an acceptable value

### ISSUE THREAD

**Issue by Deilan** [redhat-developer/vscode-yaml#73]
`osx_image: xcode9.2` is not an acceptable value for `.travis.yml` file.

![image](https://user-images.githubusercontent.com/4777512/37462558-7b96145a-2863-11e8-9640-4ca5c053dfad.png)

According to https://docs.travis-ci.com/user/reference/osx/#OS-X-Version it's valid though.

**Comment by JPinkney** [comment]
Once https://github.com/SchemaStore/schemastore/pull/421 is merged it will be fixed.

**Comment by JPinkney** [comment]
I think we can close this since SchemaStore/schemastore#421 has been merged.
