### ISSUE TITLE
Unclear how schema store versions are supported

### ISSUE THREAD

**Issue by paulcwarren** [redhat-developer/vscode-yaml#735]
## Summary
It's unclear how schema store versions are supported

## Relevant information
The schema store supports [versions of schema](https://github.com/SchemaStore/schemastore/blob/b3f603e54a6398dcd243113405c876cb9b938267/src/api/json/catalog.json#L57).  Seems like the yaml editor's footer selector will always just select the latest version.  

But if I wanted to edit an instance of this yaml file and make sure it was compliant version 3.0, not 3.1 (because perhaps I am not yet ready to adopt 3.1).  How would I go about that ensuring the editor was using the 3.0 schema, not the 3.1 schema?  

Do I perhaps set up a workspace schema using the URL of schema that I wish to use?

**Comment by paulcwarren** [comment]
I think I answered my own question.  At least I was able to configure my preferences with something like:

```
    "yaml.schemaStore.enable": false,
    "yaml.schemas": {
        "https://json.schemastore.org/airlock-microgateway-3.0.json":"microgateway-config.yaml"
    },
```    
I had to disable the schema store otherwise multiple schemas where used.

**Comment by gorkem** [comment]
We also have a PR in flight that will allow you to select schema versions listed from the store https://github.com/redhat-developer/vscode-yaml/pull/710
