### ISSUE TITLE
How to get `$ref`s working?

### ISSUE THREAD

**Issue by OnkelTem** [redhat-developer/vscode-yaml#743]
I read the documentation but couldn't find anything about using `$ref`s and how they get resolved.

Consider the following definitions:

**foo.schema.json**
```json
{
  "$id": "https://someprefix/foo",
  "title": "Foo",
  "type": "object",
  "properties": {
    "bar": { "$ref": "bar#" }
  },
  "required": ["bar"]
}
```

**bar.schema.json**
```json
{
  "$id": "https://someprefix/bar",
  "title": "Bar",
  "type": "object",
  "properties": {
    "value": { "type": "string" }
  },
  "required": ["value"]
}
```

As you see the `https://someprefix/foo` schema depends on the `https://someprefix/bar` one. The reference to from `foo` to `bar` is performed via `{ "$ref": "bar#" }`. Unfortunately it doesn't work with this plugin:

```yaml
# yaml-language-server: $schema=./foo.schema.json
bar:
  value: "hello"
```
results to a validation error: 
```
Problems loading reference 'file:///projects/bar': Unable to load schema from '/projects/bar': No content.YAML(768)
```

Is there a way to load all the schemas from a directory to get this resolution working? This is how [`Ajv` ](https://ajv.js.org/) resolution works for example.

**Comment by ssbarnea** [comment]
Read the docs from https://json-schema.org/understanding-json-schema/structuring.html#id19 and be very careful about the relative URLs. 

Hint: `#/$defs/foo` is what you want, and putting the ref inside `$defs`
