### ISSUE TITLE
YAML build issue

### ISSUE THREAD

**Issue by msivasubramaniaan** [redhat-developer/vscode-yaml#796]
## Describe the bug
Facing build issue while building YAML extension with latest YAML language server 1.9.0

## Expected Behavior
There should not be any error

## Current Behavior
The below error appears:
![image](https://user-images.githubusercontent.com/93245779/178708810-052e73ce-5e53-4ba3-85b9-5ce2648f73b0.png)

## Steps to Reproduce
1. yarn build

## Environment
- [x] Windows

**Comment by fbricon** [comment]
what change introduced that issue?

**Comment by msivasubramaniaan** [comment]
> what change introduced that issue?

I couldn't able to compile the extension in local and got the above mentioned error. The replace() is missing in the TelemeteryOutputChannel seems

**Comment by fbricon** [comment]
something's fishy here. I can compile the main branch with node 14.20.0 and `yarn build` without issue

**Comment by msivasubramaniaan** [comment]
I am using windows machine. Node v16.13.0 and Yarn v1.22.17

**Comment by msivasubramaniaan** [comment]
cleared the node modules and tried again, now the build got success. Hence closing this issue.

**Comment by fbricon** [comment]
so by default, yarn resolves @types/vscode to 1.61, which doesn't have the replace function, but if you force @types/vscode to 1.69, then replace() is needed. I don't know when it was introduced

**Comment by fbricon** [comment]
it starts breaking with @types/vscode 1.62

**Comment by msivasubramaniaan** [comment]
Better it is good to have the replace() in telemetry. Shall I reopen the issue in that case?

**Comment by fbricon** [comment]
So the change was introduced by https://github.com/microsoft/vscode/issues/132183
I'd like to bump @types/vscode to 1.62 at least. However I'm not sure whether that would have a negative impact on Theia compatibility, which starts dramatically lagging behind vscode: https://eclipse-theia.github.io/vscode-theia-comparator/filtered-status.html 

So adding the replace() function only is safe. Bumping @types/vscode version, I'm not too sure. @benoitf WDYT?

**Comment by msivasubramaniaan** [comment]
@fbricon shall I upgrade `@types/vscode` to 1.62 and further?

**Comment by benoitf** [comment]
For Theia I think it's ok to bump to 1.62

And on Che/DevSpaces side, default editor will be VS Code so it's fine to bump
