### ISSUE TITLE
Support for local schemas / schema check

### ISSUE THREAD

**Issue by kace91** [redhat-developer/vscode-yaml#80]
Hi, I'm starting to use the plugin and there are two questions that come to mind:

- Is there a way to use a local schema that isn't available through a URL? We're using a custom yaml-based format and we'd like to use its schema without the requirement of having it uploaded somewhere. If it is not currently possible, I'd like to submit that feature as a potential enhacenment.

- As a followup, is there any way to confirm that the schema defined through user settings is currently loaded? If not, it would be nice to have feedback regarding whether the file has been found, and/or if it's accepted as a valid schema. 

Thanks!

**Comment by JPinkney** [comment]
I believe using a relative path works but using an absolute path doesn't work.

I've tried with these and they don't work
```
"yaml.schemas": {
        "~/Documents/work/untitled/src/composer.json": "/*"
}

"yaml.schemas": {
        "/home/jpinkney/Documents/work/untitled/src/composer.json": "/*"
}
```

But these works fine for me
```
"yaml.schemas": {
        "./composer.json": "/*"
}

"yaml.schemas": {
        "../composer.json": "/*"
}
```

If you're looking to contribute absolute paths for schemas you might want to look around [this area](https://github.com/redhat-developer/yaml-language-server/blob/master/src/server.ts#L132)

**Comment by JPinkney** [comment]
> As a followup, is there any way to confirm that the schema defined through user settings is currently loaded? If not, it would be nice to have feedback regarding whether the file has been found, and/or if it's accepted as a valid schema.

I've added this as of [this](https://github.com/redhat-developer/yaml-language-server/commit/30baee003fcd8b22e2f13b5c7ce52a93ce28d842). It will be added Monday when we do a release.

**Comment by DKorchuganov** [comment]
> ```
> But these works fine for me
> 
> ```
> "yaml.schemas": {
>         "./composer.json": "/*"
> }
> 
> "yaml.schemas": {
>         "../composer.json": "/*"
> }
> ```
> If you're looking to contribute absolute paths for schemas you might want to look around [this area](https://github.com/redhat-developer/yaml-language-server/blob/master/src/server.ts#L132)

Sorry for a stupid question, @JPinkey, but the above paths are relative to which folder? .vscode or something else?

**Comment by JPinkney** [comment]
I believe its relative to the root of the project

**Comment by DKorchuganov** [comment]
> I believe its relative to the root of the project

Yeah, it works! Thanks a lot!

**Comment by dwtkns** [comment]
I was able to get absolute paths working by using the `file://` URI syntax for local files.

For example, this sort of thing didn't work:

```
"yaml.schemas": {
    "/Users/dwtkns/my-yaml-schema.json": "/my-yaml.yml"
}
```

...but this did:
```
"yaml.schemas": {
    "file:///Users/dwtkns/my-yaml-schema.json": "/my-yaml.yml"
}
```

**Comment by LunaticMaestro** [comment]
I followed similar approach on windows and it works
```
...
yaml.schemas": {
        
        "file:///C:/schema.json": "*.yaml",
...
```

Please merge the following PR  (@willismonroe )
https://github.com/redhat-developer/vscode-yaml/pull/742

Thanks.
