### ISSUE TITLE
Description in the schema root does not get displayed

### ISSUE THREAD

**Issue by fuyong2022** [redhat-developer/vscode-yaml#809]
## Describe the bug
When defining description at the root of the schema, this piece of information does not get displayed. 

## Expected Behavior
Description should be displayed when mouse hovers.

## Current Behavior
No description displayed when mouse hovers.

## Steps to Reproduce
1. Set title and description in the json schema.
2. Open yaml and see the top document bar, it shows: {title} ({name of schema file})
3. Mouse hover does not display anything for VSCode 1.70.2 and YAML v1.9.1

## Environment
- [X] Windows
- [ ] Mac
- [ ] Linux
- [ ] other (please specify)

**Comment by msivasubramaniaan** [comment]
@fuyong2022 can you please elaborate your issues? Where you hover currently? any examples?

**Comment by fuyong2022** [comment]
@msivasubramaniaan You can see at the top bar, the title is shown as "Global Azure Conventions and Settings"
![image](https://user-images.githubusercontent.com/102498768/187362747-92182b3d-cbb4-4c37-971d-9b3af9ec834a.png)

In my schema, I also defined description. But the description is not visible from VSCode. Should the description be displayed somewhere? 
![image](https://user-images.githubusercontent.com/102498768/187362906-d1ba3061-0787-4d80-b137-ddd4f86ba06f.png)

**Comment by msivasubramaniaan** [comment]
@fuyong2022 The issue was fixed and it will be available on the next v1.11.0
