### ISSUE TITLE
Property shows up multiple times in completions

### ISSUE THREAD

**Issue by afscrome** [redhat-developer/vscode-yaml#829]
## Describe the bug
If a schema uses `anyOf` and multiple objects have a property with the same name, but different sets of required fields, then that property shows up twice in auto completion (see example schema below).  

## Expected Behavior
In the below example, `spec` should only show in completions once.
![image](https://user-images.githubusercontent.com/289860/191842229-d090e916-b093-4012-b83b-4ae8c74d5869.png)

## Current Behavior

The `spec` field is shown in completions twice
![image](https://user-images.githubusercontent.com/289860/191841078-e3cd1202-7a1e-4ba8-b8dd-cd9632a58184.png)

## Steps to Reproduce

1.Create the below schema
2. Reference it in a yaml file
3. Start auto completion at the first character in the file

If you remove the `required` section in the second object, then completion correctly shows only one `spec` completion.

```json
{
    "$schema": "http://json-schema.org/draft-07/schema",
    "oneOf": [
        {
            "type": "object",
            "properties": {
                "spec": {
                    "type": "object"
                }
            }
        },
        {
            "properties": {
                "spec": {
                    "type": "object",
                    "required": [
                        "bar"
                    ],
                    "properties": {
                        "bar": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    ]
}
```

## Environment
- [X] Windows
- [ ] Mac
- [ ] Linux
- [ ] other (please specify)

**Comment by msivasubramaniaan** [comment]
@afscrome Here oneOf contains two properties and both name is **spec**.

1.  spec of object type
2.  spec of object with child property _bar_

So we can suggest user that all matching properties and used can pick the opt one

**Comment by afscrome** [comment]
In the VS Code JSON editor, this same schema only shows a single `spec` property
![image](https://user-images.githubusercontent.com/289860/191924443-63de9f3c-602d-4a9e-be14-d5155cb737bb.png)
So to does Rider
![image](https://user-images.githubusercontent.com/289860/191926135-7fe0ff83-b299-46a4-bc87-e6074dddf8ab.png)


The wider context in which I encountered this I'm trying to use Backstage's object schema for it's `catalog-info.yaml` files.  (This schema is heavily inspired by Kubenetes object format)
* json schema - https://json.schemastore.org/catalog-info.json
* docs - https://backstage.io/docs/features/software-catalog/descriptor-format, with a schema

If using this schema in the VS Code JSON editor or Rider, the the auto completions come out as expected, and are easy to use, with no duplicate property names
![image](https://user-images.githubusercontent.com/289860/191916816-aa29e65a-f45a-4635-9350-253c1ea303f8.png)
![image](https://user-images.githubusercontent.com/289860/191926288-16941d60-742a-43ed-81bd-c4ad56859daa.png)


But when I use this same schema with the VS Code YAML extension , the auto completions become overwhelming with duplicates, duplicated, to the point of not being very useful.  There are quite a few issues which I suspect are related, but I'm still trying to reduce them to a minimal repo

![image](https://user-images.githubusercontent.com/289860/191918483-d054c568-745f-4176-b74b-431b393cd163.png)
![image](https://user-images.githubusercontent.com/289860/191918067-85e08e86-7786-4119-9561-748725bad77e.png)

**Comment by msivasubramaniaan** [comment]
@afscrome Let me check and get back to you ASAP
