### ISSUE TITLE
yaml i18n

### ISSUE THREAD

**Issue by xiaoice** [redhat-developer/vscode-yaml#857]
### Is your enhancement related to a problem? Please describe.
Hello, I want to adapt [deploy-schema.json] to both Chinese and English languages. Is there any good solution

```
"yamlValidation": [
  {
  "fileMatch": "deploy.yml",
  "url": "./schema/deploy-schema.json"
  }
]
```

### Describe the solution you would like
When vscode.env.language is in Chinese, read deploy-schema-zh-cn.json
When vscode.env.language is in English, read deploy-schema-en.json

```
file: 
deploy-schema-zh-cn.json
deploy-schema-en.json
```

**Comment by gorkem** [comment]
We do not support i18n for schemas. The users just need to put the correct schema for the it language to the settings.
