### ISSUE TITLE
Cannot update/install redhat.vscode-yaml-0.0.12

### ISSUE THREAD

**Issue by amal-khailtash** [redhat-developer/vscode-yaml#86]
I cannot update or install newer version of this extension.

```
VSCode Version 1.23.1
Commit d0182c3417d225529c6d5ad24b7572815d0de9ac
Date 2018-05-10T16:04:33.747Z
Shell 1.7.12
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64
```
```
$ code --install-extension redhat.vscode-yaml
Found 'redhat.vscode-yaml' in the marketplace.
Installing...
ENOTEMPTY: directory not empty, rename '$HOME/.vscode/extensions/.redhat.vscode-yaml-0.0.12' -> '$HOME/.vscode/extensions/redhat.vscode-yaml-0.0.12'
```

**Comment by JPinkney** [comment]
I uninstalled and then reinstalled fine via the command line. Can you try removing $HOME/.vscode/extensions/.redhat.vscode-yaml-0.0.12 and $HOME/.vscode/extensions/redhat.vscode-yaml-0.0.12 and then reinstalling again

**Comment by amal-khailtash** [comment]
```
$ ls -l /home/akhailta/.vscode/extensions/redhat.vscode-yaml-0.0.12
total 4
drwxr-xr-x 8 akhailta wl4 4096 May 14 12:04 node_modules/

$ ls -l /home/akhailta/.vscode/extensions/redhat.vscode-yaml-0.0.12/node_modules/
total 24
drwxr-xr-x 5 akhailta wl4 4096 May 14 12:04 vscode-json-languageservice/
drwxr-xr-x 5 akhailta wl4 4096 May 14 12:04 vscode-languageserver/
drwxr-xr-x 4 akhailta wl4 4096 May 14 12:04 vscode-uri/
drwxr-xr-x 5 akhailta wl4 4096 May 14 12:04 vscode-yaml-languageservice/
drwxr-xr-x 5 akhailta wl4 4096 May 14 12:04 yaml-ast-parser/
drwxr-xr-x 3 akhailta wl4 4096 May 14 12:04 yaml-language-server/
```

**Comment by JPinkney** [comment]
Were you able to get it to install? I've just checked again and on 1.23.1 its working fine for me. Could it be some sort of permissions thing? Here is what shows for me when I do `ls -l` on redhat.vscode-yaml-0.0.12 and `ls -l` on redhat.vscode-yaml-0.0.12/node_modules

![selection_010](https://user-images.githubusercontent.com/8839537/40624581-6fcde9de-627b-11e8-8a73-e259f3ca5e97.png)

**Comment by amal-khailtash** [comment]
I did try it again just now and it did install this time around!  Not sure what the problem was.  It was quite persistent.  Thanks,

**Comment by JPinkney** [comment]
I'm glad to hear that! Maybe you restarted between then and now and that did the trick?
