### ISSUE TITLE
Extension silently fails to get kubernetes schema

### ISSUE THREAD

**Issue by ytimenkov** [redhat-developer/vscode-yaml#89]
Version: 0.0.12

There are 2 points in this issue:
1. `"kubernetes"` association doesn't work on my machine.
2. It provides absolutely no diagnostics/hint/error message why and whether it should work or not.

I spend quite much time trying to get completion and validation for my Kubernetes files: it just doesn't work, only suggestions I get are from VS Code's internal parser.

I tried enabling verbose tracing and I see only and at the moment I'm not sure what should be returned.
```
[Trace - 11:04:59 AM] Sending response 'custom/schema/request - (3)'. Processing request took 1ms
No result returned.
```

Digging through language server sources I found URL for Kubernetes schema, downloaded it and put it explicitly into config:
```json
    "yaml.schemas": {
        "file://home/default/openshift_schema_all.json": "packages/kubernetes/*.yaml"
    },
```

It started work and I see in log:
```
[Trace - 11:15:13 AM] Sending response 'custom/schema/request - (29)'. Processing request took 5ms
Result: "kubernetes://schema/v1@service"
```

I'm behind proxy which requires authentication and ssl check disabled and this may be causing issue.

**Comment by JPinkney** [comment]
The custom/scheme/request is something different that is used when someone builds an extension ontop of vscode-yaml. Try to see if there is a didChangeConfiguartion, that’s what will set the language server to use kubernetes schema internally.

**Comment by ytimenkov** [comment]
I saw that information which is sent to language server looked correct. This also confirmed by that changing "kubernetes" to local path makes it work.

I had doubts where to file issue: here or to language server, but as extension doesn't expose diagnostics from the language server I decided to start here.

**Comment by JPinkney** [comment]
The issue is fine to be in here, I work on both this extension and the language server. 

Just to make sure, it does work when you put in the local path but now when you use the url?

**Comment by ytimenkov** [comment]
Url doesn't work. Had "kubernetes" first, but I had only syntax highlighting: no validation, no hover hints, no completion. Changing to Url from language server sources had same effect.

So I blame connectivity (proxy, proxy authentication, fake ssl certificate).

**Comment by JPinkney** [comment]
This isn't my area of expertise so I'm not sure how much it will help but the language server can use VSCode's http.proxy and http.proxyStrictSSL settings to configure the http requests that the language server will do.

The relevant code on the extension side is [here](https://github.com/redhat-developer/yaml-language-server/blob/master/src/server.ts#L211)

**Comment by ytimenkov** [comment]
Let's start with diagnostics :D, e.g. notification that schema can't be downloaded and logging from language server.

As for httpProxy, I saw that either `proxy` or `strictSSL` (but not both) are passed to the language server when configuration changes. But this may be another separate issue.

**Comment by JPinkney** [comment]
> Let's start with diagnostics :D, e.g. notification that schema can't be downloaded and logging from language server.

I can do that. I'll open up an issue on the yaml-language-server.

> As for httpProxy, I saw that either proxy or strictSSL (but not both) are passed to the language server when configuration changes. But this may be another separate issue.

This is whats being sent for me 
```json
Sending notification 'workspace/didChangeConfiguration'.
Params: {
    "settings": {
        "yaml": {
            "trace": {
                "server": "verbose"
            },
            "schemas": {
                "kubernetes": "/*"
            },
            "format": {
                "enable": true
            },
            "validate": true,
            "customTags": []
        },
        "http": {
            "proxy": "blahblahblah2",
            "proxyStrictSSL": true
        }
    }
}
```

**Comment by ytimenkov** [comment]
Cool! Thanks for quick response.
