### ISSUE TITLE
Support examples property in VS Code

### ISSUE THREAD

**Issue by JacekArdanowski** [redhat-developer/vscode-yaml#896]
Hi,
I would like to suggest new feature for displaying "examples" property in JSON Schema when on hover.

### Describe the solution you would like
According to the standard:

> New in draft 6 The **examples** keyword is a place to provide an array of examples that validate against the schema.
https://json-schema.org/understanding-json-schema/reference/generic.html

I would like to see examples field below description when hovering over the field that contains "examples" in JSON schema (see screenshot below)

### Additional context
For example for timeout property defined like below:
<img width="331" alt="image" src="https://user-images.githubusercontent.com/83065856/223518756-71f44591-166f-47d3-a38f-d609f88bce24.png">
I'd like to see the examples property below the description:
<img width="289" alt="image" src="https://user-images.githubusercontent.com/83065856/223518923-a533b9f8-f8d6-4019-a0c2-39b06da7f61d.png">

Also, I'm not sure what does "Source" here mean, any idea?

**Comment by LeShaunJ** [comment]
I believe this is already a feature; however, the rendering of it is _less than ideal_. Given the following:

<img width="304" alt="image" src="https://github.com/redhat-developer/vscode-yaml/assets/5474674/45a523e7-df0a-4402-8694-7b4d6f169c10">

 It appears to render whitespace as raw HTML entity codes:

<img width="644" alt="image" src="https://github.com/redhat-developer/vscode-yaml/assets/5474674/5eb7c8ad-6887-4b18-a5b4-ff769de0e661">

What I think we'd all appreciate is that it render such examples as syntax-highlighted YAML.
