### ISSUE TITLE
GitHub Actions YAML - error is false for self-hosted runner

### ISSUE THREAD

**Issue by scott-doyland-burrows** [redhat-developer/vscode-yaml#911]
See the screenshot below.

The runner name is valid - it is a self-hosted runner - but the YAML schema says it is invalid.

![image](https://user-images.githubusercontent.com/61512176/226991067-e3de93df-e254-4f1d-a4d0-f1dfd1c3d28d.png)

**Comment by gorkem** [comment]
This project does not provide the schema, which should probably be reported elsewhere.

**Comment by scott-doyland-burrows** [comment]
Thanks - did some digging and found a previous issue in the repo that holds the schema.  Looks like it was actually a change I needed to make in my workflow to comply with GitHub Actions recommendations re self-hosted runner config in the workflow.
