### ISSUE TITLE
Map keys must be unique in Gitlab yml syntax

### ISSUE THREAD

**Issue by steward93** [redhat-developer/vscode-yaml#913]
Hi,

Am trying to deploy both my internal and external job at once using gitlab pipeline. Below is my code where I have defined my internal job and external job template by specifying server names in my pipeline. This works if I make the operator to run as <<: ["internal_job" ,"external_job"] but I'm trying to invoke different scripts for internal and external job separately hence my code looks like below and I do get error  "Map keys must be unique" in my external_deploy stage. Does gitlab allow us to call multiple templates(like how am calling here internal_deploy and external_deploy) under single stage or is there any alternative way forward. I tried my yml file to preceed with %YAML 1.1 but it did not work.

My intention is to run both internal and external job at same time.

deploy_all_internal_external:
  stage: internal_deploy
  <<: *internal_job
  script:
    - *rotate_logs
  stage: external_deploy
  <<: *external_job 
  script:
     - *deploy_external_only_src

**Comment by gorkem** [comment]
This project provides generic YAML language support and JSON schema-based validation. The error you have mentioned, `Map keys must be unique,` is part of the YAML specification. In the example you have posted (although the indentation is broken and indentation matters to YAML), it looks like the `stage` is a repeated key and violates this rule.
