### ISSUE TITLE
Relative paths for schemas not working anymore

### ISSUE THREAD

**Issue by labarilem** [redhat-developer/vscode-yaml#92]
Hi,

I have a JSON schema file in my project that I want to apply to several YAML files.

This is my `.vscode/settings.json`:

```json
{
  "yaml.format.enable": true,
  "yaml.schemas": {
    "./my.schema.json": "*.repo.yml"
  }
}
```

where `./my.schema.json` is the relative path to my JSON schema file.

This configuration was working as intended until yesterday. Now it only works if I specify an absolute path for the JSON schema file.

Any ideas?

Thanks 😄

**Comment by JPinkney** [comment]
I'm unsure what would have broke but I'll look into it.

**Comment by matulkum** [comment]
maybe it was not a change on the extensions, which broke it, but an update from vscode?

**Comment by labarilem** [comment]
Hi @JPinkney , any updates? 😄

**Comment by JPinkney** [comment]
Should be in the next release on July 9th.

**Comment by labarilem** [comment]
This issue is still present using the latest VSCode version.

**Comment by JPinkney** [comment]
That's because it hasn't been released yet. There has been issues with the release process that we are still trying to figure out.

**Comment by gdimauro** [comment]
any updates?

**Comment by JPinkney** [comment]
Just released. It should be fixed. Apparently the language client dependency switched from relative paths to absolute paths so I just had to lower that and it should be back to normal.

**Comment by labarilem** [comment]
I can confirm that it's working now, thanks 😄
