### ISSUE TITLE
Reading proxy settings from vscode user settings doesn't work

### ISSUE THREAD

**Issue by dmilosz** [redhat-developer/vscode-yaml#920]
## Describe the bug
Proxy from vscode user settings is not read by the extension properly, so that it's not possible to use proxy settings settings from vscode and only system HTTP_PROXY and HTTPS_PROXY environment variables are respected, because of implementation in `request-light` package.

## Expected Behavior
vscode-yaml extension should correctly respect user proxy vscode settings.

## Current Behavior
Only system environment variables HTTP_PROXY, HTTPS_PROXY and their lowercase alternatives are respected.

## Steps to Reproduce

1. In vscode, open user settings tab: `F1 -> Preferences: Open User Settings -> Application -> Proxy`
2. Write your specific proxy address, which is different than the one in HTTP_PROXY or HTTPS_PROXY environment variables.
3. Try to access resource which is only available when using the proxy. 

## Environment
- [x] Windows
- [x] Mac
- [x] Linux

**Comment by gorkem** [comment]
PR is merged and released. I suppose this is fixed now, closing.
