### ISSUE TITLE
Overriding multiple anchors in one node triggers a linter error

### ISSUE THREAD

**Issue by thepunkoff** [redhat-developer/vscode-yaml#924]
## Describe the bug
Minimal reproduction file causes a linter error: "Map keys must be unique":
```
foo: &foo
  a: 1
bar: &bar
  a: "bar"
baz:
  <<: *bar
  <<: *foo
```

## Expected Behavior
I expect no linter errors, since this is allowed in YAML.

## Current Behavior
<img width="231" alt="image" src="https://user-images.githubusercontent.com/48530881/234586393-1b9a8e7c-76b1-46c1-901a-9b52423bc4d7.png">

## Steps to Reproduce
Open the provided file in vscode with enabled Yaml extension.

## Environment
- [x] Windows
- [ ] Mac
- [ ] Linux
- [ ] other (please specify)

**Comment by Fryguy** [comment]
I'm having this exact issue.  Thanks for reporting @thepunkoff

**Comment by legowerewolf** [comment]
Also getting this on Mac.

**Comment by gorkem** [comment]
@eemeli I think this is coming from the parser

**Comment by eemeli** [comment]
This is allowed in YAML 1.1, but the library and extension default to YAML 1.2, which attaches no special meaning to the `<<` key. This is controllable in the extension settings by setting `"yaml.yamlVersion": "1.1"`, or in the document itself by adding a directive `%YAML 1.1`.

@gorkem It might make sense to special-case this error to be more informative in the extension?

**Comment by Fryguy** [comment]
Wow TIL and also that's really annoying.  More information here: https://stackoverflow.com/a/64228697/2355944

I like that there's a workaround where you can do

```
<<: [*map1-ref, *map2-ref]
```

In the "real world" there are going to be a lot of YAMLs that have multiple `<<:` keys, so it might be worth special casing support for it or perhaps making it a warning as opposed to an error.

**Comment by eemeli** [comment]
@Fryguy Tbf, the issue here is that you're implicitly relying on version-specific behaviour that was removed from the YAML spec in 2009, i.e. 14 years ago. I would recommend including a directive `%YAML 1.1` in your file to make this clear.

**Comment by gorkem** [comment]
@eemeli Is this error coming with a different error code than `DUPLICATE_KEY` if so we can differentiate the message

**Comment by eemeli** [comment]
@gorkem It's a duplicate-key error where the key at the start of the range is `<<`.

**Comment by Fryguy** [comment]
> Wow TIL and also that's really annoying.

I just realized my comment could have been taken personally, so if that's the case I apologize. My comment there was not directed towards any person nor this project, but directed towards the spec itself in that the merge key isn't specified at all.

Thanks for all the great work here!

**Comment by AdySnowflake** [comment]
> Wow TIL and also that's really annoying. More information here: https://stackoverflow.com/a/64228697/2355944哇，今天我学到了，而且这真的很烦人。更多信息请查看：https://stackoverflow.com/a/64228697/2355944
> 
> I like that there's a workaround where you can do我喜欢有一个解决方法，你可以这样做
> 
> ```
> <<: [*map1-ref, *map2-ref]
> ```
> 
> In the "real world" there are going to be a lot of YAMLs that have multiple `<<:` keys, so it might be worth special casing support for it or perhaps making it a warning as opposed to an error.在“现实世界”中，会有很多 YAML 文件具有多个 `<<:` 键，因此可能值得为其提供特殊支持，或者将其作为警告而不是错误。

thanks! it's useful!
