### ISSUE TITLE
Unset JOSN schema for specific files

### ISSUE THREAD

**Issue by b1zzu** [redhat-developer/vscode-yaml#939]
### Is your enhancement related to a problem? Please describe.

Bitbucket Pipelines is an awful JSON schema support, and it just flags a lot of lines as errors while they are actually correct. As Atlassian doesn't provide a full-up-to-date schema, the only thing I can do is disable it. 

### Describe the solution you would like

The option of disabling the json schema from the UI or settings:
![image](https://github.com/redhat-developer/vscode-yaml/assets/7964685/b99dcf76-c0d5-42ef-af85-0cd126969788)

**Comment by gorkem** [comment]
What exactly is the enhancement you are looking for? The definition is confusing.

**Comment by maks** [comment]
I can't speak for the original poster, but to me it sounds like what I would like as well: the option to tell the extension to **Not** apply any schema to the current Yaml file. Failing that the ability to create a list of excluded filenames in the extensions settings 
eg. 
`yaml.ignore_schema_files: ["myunknownyamlfile.yaml", "someother.yaml"]` 

would be great.

**Comment by maks** [comment]
Actually my apologies, I just read the documentation more closely and realised that this can be achieved by using a [custom schema association](https://github.com/redhat-developer/vscode-yaml#associating-a-schema-to-a-glob-pattern-via-yamlschemas).

**Comment by gorkem** [comment]
Closing as there is no further clarifications
