### ISSUE TITLE
Argo Workflows and Argo Events schemas not available in UI though they appear in catalog

### ISSUE THREAD

**Issue by sgtsquiggs** [redhat-developer/vscode-yaml#945]
## Describe the bug
Cannot load schemas `Argo Workflows` or `Argo Events` via the UI. They both appear in the schema catalog [here](https://github.com/SchemaStore/schemastore/blob/c473755ed8240b3d57ca2c970fc0e20eff934ed8/src/api/json/catalog.json#L282-L290).

They just do not appear in the JSON schema menu at all.

## Expected Behavior
All available schemas in the schema catalog should be loaded and available

## Current Behavior
Not all schemas are available

## Steps to Reproduce

1. Add YAML extension
2. Configure to enable schema store
    <img width="522" alt="image" src="https://github.com/redhat-developer/vscode-yaml/assets/3420325/bede65fc-afdf-4520-8171-51ad4f6ad7ef">
4. Open any yaml file
5. Attempt to set schema to `Argo Workflows` (I searched for "workflows")
    <img width="625" alt="image" src="https://github.com/redhat-developer/vscode-yaml/assets/3420325/edabb9fc-6db4-4df4-b5e8-876b4f3ff06c">

## Environment
- [ ] Windows
- [x] Mac
- [ ] Linux
- [ ] other (please specify)

**Comment by sgtsquiggs** [comment]
In the `Select JSON schema` image above, the item `https://raw.githubusercontent.com/argoproj/argo-workflows/master/api/jsonschema/sche...` appears because I have manually associated it with files `wf-*.yaml` in my workspace config.

**Comment by gorkem** [comment]
This is because the catalogue entry has no file match entry for argo workflows JSON schema and the extension filters according to the file match. What you have done with `wf-*.yaml` association in the workspace config is the right way to work with such schemas.

**Comment by sgtsquiggs** [comment]
Hmmm but I cannot even select the schema from the list of available schemas using the menu in the toolbar.

I was attempting to manually assoc the file with the schema (via the menu) but didn't see it so I manually referenced it in settings.

**Comment by gorkem** [comment]
The menu on the toolbar's purpose is to select the correct schema when multiple schemas are mapped to the file from the catalogue through file matches and settings. It is not a general tool for browsing the schema catalogue and selecting the schema from the catalogue.

**Comment by sgtsquiggs** [comment]
Ah, got it 👍
