### ISSUE TITLE
Sort feature

### ISSUE THREAD

**Issue by gdlx** [redhat-developer/vscode-yaml#95]
Hi,

It would be nice to add a keys sorting feature. I use this a lot under Atom for my locale translations files: https://github.com/elledienne/easysort-yaml

**Comment by phyllisstein** [comment]
I'd love to see this as well. For the time being I can sometimes get away with [converting YAML to JSON](https://marketplace.visualstudio.com/items?itemName=tuxtina.json2yaml) and [sorting the result](https://marketplace.visualstudio.com/items?itemName=richie5um2.vscode-sort-json), but it's a pretty silly kludge.

**Comment by gorkem** [comment]
There is already a [good solution](https://marketplace.visualstudio.com/items?itemName=PascalReitermann93.vscode-yaml-sort) for this on the marketplace. I am not sure if there are any advantages to duplicating that functionality in this extension.

**Comment by schlomo** [comment]
Can you please reopen this? `vscode-yaml-sort`removes comments on sorting which IMHO is a reason to not use it: https://github.com/pascalre/vscode-yaml-sort/issues/39

I'd therefore be really thankful if `vscode-yaml` could provide a better sorting solution

**Comment by gregpavl** [comment]
is there any update about this `enhancement`?

**Comment by borontion** [comment]
I also really need this feature. If there is no plan from the owner of this repo, I can try to implement and send a pr.

**Comment by gorkem** [comment]
This was fixed with https://github.com/redhat-developer/yaml-language-server/pull/839 please give it a try.

**Comment by huxuan** [comment]
> This was fixed with [redhat-developer/yaml-language-server#839](https://github.com/redhat-developer/yaml-language-server/pull/839) please give it a try.

Hi @gorkem, thanks for the great feature. Just want to ensure whether it is sort keys on format supported? Seems I failed to make it though it is mentioned to have a code action in the pull request.
