### ISSUE TITLE
Disable schema store connection

### ISSUE THREAD

**Issue by OwenMcDonnell** [redhat-developer/vscode-yaml#98]
Is there a way to disable any connection to the schema store? Locally mapped schemas seem to be combining with those from the schema store making development of new schemas difficult.

**Comment by JPinkney** [comment]
Not currently but I can add that

**Comment by OwenMcDonnell** [comment]
Actually, now i wonder if its really all that useful since its pretty easy to just rename the file you're targeting to something that's not represented in the schema store.

**Comment by peterm0x** [comment]
It would be useful if locally mapped schemas override those from schema store. For example currently AWS SAM is linked to older schema file thus failing to recognize added elements. Also, file naming could not be easily changed due to tooling / company policies.

**Comment by JPinkney** [comment]
This has been added in 0.3.0. We now have a setting called yaml.schemaStore.enable that when set to false, stops the extension from automatically pulling schemas from the schema store. Basically, this just means that you will need to set schemas yourself.
