### ISSUE TITLE
Autocompletion does not work with custom schema

### ISSUE THREAD

**Issue by yogeek** [redhat-developer/vscode-yaml#99]
First, thanks for this plugin !

I am trying to use it to write a yaml file corresponding to the schema of a Jenkins plugin (https://github.com/jenkinsci/configuration-as-code-plugin).
The schema is configured like this (I make it available locally because it is dynamically generated from a live Jenkins instance) :
```
  "yaml.schemas": {
    "http://localhost:8080/schema.json": "/jenkins.yml"
  }
```

When editing the file in VSCode, it seems to be known (no error indicating that the schema is not found) but no autocomplation is available.
Does it normally work directly or do I have to enable it ?

Here is the [schema](https://raw.githubusercontent.com/yogeek/jenkins-dood/master/schema.json) for information

**Comment by JPinkney** [comment]
Hi! Is this still an issue? If it is can you check a few things:

1. Does:
```
"yaml.schemas": {
    "https://raw.githubusercontent.com/yogeek/jenkins-dood/master/schema.json": "jenkins.yaml"
}
```

work correctly?

If it does then can you try 
```
"yaml.schemas": {
  "http://localhost:8080/schema.json": "jenkins.yml"
}
```
(without the / before jenkins.yml)

**Comment by Geekarette** [comment]
Hi @JPinkney 

Just tested, the 1. does not work : no completion and no documentation when hover the nodes...

Version : 
VSCode : 1.43.2
yaml plugin = 0.7.2

**Comment by yogeek** [comment]
Hi @JPinkney 

Just tested on a brand new clean installation of VS Code and the 1. still does not work : no completion and no documentation when hover the nodes...

Version : 
VSCode : 1.43.2
yaml plugin = 0.7.2

**Comment by JPinkney** [comment]
This is what I see when I try to autocomplete from my side:
![image](https://user-images.githubusercontent.com/8839537/78410513-90bf5500-75da-11ea-9f85-bf93bc30b1e9.png)
![image](https://user-images.githubusercontent.com/8839537/78410537-a3d22500-75da-11ea-9a91-bdb911d8acc3.png)

It doesn't look like the schema itself has any documentation in the json schema so thats why hovering the nodes won't show anything. Can you try setting the yaml.trace.server setting to be verbose (like in the second picture). Then can you copy and paste the contents of the vscode-yaml output channel (available from view -> output -> then change the dropdown on the right to be YAML support)

**Comment by yogeek** [comment]
Ok so in fact, in my last message i did not tested on an empty yamlfile but on an existing one :

- on an empty `jenkins.yaml` : I have the root nodes propositions for autocompletion like you :

![image](https://user-images.githubusercontent.com/9500406/78422514-176a4580-7660-11ea-8005-88a940d4bdc1.png)

- but once I choose one of the root node, no child node is proposed, only the parent node again :

![image](https://user-images.githubusercontent.com/9500406/78422536-3a94f500-7660-11ea-84c2-57a5583dd825.png)

![image](https://user-images.githubusercontent.com/9500406/78422547-526c7900-7660-11ea-8639-885f7b031b12.png)

**Comment by yogeek** [comment]
@JPinkney **_UPDATE_** : it appears that, since I opened this issue a year and half ago, the project providing the schema evolved to a new version (details here : https://github.com/jenkinsci/configuration-as-code-plugin/blob/master/docs/features/jsonSchema.md)

So I just tried to install a new Jenkins version with the last plugin and the schema seems to work correctly now :

![image](https://user-images.githubusercontent.com/9500406/78422936-33bbb180-7663-11ea-8cf5-2b83e0dc6a66.png)


So sorry about my previous message, it came from the schema which was generated by the jenkins plugin and was apparently invalid. As you can see in the linked page above, they now have a v2 version which is correct and compatible with IDE validation and completion features.

FYI : I updated the schema [here](https://raw.githubusercontent.com/yogeek/jenkins-dood/master/schema.json) if you want to check

Thank you for your help !

**Comment by JPinkney** [comment]
So everything is working now? I'm glad I could help! Is this issue okay to close?

**Comment by yogeek** [comment]
Yes it seems to work well now, thanks again
